#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Chèn 30 mục mới (6 nhóm) nâng tổng lên 180 loài. Idempotent. python3 scripts/add-180-data.py"""
import json, os
BASE = os.path.join(os.path.dirname(__file__), '..'); PATH = os.path.join(BASE, 'data', 'tu-dien-nong-lam-ngu.json')

# ===== LÂM NGHIỆP — cây (schema thực vật) =====
NGAP_MAN = [
 {"id":"duoc","ten":"Đước","tenKhoaHoc":"Rhizophora apiculata","tenKhac":"Mangrove · đước đôi","nhom":"ngap-man",
  "ho":"Đước (Rhizophoraceae)","phanLoai":{"bo":"Sơ ri (Malpighiales)","ho":"Đước (Rhizophoraceae)","chi":"Rhizophora","loai":"R. apiculata"},
  "moTa":"Đước là cây trụ cột của rừng ngập mặn ven biển VN, rễ chống vươn ra giữ đất, chắn sóng, là 'lá phổi' và lá chắn của vùng cửa biển.",
  "hinhThai":"Cây gỗ với hệ rễ chống cong vươn từ thân xuống bùn; lá đơn dày bóng; quả nảy mầm ngay trên cây thành trụ mầm dài.",
  "loaiThan":"Cây gỗ rễ chống","chieuCao":"15–25 m","chuKy":"Cây lâu năm","anhSang":"Ưa sáng",
  "nuoc":"Ngập mặn – lợ theo thủy triều","loaiDat":"Bùn lầy ven biển, cửa sông","vungTrong":"Cà Mau, Cần Giờ, Đồng bằng Sông Cửu Long, ven biển miền Trung",
  "nhanGiong":"Cắm trụ mầm xuống bùn","thoiGianThuHoach":"—","nangSuat":"—",
  "giaTri":"Chắn sóng, giữ đất, hấp thụ carbon; gỗ làm than đước; là 'nhà trẻ' cho tôm cá.","boPhanDung":"Gỗ làm than, cọc; rừng phòng hộ & nuôi tôm sinh thái.",
  "baoTon":"Rừng phòng hộ được bảo vệ; suy giảm do phá rừng nuôi tôm.",
  "xuatXu":"Loài bản địa rừng ngập mặn nhiệt đới.","suThatThuVi":"Hạt đước nảy mầm ngay khi còn trên cây mẹ (thai sinh), rụng xuống cắm thẳng vào bùn mọc thành cây con.",
  "mauDacTrung":["#3a5a3a","#7a6a4a"],"nguon":"https://vi.wikipedia.org/wiki/%C4%90%C6%B0%E1%BB%9Bc"},
 {"id":"mam","ten":"Mắm","tenKhoaHoc":"Avicennia marina","tenKhac":"Grey mangrove","nhom":"ngap-man",
  "ho":"Ô rô (Acanthaceae)","phanLoai":{"bo":"Hoa môi (Lamiales)","ho":"Ô rô (Acanthaceae)","chi":"Avicennia","loai":"A. marina"},
  "moTa":"Cây mắm là loài tiên phong lấn biển — mọc trước nhất trên bãi bồi, rễ thở tua tủa giúp giữ phù sa cho đước theo sau.",
  "hinhThai":"Cây gỗ nhỏ với vô số rễ thở (cọc) nhô lên khỏi bùn quanh gốc; lá xám bạc mặt dưới; quả nang dẹt.",
  "loaiThan":"Cây gỗ rễ thở","chieuCao":"3–10 m","chuKy":"Cây lâu năm","anhSang":"Ưa sáng",
  "nuoc":"Ngập mặn","loaiDat":"Bãi bồi mặn ven biển","vungTrong":"Ven biển Cà Mau, Bến Tre, miền Trung",
  "nhanGiong":"Gieo hạt tự nhiên","thoiGianThuHoach":"—","nangSuat":"—",
  "giaTri":"Tiên phong lấn biển, giữ phù sa, chắn sóng; gỗ làm củi.","boPhanDung":"Rừng phòng hộ; gỗ củi.",
  "baoTon":"Được bảo vệ trong rừng phòng hộ ven biển.",
  "xuatXu":"Loài bản địa bãi triều nhiệt đới.","suThatThuVi":"Rễ thở của mắm mọc thẳng đứng khỏi mặt bùn để 'thở' khi triều rút — vì đất ngập mặn rất thiếu oxy.",
  "mauDacTrung":["#5a6b5a","#cabfa0"],"nguon":"https://vi.wikipedia.org/wiki/Chi_M%E1%BA%AFm"},
 {"id":"ban","ten":"Bần","tenKhoaHoc":"Sonneratia caseolaris","tenKhac":"Mangrove apple","nhom":"ngap-man",
  "ho":"Bần (Lythraceae)","phanLoai":{"bo":"Sim (Myrtales)","ho":"Bần (Lythraceae)","chi":"Sonneratia","loai":"S. caseolaris"},
  "moTa":"Cây bần mọc ven sông nước lợ, quả chua dùng nấu canh; rễ thở nhô lên giữ bờ chống sạt lở.",
  "hinhThai":"Cây gỗ tán rộng, rễ thở hình nón quanh gốc; hoa lớn nhị trắng – đỏ nở đêm; quả tròn dẹt màu xanh.",
  "loaiThan":"Cây gỗ rễ thở","chieuCao":"5–15 m","chuKy":"Cây lâu năm","anhSang":"Ưa sáng",
  "nuoc":"Nước lợ ven sông","loaiDat":"Bùn ven sông cửa biển","vungTrong":"Đồng bằng Sông Cửu Long, ven sông nước lợ",
  "nhanGiong":"Gieo hạt","thoiGianThuHoach":"Quả thu quanh năm","nangSuat":"—",
  "giaTri":"Giữ bờ chống sạt lở; quả bần chua là đặc sản (canh chua, mứt).","boPhanDung":"Quả ăn (nấu canh chua, làm mứt); cây giữ bờ.",
  "baoTon":"Phổ biến ven sông; được trồng giữ bờ.",
  "xuatXu":"Loài bản địa vùng cửa sông nhiệt đới.","suThatThuVi":"Hoa bần nở về đêm và do dơi, bướm đêm thụ phấn — sáng ra đã tàn.",
  "mauDacTrung":["#5a7a4a","#c9b06a"],"nguon":"https://vi.wikipedia.org/wiki/B%E1%BA%A7n_chua"},
 {"id":"vet","ten":"Vẹt","tenKhoaHoc":"Bruguiera gymnorhiza","tenKhac":"Orange mangrove","nhom":"ngap-man",
  "ho":"Đước (Rhizophoraceae)","phanLoai":{"bo":"Sơ ri (Malpighiales)","ho":"Đước (Rhizophoraceae)","chi":"Bruguiera","loai":"B. gymnorhiza"},
  "moTa":"Vẹt là cây ngập mặn có rễ đầu gối cong gập đặc trưng, mọc cùng đước tạo nên rừng ngập mặn nhiều tầng.",
  "hinhThai":"Cây gỗ với rễ hình đầu gối cong lên khỏi bùn; lá bóng; đài hoa đỏ hình sao; trụ mầm dài như điếu xì gà.",
  "loaiThan":"Cây gỗ rễ đầu gối","chieuCao":"8–20 m","chuKy":"Cây lâu năm","anhSang":"Ưa sáng",
  "nuoc":"Ngập mặn","loaiDat":"Bùn mặn ổn định","vungTrong":"Rừng ngập mặn Cà Mau, Cần Giờ",
  "nhanGiong":"Cắm trụ mầm","thoiGianThuHoach":"—","nangSuat":"—",
  "giaTri":"Giữ đất, chắn sóng cùng đước; gỗ làm củi, than; vỏ chứa tanin.","boPhanDung":"Gỗ củi, than; vỏ lấy tanin nhuộm.",
  "baoTon":"Được bảo vệ trong rừng phòng hộ.",
  "xuatXu":"Loài bản địa rừng ngập mặn.","suThatThuVi":"Rễ vẹt cong gập như đầu gối nhô lên rồi cắm lại xuống bùn — kiểu rễ độc đáo để vừa thở vừa bám đất lầy.",
  "mauDacTrung":["#3a5a4a","#9c3a2e"],"nguon":"https://vi.wikipedia.org/wiki/Chi_V%E1%BA%B9t"},
 {"id":"su","ten":"Sú","tenKhoaHoc":"Aegiceras corniculatum","tenKhac":"River mangrove","nhom":"ngap-man",
  "ho":"Anh thảo (Primulaceae)","phanLoai":{"bo":"Thạch nam (Ericales)","ho":"Anh thảo (Primulaceae)","chi":"Aegiceras","loai":"A. corniculatum"},
  "moTa":"Sú là cây bụi ngập mặn nhỏ mọc mép rừng, hoa trắng thơm hút ong, là nguồn mật rừng ngập mặn quý.",
  "hinhThai":"Cây bụi nhỏ, lá dày bóng, chùm hoa trắng thơm, quả cong hình sừng.",
  "loaiThan":"Cây bụi","chieuCao":"1–4 m","chuKy":"Cây lâu năm","anhSang":"Ưa sáng",
  "nuoc":"Ngập mặn – lợ","loaiDat":"Bùn mặn mép rừng","vungTrong":"Rừng ngập mặn Bắc Bộ & Nam Bộ",
  "nhanGiong":"Gieo hạt","thoiGianThuHoach":"—","nangSuat":"—",
  "giaTri":"Giữ đất mép rừng; hoa cho mật ong rừng ngập mặn (mật sú vẹt).","boPhanDung":"Cây phòng hộ; hoa nuôi ong lấy mật.",
  "baoTon":"Phổ biến trong rừng ngập mặn được bảo vệ.",
  "xuatXu":"Loài bản địa vùng triều.","suThatThuVi":"Mật ong từ hoa sú vẹt rừng ngập mặn là loại mật rừng đặc sản, hương vị riêng của vùng cửa biển.",
  "mauDacTrung":["#4a6b4a","#e8e2d2"],"nguon":"https://vi.wikipedia.org/wiki/S%C3%BA"},
]
CAY_CANH = [
 {"id":"phuong-vi","ten":"Phượng vĩ","tenKhoaHoc":"Delonix regia","tenKhac":"Royal poinciana · phượng","nhom":"cay-canh",
  "ho":"Đậu (Fabaceae)","phanLoai":{"bo":"Đậu (Fabales)","ho":"Đậu (Fabaceae)","chi":"Delonix","loai":"D. regia"},
  "moTa":"Phượng vĩ là cây bóng mát gắn với sân trường và mùa hè; hoa đỏ rực nở tháng 5–6 báo hiệu mùa thi, mùa chia tay.",
  "hinhThai":"Cây gỗ tán rộng hình dù; lá kép lông chim hai lần mảnh như lá me; hoa đỏ cam rực; quả đậu dẹt dài hóa gỗ.",
  "loaiThan":"Cây gỗ","chieuCao":"10–15 m","chuKy":"Cây lâu năm","anhSang":"Ưa nắng",
  "nuoc":"Trung bình, chịu hạn","loaiDat":"Đất thoát nước tốt","vungTrong":"Trồng khắp đô thị, sân trường cả nước",
  "nhanGiong":"Gieo hạt","thoiGianThuHoach":"—","nangSuat":"—",
  "giaTri":"Cây bóng mát & cảnh quan biểu tượng học trò; hoa đẹp rực rỡ mùa hè.","boPhanDung":"Tán cho bóng mát; hoa làm cảnh.",
  "baoTon":"Cây trồng phổ biến — không bị đe dọa.",
  "xuatXu":"Nguồn gốc Madagascar, trồng làm cảnh khắp VN.","suThatThuVi":"Phượng vĩ gắn liền với 'mùa phượng' học trò — hoa nở đỏ rực đúng dịp cuối năm học và mùa thi.",
  "mauDacTrung":["#c0392b","#3f7d4e"],"nguon":"https://vi.wikipedia.org/wiki/Ph%C6%B0%E1%BB%A3ng_v%C4%A9"},
 {"id":"loc-vung","ten":"Lộc vừng","tenKhoaHoc":"Barringtonia acutangula","tenKhac":"Freshwater mangrove","nhom":"cay-canh",
  "ho":"Lộc vừng (Lecythidaceae)","phanLoai":{"bo":"Thạch nam (Ericales)","ho":"Lộc vừng (Lecythidaceae)","chi":"Barringtonia","loai":"B. acutangula"},
  "moTa":"Lộc vừng là cây cảnh sân vườn quý, hoa đỏ buông thành chuỗi dài rủ xuống mặt nước rất đẹp; nằm trong bộ cây cảnh 'sanh – sung – tùng – lộc'.",
  "hinhThai":"Cây gỗ tán đẹp, lá bóng, chuỗi hoa đỏ buông dài rủ xuống, quả vuông cạnh.",
  "loaiThan":"Cây gỗ cảnh","chieuCao":"5–15 m","chuKy":"Cây lâu năm","anhSang":"Ưa nắng, chịu bán râm",
  "nuoc":"Ưa ẩm, chịu được ngập","loaiDat":"Đất ẩm ven nước","vungTrong":"Trồng cảnh sân vườn, ven hồ khắp cả nước",
  "nhanGiong":"Gieo hạt, chiết","thoiGianThuHoach":"—","nangSuat":"—",
  "giaTri":"Cây cảnh phong thủy giá trị cao; hoa rủ đỏ rực làm cảnh quan ven nước.","boPhanDung":"Cây cảnh; lá non ăn được; hoa làm cảnh.",
  "baoTon":"Cây trồng phổ biến.",
  "xuatXu":"Loài bản địa nhiệt đới châu Á.","suThatThuVi":"Chữ 'lộc' trong tên khiến lộc vừng được ưa trồng làm cảnh phong thủy với mong cầu tài lộc.",
  "mauDacTrung":["#a83232","#3f6b3a"],"nguon":"https://vi.wikipedia.org/wiki/L%E1%BB%99c_v%E1%BB%ABng"},
 {"id":"me-tay","ten":"Me tây (Còng)","tenKhoaHoc":"Samanea saman","tenKhac":"Rain tree · cây còng","nhom":"cay-canh",
  "ho":"Đậu (Fabaceae)","phanLoai":{"bo":"Đậu (Fabales)","ho":"Đậu (Fabaceae)","chi":"Samanea","loai":"S. saman"},
  "moTa":"Me tây (miền Nam gọi cây còng) là cây bóng mát tán cực rộng hình dù, thường trồng ven đường, công viên cho bóng mát lớn.",
  "hinhThai":"Cây gỗ lớn tán dù rất rộng; lá kép lông chim hai lần; hoa chùm như búi tơ hồng; quả đậu dài màu nâu đen.",
  "loaiThan":"Cây gỗ lớn","chieuCao":"15–25 m","chuKy":"Cây lâu năm","anhSang":"Ưa nắng",
  "nuoc":"Trung bình, chịu hạn","loaiDat":"Đất sâu, thoát nước","vungTrong":"Trồng ven đường, công viên khắp miền Nam",
  "nhanGiong":"Gieo hạt","thoiGianThuHoach":"—","nangSuat":"—",
  "giaTri":"Bóng mát tán rộng bậc nhất; quả ngọt làm thức ăn gia súc.","boPhanDung":"Tán cho bóng mát; quả làm thức ăn gia súc; gỗ làm đồ mỹ nghệ.",
  "baoTon":"Cây trồng phổ biến.",
  "xuatXu":"Nguồn gốc Trung & Nam Mỹ, trồng rộng ở VN.","suThatThuVi":"Lá me tây cụp lại khi trời tối hoặc sắp mưa — nên có tên tiếng Anh là 'rain tree' (cây mưa).",
  "mauDacTrung":["#6b7a4a","#d8a0b0"],"nguon":"https://vi.wikipedia.org/wiki/Me_t%C3%A2y"},
 {"id":"muong-hoang-yen","ten":"Muồng hoàng yến","tenKhoaHoc":"Cassia fistula","tenKhac":"Golden shower · bò cạp nước","nhom":"cay-canh",
  "ho":"Đậu (Fabaceae)","phanLoai":{"bo":"Đậu (Fabales)","ho":"Đậu (Fabaceae)","chi":"Cassia","loai":"C. fistula"},
  "moTa":"Muồng hoàng yến nở hoa vàng rực buông thành chuỗi dài như mưa vàng, là cây cảnh quan đường phố được ưa chuộng.",
  "hinhThai":"Cây gỗ nhỏ, lá kép lông chim; hoa vàng tươi buông thành chùm dài rủ xuống; quả dạng đũa tròn dài màu nâu đen.",
  "loaiThan":"Cây gỗ nhỏ","chieuCao":"7–15 m","chuKy":"Cây lâu năm","anhSang":"Ưa nắng",
  "nuoc":"Chịu hạn","loaiDat":"Đất thoát nước","vungTrong":"Trồng cảnh quan đường phố khắp cả nước",
  "nhanGiong":"Gieo hạt","thoiGianThuHoach":"—","nangSuat":"—",
  "giaTri":"Cây cảnh quan hoa vàng đẹp; quả & vỏ dùng trong dược liệu dân gian.","boPhanDung":"Hoa làm cảnh; quả, vỏ làm thuốc nhuận tràng dân gian.",
  "baoTon":"Cây trồng phổ biến.",
  "xuatXu":"Nguồn gốc Nam Á, trồng cảnh ở VN.","suThatThuVi":"Mỗi mùa hoa, muồng hoàng yến phủ vàng cả cây như một 'cơn mưa vàng' — nên có tên golden shower.",
  "mauDacTrung":["#e3b32a","#5a6b3a"],"nguon":"https://vi.wikipedia.org/wiki/Mu%E1%BB%93ng_ho%C3%A0ng_y%E1%BA%BFn"},
 {"id":"osaka-do","ten":"Osaka đỏ","tenKhoaHoc":"Erythrina sp.","tenKhac":"Osaka hoa đỏ","nhom":"cay-canh",
  "ho":"Đậu (Fabaceae)","phanLoai":{"bo":"Đậu (Fabales)","ho":"Đậu (Fabaceae)","chi":"Erythrina","loai":"—"},
  "moTa":"Osaka đỏ là cây cảnh quan thân gỗ nở hoa đỏ rực buông chuỗi, được trồng nhiều ở đô thị và khu nghỉ dưỡng vì hoa đẹp, lâu tàn.",
  "hinhThai":"Cây gỗ nhỏ, lá kép; hoa đỏ tươi mọc thành chùm dài buông rủ; ra hoa nhiều đợt trong năm.",
  "loaiThan":"Cây gỗ nhỏ cảnh","chieuCao":"6–12 m","chuKy":"Cây lâu năm","anhSang":"Ưa nắng",
  "nuoc":"Trung bình","loaiDat":"Đất thoát nước tốt","vungTrong":"Trồng cảnh quan đô thị, khu nghỉ dưỡng",
  "nhanGiong":"Giâm cành, gieo hạt","thoiGianThuHoach":"—","nangSuat":"—",
  "giaTri":"Cây cảnh quan hoa đỏ rực, ra hoa nhiều đợt, tạo điểm nhấn cảnh quan.","boPhanDung":"Hoa & dáng cây làm cảnh quan.",
  "baoTon":"Cây trồng cảnh phổ biến.",
  "xuatXu":"Cây cảnh nhập trồng phổ biến ở VN gần đây.","suThatThuVi":"Osaka đỏ được dân làm vườn ưa chuộng vì ra hoa nhiều đợt quanh năm, hoa đỏ giữ lâu trên cây.",
  "mauDacTrung":["#c0392b","#4f7a34"],"nguon":"https://vi.wikipedia.org/wiki/Chi_V%C3%B4ng"},
]
# ===== CHĂN NUÔI =====
THU_DAC_SAN = [
 {"id":"dui","ten":"Dúi","tenKhoaHoc":"Rhizomys sp.","tenKhac":"Bamboo rat","nhom":"thu-dac-san",
  "moTa":"Dúi là loài gặm nhấm sống trong hang, nuôi lấy thịt đặc sản; ăn tre nứa, dễ nuôi, ít bệnh, đang là mô hình hot ở nông thôn.",
  "giong":"Dúi mốc, dúi má đào","trongLuong":"1–3 kg",
  "thucAn":"Tre, nứa, mía, ngô, cỏ voi; rất ít uống nước","chuongTrai":"Ô xây gạch men kín, tối, mát; mỗi con/ô",
  "sinhSan":"Đẻ 2–4 con/lứa, 2–3 lứa/năm","thoiGianNuoi":"Nuôi thịt 6–8 tháng",
  "sanPham":"Thịt dúi (đặc sản), con giống","benhThuongGap":"Tiêu chảy, viêm phổi do ẩm lạnh, đau mắt",
  "vungNuoi":"Trung du, miền núi phía Bắc, Tây Nguyên","giaTri":"Thịt đặc sản giá cao; nuôi vốn ít, tận dụng tre nứa sẵn có.",
  "suThatThuVi":"Dúi gần như không cần uống nước — lấy đủ độ ẩm từ thân tre, mía tươi nó gặm.",
  "mauDacTrung":["#8a8079","#d8d2c4"],"nguon":"https://vi.wikipedia.org/wiki/Chi_D%C3%BAi"},
 {"id":"chon-huong","ten":"Chồn hương","tenKhoaHoc":"Paradoxurus hermaphroditus","tenKhac":"Civet · cầy hương","nhom":"thu-dac-san",
  "moTa":"Chồn hương (cầy hương) nuôi lấy thịt đặc sản và làm cà phê chồn; thân thon như mèo, mặt có vằn đen đặc trưng.",
  "giong":"Chồn hương thuần dưỡng","trongLuong":"2–5 kg",
  "thucAn":"Chuối, đu đủ, cá, trứng, cà phê chín; ăn tạp thiên ngọt","chuongTrai":"Chuồng lưới cao ráo, yên tĩnh, có chỗ trú tối",
  "sinhSan":"Đẻ 2–4 con/lứa","thoiGianNuoi":"Nuôi thịt 8–12 tháng",
  "sanPham":"Thịt chồn (đặc sản), cà phê chồn","benhThuongGap":"Tiêu chảy, ký sinh trùng, stress",
  "vungNuoi":"Tây Nguyên, Đông Nam Bộ","giaTri":"Thịt & cà phê chồn giá rất cao; cần nuôi có giấy phép động vật hoang dã.",
  "suThatThuVi":"Cà phê chồn nổi tiếng ra đời nhờ chồn hương ăn quả cà phê chín rồi thải hạt — hạt được lên men tự nhiên trong ruột chồn.",
  "mauDacTrung":["#6b5a3a","#d8c4a0"],"nguon":"https://vi.wikipedia.org/wiki/C%E1%BA%A7y_v%C3%B2i_%C4%91%E1%Bb%91m".replace('%c4%b','%C4%91').replace('​','')},
 {"id":"heo-rung","ten":"Heo rừng","tenKhoaHoc":"Sus scrofa","tenKhac":"Wild boar · lợn rừng","nhom":"thu-dac-san",
  "moTa":"Heo rừng (thuần hóa/lai) nuôi lấy thịt nạc đặc sản, da dày lông bờm cứng; nuôi bán hoang dã, thịt săn chắc ít mỡ.",
  "giong":"Heo rừng thuần, heo rừng lai","trongLuong":"30–70 kg",
  "thucAn":"Rau, củ, chuối, cám, phụ phẩm; ăn tạp","chuongTrai":"Chuồng có sân vận động rộng rào chắc, nền đất để dũi",
  "sinhSan":"Đẻ 5–10 con/lứa, 2 lứa/năm","thoiGianNuoi":"Nuôi thịt 8–12 tháng",
  "sanPham":"Thịt heo rừng (đặc sản), con giống","benhThuongGap":"Dịch tả lợn, ký sinh trùng, tiêu chảy",
  "vungNuoi":"Trung du, miền núi, trang trại bán hoang dã","giaTri":"Thịt nạc săn chắc giá cao, được ưa ở nhà hàng đặc sản.",
  "suThatThuVi":"Heo rừng con có sọc nâu vàng dọc thân (kiểu 'quả dưa hấu') để ngụy trang, lớn lên sọc mới mất.",
  "mauDacTrung":["#3a2e22","#8a6a3a"],"nguon":"https://vi.wikipedia.org/wiki/L%E1%BB%A3n_r%E1%BB%ABng"},
 {"id":"nai","ten":"Nai","tenKhoaHoc":"Rusa unicolor","tenKhac":"Sambar deer","nhom":"thu-dac-san",
  "moTa":"Nai là loài hươu lớn, nuôi lấy nhung và thịt; vóc to, lông nâu sẫm, sừng to nhiều nhánh ở con đực.",
  "giong":"Nai thuần dưỡng","trongLuong":"100–250 kg",
  "thucAn":"Cỏ, lá cây, củ quả, thức ăn tinh","chuongTrai":"Khu nuôi rào cao chắc chắn, có sân rộng và bóng mát",
  "sinhSan":"Mang thai ~8 tháng, 1 con/lứa","thoiGianNuoi":"Khai thác nhung & sinh sản nhiều năm",
  "sanPham":"Nhung nai (dược liệu), thịt, con giống","benhThuongGap":"Ký sinh trùng, chướng bụng, stress",
  "vungNuoi":"Tây Nguyên, miền núi (trại nuôi)","giaTri":"Nhung nai là dược liệu quý; thịt nai đặc sản giá cao.",
  "suThatThuVi":"Nai là loài hươu lớn nhất Đông Nam Á; con đực rống vang để gọi bầy và thu hút con cái mùa sinh sản.",
  "mauDacTrung":["#5a3a2a","#cabfa0"],"nguon":"https://vi.wikipedia.org/wiki/Nai"},
 {"id":"cay-voi-huong","ten":"Cầy vòi hương","tenKhoaHoc":"Paguma larvata","tenKhac":"Masked palm civet","nhom":"thu-dac-san",
  "moTa":"Cầy vòi hương có vệt trắng chạy dọc giữa mặt rất đặc trưng; nuôi lấy thịt đặc sản, ăn tạp thiên quả.",
  "giong":"Cầy vòi hương thuần dưỡng","trongLuong":"3–6 kg",
  "thucAn":"Chuối, đu đủ, quả chín, cá, trứng","chuongTrai":"Chuồng lưới cao ráo, yên tĩnh, có hộc trú",
  "sinhSan":"Đẻ 1–4 con/lứa","thoiGianNuoi":"Nuôi thịt 8–12 tháng",
  "sanPham":"Thịt (đặc sản), con giống","benhThuongGap":"Tiêu chảy, ký sinh trùng",
  "vungNuoi":"Trung du, miền núi, Tây Nguyên","giaTri":"Thịt đặc sản giá cao; nuôi cần giấy phép động vật hoang dã.",
  "suThatThuVi":"Cầy vòi hương dễ nhận nhờ vệt lông trắng chạy thẳng từ mũi lên đỉnh đầu như đeo mặt nạ.",
  "mauDacTrung":["#6b5a4a","#e8e2d2"],"nguon":"https://vi.wikipedia.org/wiki/C%E1%BA%A7y_v%C3%B2i_h%C6%B0%C6%A1ng"},
]
BO_SAT_NUOI = [
 {"id":"ca-sau","ten":"Cá sấu","tenKhoaHoc":"Crocodylus siamensis","tenKhac":"Siamese crocodile","nhom":"bo-sat-nuoi",
  "moTa":"Cá sấu nước ngọt được nuôi lấy da (làm hàng da cao cấp) và thịt; thân phủ vảy sừng, nuôi trong ao quây an toàn.",
  "giong":"Cá sấu nước ngọt (Xiêm)","trongLuong":"40–80 kg (xuất chuồng), tối đa hàng trăm kg",
  "thucAn":"Cá tạp, đầu gà, phụ phẩm thịt","chuongTrai":"Ao quây tường cao chắc chắn, có bãi phơi nắng và hồ nước",
  "sinhSan":"Đẻ 20–40 trứng/lứa, ấp trong tổ ~80 ngày","thoiGianNuoi":"Nuôi lấy da 2–3 năm",
  "sanPham":"Da cá sấu (hàng da cao cấp), thịt, con giống","benhThuongGap":"Nấm da, nhiễm khuẩn vết thương, stress mật độ",
  "vungNuoi":"Đồng bằng Sông Cửu Long, Đông Nam Bộ","giaTri":"Da cá sấu giá trị xuất khẩu cao; nuôi cần giấy phép & truy xuất CITES.",
  "suThatThuVi":"Giới tính cá sấu con phụ thuộc nhiệt độ ấp trứng — không do gen quyết định như đa số loài.",
  "mauDacTrung":["#4a5a3a","#cabf9a"],"nguon":"https://vi.wikipedia.org/wiki/C%C3%A1_s%E1%BA%A5u_Xi%C3%AAm"},
 {"id":"ran-ho-trau","ten":"Rắn hổ trâu","tenKhoaHoc":"Ptyas mucosa","tenKhac":"Oriental ratsnake · rắn ráo trâu","nhom":"bo-sat-nuoi",
  "moTa":"Rắn hổ trâu (ráo trâu) là rắn lành không độc, lớn nhanh, nuôi lấy thịt; săn chuột nên còn có ích cho đồng ruộng.",
  "giong":"Rắn hổ trâu (ráo trâu)","trongLuong":"1–2,5 kg",
  "thucAn":"Chuột, cóc nhái, gà con","chuongTrai":"Chuồng/hộc xây kín có khe thoáng, khô ráo, ấm",
  "sinhSan":"Đẻ 6–15 trứng/lứa, ấp ~60 ngày","thoiGianNuoi":"Nuôi thịt 10–14 tháng",
  "sanPham":"Thịt rắn, con giống, da","benhThuongGap":"Sưng phổi do lạnh ẩm, nấm da, đường ruột",
  "vungNuoi":"Đồng bằng Sông Cửu Long, đồng bằng Bắc Bộ","giaTri":"Thịt rắn giá cao; nuôi cần giấy phép; rắn không độc nên an toàn hơn.",
  "suThatThuVi":"Rắn hổ trâu không có nọc độc — tên 'hổ trâu' chỉ vì nó to khỏe và phồng cổ dọa khi gặp nguy.",
  "mauDacTrung":["#6b6b3a","#cabfa0"],"nguon":"https://vi.wikipedia.org/wiki/R%E1%BA%AFn_r%C3%A1o_tr%C3%A2u"},
 {"id":"ky-da","ten":"Kỳ đà","tenKhoaHoc":"Varanus salvator","tenKhac":"Water monitor","nhom":"bo-sat-nuoi",
  "moTa":"Kỳ đà hoa là loài thằn lằn lớn, nuôi lấy thịt & da; thân dài phủ vảy, lưỡi chẻ, bơi giỏi.",
  "giong":"Kỳ đà hoa, kỳ đà vân","trongLuong":"3–10 kg",
  "thucAn":"Cá, ếch nhái, đầu gà, phụ phẩm thịt","chuongTrai":"Chuồng xây có hồ nước và chỗ phơi nắng, rào chắc",
  "sinhSan":"Đẻ 10–30 trứng/lứa","thoiGianNuoi":"Nuôi thịt 1,5–2 năm",
  "sanPham":"Thịt kỳ đà (đặc sản), da","benhThuongGap":"Nấm da, nhiễm khuẩn, ký sinh trùng",
  "vungNuoi":"Đồng bằng Sông Cửu Long, Đông Nam Bộ","giaTri":"Thịt & da giá cao; nuôi cần giấy phép động vật hoang dã.",
  "suThatThuVi":"Kỳ đà bơi rất giỏi và có thể lặn lâu dưới nước — dùng cái đuôi dẹt khỏe như mái chèo.",
  "mauDacTrung":["#5a5a3a","#d8cf9a"],"nguon":"https://vi.wikipedia.org/wiki/K%E1%BB%B3_%C4%91%C3%A0_hoa"},
 {"id":"tran","ten":"Trăn","tenKhoaHoc":"Python bivittatus","tenKhac":"Burmese python","nhom":"bo-sat-nuoi",
  "moTa":"Trăn đất là rắn lớn không độc, nuôi lấy da (hàng da cao cấp), thịt và mỡ; thân to khỏe, hoa văn đốm nâu.",
  "giong":"Trăn đất, trăn gấm","trongLuong":"10–40 kg",
  "thucAn":"Gà, vịt, chuột, thỏ (con mồi nguyên con)","chuongTrai":"Chuồng xây kín chắc chắn, ấm, có khay nước",
  "sinhSan":"Đẻ 20–60 trứng/lứa, con cái cuộn ấp trứng","thoiGianNuoi":"Nuôi lấy da 1,5–2 năm",
  "sanPham":"Da trăn (hàng da), thịt, mỡ","benhThuongGap":"Sưng phổi, nấm da, ký sinh trùng",
  "vungNuoi":"Đồng bằng Sông Cửu Long, Đông Nam Bộ","giaTri":"Da trăn xuất khẩu giá trị cao; nuôi cần giấy phép & CITES.",
  "suThatThuVi":"Trăn không có nọc độc — nó siết chặt con mồi để khiến con mồi ngạt, rồi nuốt chửng nguyên con.",
  "mauDacTrung":["#8a6a3a","#cabf8a"],"nguon":"https://vi.wikipedia.org/wiki/Tr%C4%83n_%C4%91%E1%BA%A5t"},
 {"id":"tac-ke","ten":"Tắc kè","tenKhoaHoc":"Gekko gecko","tenKhac":"Tokay gecko","nhom":"bo-sat-nuoi",
  "moTa":"Tắc kè là loài thạch sùng lớn, nuôi làm dược liệu (ngâm rượu) và xuất khẩu; thân xám điểm đốm cam, tiếng kêu 'tắc-kè' đặc trưng.",
  "giong":"Tắc kè hoa","trongLuong":"100–400 g",
  "thucAn":"Côn trùng: dế, gián, sâu, châu chấu","chuongTrai":"Chuồng lưới cao có thân cây/ống tre để bám trú, ấm",
  "sinhSan":"Đẻ 1–2 trứng/lứa, dán vào vách","thoiGianNuoi":"Nuôi 10–12 tháng",
  "sanPham":"Tắc kè khô (dược liệu), con giống","benhThuongGap":"Còi do thiếu canxi, ký sinh, đường ruột",
  "vungNuoi":"Miền núi, trung du, Tây Nguyên","giaTri":"Dược liệu ngâm rượu bổ; có thị trường xuất khẩu.",
  "suThatThuVi":"Tắc kè bám tường nhờ hàng triệu sợi lông siêu nhỏ dưới ngón chân — bám được cả trên mặt kính trơn.",
  "mauDacTrung":["#5a6b7a","#c08a3a"],"nguon":"https://vi.wikipedia.org/wiki/T%E1%BA%AFc_k%C3%A8"},
]
# ===== THỦY SẢN =====
CA_BIEN = [
 {"id":"ca-mu","ten":"Cá mú","tenKhoaHoc":"Epinephelus sp.","tenKhac":"Grouper · cá song","nhom":"ca-bien",
  "moTa":"Cá mú (cá song) là cá biển thịt chắc ngọt giá cao, nuôi lồng bè ven biển và đảo; thân mập, miệng rộng, da đốm.",
  "moiTruongNuoc":"Nước mặn ven biển","nhietDoPH":"26–30°C, độ mặn 28–33‰",
  "thucAn":"Cá tạp, thức ăn viên đạm cao","hinhThucNuoi":"Lồng bè trên biển, ao đìa nước mặn; mật độ vừa",
  "thuHoach":"8–12 tháng, đạt 0,6–1,2 kg/con","sanLuong":"Giá trị cao dù sản lượng vừa",
  "sanPham":"Cá mú thương phẩm (nhà hàng, xuất khẩu)","benhThuongGap":"Ký sinh trùng, lở loét, hoại tử thần kinh (VNN)",
  "vungNuoi":"Khánh Hòa, Kiên Giang, Quảng Ninh, vùng vịnh & đảo","giaTri":"Hải sản cao cấp giá cao; cá mú nghệ có thể nặng vài chục kg.",
  "suThatThuVi":"Nhiều loài cá mú sinh ra là cái rồi lớn lên chuyển thành đực — hiện tượng đổi giới tính theo tuổi.",
  "mauDacTrung":["#6b5a3a","#cabf8a"],"nguon":"https://vi.wikipedia.org/wiki/C%C3%A1_m%C3%BA"},
 {"id":"ca-chem","ten":"Cá chẽm","tenKhoaHoc":"Lates calcarifer","tenKhac":"Barramundi · cá vược","nhom":"ca-bien",
  "moTa":"Cá chẽm (cá vược) sống được cả nước mặn, lợ và ngọt; lớn nhanh, thịt trắng ngon, nuôi lồng và ao rộng rãi.",
  "moiTruongNuoc":"Rộng muối: mặn, lợ, ngọt","nhietDoPH":"26–32°C, độ mặn 0–30‰",
  "thucAn":"Cá tạp, thức ăn viên đạm cao; ăn thịt","hinhThucNuoi":"Lồng bè, ao nước lợ; mật độ vừa",
  "thuHoach":"8–12 tháng, đạt 0,8–1,5 kg/con","sanLuong":"Cao, lớn nhanh",
  "sanPham":"Phi lê & cá nguyên con (nội địa, xuất khẩu)","benhThuongGap":"Ký sinh trùng, lở loét, VNN",
  "vungNuoi":"Ven biển miền Trung, Nam Bộ; cả vùng nước lợ","giaTri":"Cá thịt trắng giá tốt, thị trường rộng nhờ chịu được nhiều độ mặn.",
  "suThatThuVi":"Cá chẽm chịu được từ nước biển tới nước ngọt — nên nuôi được ở rất nhiều vùng khác nhau.",
  "mauDacTrung":["#8a9aa0","#e3e7ea"],"nguon":"https://vi.wikipedia.org/wiki/C%C3%A1_v%C6%B0%E1%BB%A3c_Nh%E1%BA%ADt"},
 {"id":"ca-bop","ten":"Cá bớp","tenKhoaHoc":"Rachycentron canadum","tenKhac":"Cobia · cá giò","nhom":"ca-bien",
  "moTa":"Cá bớp (cá giò) là cá biển lớn nhanh bậc nhất, thân dài thuôn, thịt béo chắc; nuôi lồng bè trên biển cho sản lượng lớn.",
  "moiTruongNuoc":"Nước mặn ven biển","nhietDoPH":"26–30°C, độ mặn 28–33‰",
  "thucAn":"Cá tạp, thức ăn viên đạm cao","hinhThucNuoi":"Lồng bè trên biển; mật độ vừa",
  "thuHoach":"8–12 tháng, đạt 4–8 kg/con","sanLuong":"Cao, cá lớn nhanh",
  "sanPham":"Cá bớp thương phẩm (lẩu, nướng, xuất khẩu)","benhThuongGap":"Ký sinh trùng (sán lá mang), lở loét",
  "vungNuoi":"Kiên Giang, Khánh Hòa, Quảng Ngãi (lồng bè biển)","giaTri":"Lớn rất nhanh nên hiệu quả nuôi cao; thịt béo được ưa chuộng.",
  "suThatThuVi":"Cá bớp có thể tăng tới 5–6 kg chỉ trong một năm nuôi — thuộc nhóm cá biển lớn nhanh nhất.",
  "mauDacTrung":["#3a3a2e","#b5ac8a"],"nguon":"https://vi.wikipedia.org/wiki/C%C3%A1_gi%C3%B2"},
 {"id":"ca-hong-my","ten":"Cá hồng mỹ","tenKhoaHoc":"Sciaenops ocellatus","tenKhac":"Red drum","nhom":"ca-bien",
  "moTa":"Cá hồng mỹ thân đỏ đồng, có đốm đen gần đuôi; nhập nuôi lồng bè và ao nước lợ, lớn nhanh, dễ nuôi.",
  "moiTruongNuoc":"Nước mặn – lợ","nhietDoPH":"24–30°C, độ mặn 10–30‰",
  "thucAn":"Thức ăn viên, cá tạp","hinhThucNuoi":"Lồng bè, ao nước lợ; mật độ vừa",
  "thuHoach":"8–10 tháng, đạt 0,8–1,5 kg/con","sanLuong":"Cao, dễ nuôi",
  "sanPham":"Cá thương phẩm (nội địa, chế biến)","benhThuongGap":"Ký sinh trùng, lở loét, sốc môi trường",
  "vungNuoi":"Ven biển Bắc Bộ, Trung Bộ","giaTri":"Cá thịt giá hợp lý, lớn nhanh, chịu rộng muối nên dễ nuôi.",
  "suThatThuVi":"Đốm đen tròn gần đuôi cá hồng mỹ được cho là 'mắt giả' đánh lừa kẻ săn mồi nhắm nhầm hướng.",
  "mauDacTrung":["#a8503a","#e3c4b0"],"nguon":"https://vi.wikipedia.org/wiki/Sciaenops_ocellatus"},
 {"id":"ca-mang","ten":"Cá măng","tenKhoaHoc":"Chanos chanos","tenKhac":"Milkfish · cá măng sữa","nhom":"ca-bien",
  "moTa":"Cá măng (măng sữa) thân bạc thuôn, ăn tảo và mùn nên nuôi rẻ; phổ biến ở ao nước lợ ven biển miền Trung – Nam.",
  "moiTruongNuoc":"Nước lợ – mặn","nhietDoPH":"26–32°C, độ mặn 10–32‰",
  "thucAn":"Tảo, mùn bã, thức ăn viên; ăn thực vật phù du","hinhThucNuoi":"Ao nước lợ, đăng quầng; mật độ vừa",
  "thuHoach":"5–8 tháng, đạt 0,3–0,6 kg/con","sanLuong":"Khá, chi phí thức ăn thấp",
  "sanPham":"Cá măng tươi (nội địa)","benhThuongGap":"Ký sinh trùng, sốc độ mặn, thiếu oxy",
  "vungNuoi":"Ven biển Nam Trung Bộ, Nam Bộ","giaTri":"Nuôi rẻ nhờ ăn tảo; là cá phổ thông vùng ven biển.",
  "suThatThuVi":"Cá măng con được vớt tự nhiên ngoài biển hoặc cho đẻ nhân tạo, rồi đưa vào ao lợ nuôi lớn.",
  "mauDacTrung":["#9aa6ac","#e3e7ea"],"nguon":"https://vi.wikipedia.org/wiki/C%C3%A1_m%C4%83ng_s%E1%BB%AFa"},
]
NHUYEN_THE = [
 {"id":"so-huyet","ten":"Sò huyết","tenKhoaHoc":"Anadara granosa","tenKhac":"Blood cockle","nhom":"nhuyen-the",
  "moTa":"Sò huyết là nhuyễn thể hai mảnh vỏ có máu đỏ (huyết tố), vỏ dày gân nổi; nuôi bãi triều bùn, thịt bổ máu được ưa chuộng.",
  "moiTruongNuoc":"Nước mặn – lợ, bãi bùn triều","nhietDoPH":"26–30°C, độ mặn 15–30‰",
  "thucAn":"Lọc tảo và mùn hữu cơ (không cho ăn)","hinhThucNuoi":"Thả giống trên bãi bùn triều, quây giữ; mật độ cao",
  "thuHoach":"8–12 tháng, đạt 60–100 con/kg","sanLuong":"Khá cao trên bãi nuôi",
  "sanPham":"Sò huyết thương phẩm (đặc sản)","benhThuongGap":"Chết do nắng nóng, ô nhiễm bãi, độ mặn đột biến",
  "vungNuoi":"Kiên Giang, Cà Mau, Bến Tre, Ninh Thuận","giaTri":"Đặc sản giàu sắt; sò huyết Ô Loan, Cà Mau nổi tiếng.",
  "suThatThuVi":"Sò huyết có máu đỏ chứa hemoglobin như người — hiếm ở nhuyễn thể — nên thịt có màu đỏ và vị 'bổ máu'.",
  "mauDacTrung":["#8a2e2e","#cabf9a"],"nguon":"https://vi.wikipedia.org/wiki/S%C3%B2_huy%E1%BA%BFt"},
 {"id":"oc-huong","ten":"Ốc hương","tenKhoaHoc":"Babylonia areolata","tenKhac":"Spotted babylon","nhom":"nhuyen-the",
  "moTa":"Ốc hương là ốc biển thịt thơm giòn giá cao, vỏ trơn đốm nâu; nuôi ao đáy cát và lồng ven biển, là đặc sản xuất khẩu.",
  "moiTruongNuoc":"Nước mặn ven biển, đáy cát","nhietDoPH":"26–30°C, độ mặn 28–33‰",
  "thucAn":"Cá tạp, thịt nhuyễn thể băm","hinhThucNuoi":"Ao đáy cát, lồng/đăng ven biển; mật độ cao",
  "thuHoach":"5–8 tháng, đạt 90–150 con/kg","sanLuong":"Cao, giá bán cao",
  "sanPham":"Ốc hương thương phẩm (nội địa, xuất khẩu)","benhThuongGap":"Sưng vòi, bệnh do vi khuẩn, chết do đáy bẩn",
  "vungNuoi":"Khánh Hòa, Phú Yên, Ninh Thuận, Kiên Giang","giaTri":"Hải sản cao cấp giá cao, thị trường xuất khẩu tốt.",
  "suThatThuVi":"Ốc hương vùi mình trong cát ban ngày, đêm bò ra ăn — nên ao nuôi phải có lớp cát đáy sạch.",
  "mauDacTrung":["#b5a06a","#e8dcc0"],"nguon":"https://vi.wikipedia.org/wiki/%E1%BB%90c_h%C6%B0%C6%A1ng"},
 {"id":"vem-xanh","ten":"Vẹm xanh","tenKhoaHoc":"Perna viridis","tenKhac":"Asian green mussel","nhom":"nhuyen-the",
  "moTa":"Vẹm xanh là nhuyễn thể vỏ xanh, bám giàn dây bằng tơ chân; lọc nước để ăn nên nuôi không tốn thức ăn, giàu đạm.",
  "moiTruongNuoc":"Nước mặn – lợ ven biển","nhietDoPH":"26–30°C, độ mặn 18–30‰",
  "thucAn":"Lọc tảo phù du (không cho ăn)","hinhThucNuoi":"Nuôi treo dây, giàn bè; bám bằng tơ chân",
  "thuHoach":"6–10 tháng","sanLuong":"Cao theo giàn treo, vốn thấp",
  "sanPham":"Vẹm xanh thương phẩm (hấp, nướng)","benhThuongGap":"Chết do ô nhiễm, độ mặn đột biến",
  "vungNuoi":"Quảng Ninh, Khánh Hòa, ven biển Nam Bộ","giaTri":"Hải sản giàu đạm giá rẻ; vốn thấp vì không tốn thức ăn.",
  "suThatThuVi":"Vẹm bám chắc vào giá thể bằng những sợi 'tơ chân' (byssus) dai như keo do chính nó tiết ra.",
  "mauDacTrung":["#3a6b4a","#cabf9a"],"nguon":"https://vi.wikipedia.org/wiki/V%E1%BA%B9m_xanh"},
 {"id":"rong-nho","ten":"Rong nho","tenKhoaHoc":"Caulerpa lentillifera","tenKhac":"Sea grapes · trứng cá xanh","nhom":"nhuyen-the",
  "moTa":"Rong nho là loài rong biển ăn được, các nhánh kết hạt tròn xanh mọng như chùm nho tí hon, giòn mặn, giàu khoáng.",
  "moiTruongNuoc":"Nước mặn trong, ao đáy cát ven biển","nhietDoPH":"25–30°C, độ mặn 30–35‰",
  "thucAn":"Tự quang hợp (không cho ăn)","hinhThucNuoi":"Nuôi đáy ao hoặc treo vỉ trong nước mặn sạch",
  "thuHoach":"30–45 ngày/đợt, thu nhiều đợt","sanLuong":"Cao, thu liên tục",
  "sanPham":"Rong nho tươi & tách nước (ăn sống, salad, xuất khẩu)","benhThuongGap":"Tàn do nước đục, nhiệt cao, ô nhiễm",
  "vungNuoi":"Khánh Hòa (Cam Ranh), Ninh Thuận, Phú Yên","giaTri":"Thực phẩm sạch giàu khoáng; đặc sản xuất khẩu (Nhật ưa chuộng).",
  "suThatThuVi":"Rong nho được gọi là 'trứng cá xanh' vì các hạt tròn vỡ giòn trong miệng, vị mặn nhẹ của biển.",
  "mauDacTrung":["#4f8f3a","#cfe0b0"],"nguon":"https://vi.wikipedia.org/wiki/Rong_nho"},
 {"id":"rong-sun","ten":"Rong sụn","tenKhoaHoc":"Kappaphycus alvarezii","tenKhac":"Elkhorn sea moss","nhom":"nhuyen-the",
  "moTa":"Rong sụn là rong biển thân giòn phân nhánh, nguyên liệu chiết carrageenan (chất tạo đông) và làm thạch, chè; nuôi dây trên biển.",
  "moiTruongNuoc":"Nước mặn trong ven biển","nhietDoPH":"26–30°C, độ mặn 28–34‰",
  "thucAn":"Tự quang hợp (không cho ăn)","hinhThucNuoi":"Buộc bụi rong vào dây căng giữa cọc/phao trên biển",
  "thuHoach":"45–60 ngày/đợt","sanLuong":"Cao, thu nhiều đợt",
  "sanPham":"Rong sụn khô (làm thạch, chè, chiết carrageenan)","benhThuongGap":"Bệnh 'ice-ice' trắng nhũn, tàn do nước nóng đục",
  "vungNuoi":"Ninh Thuận, Khánh Hòa, Phú Yên","giaTri":"Nguyên liệu carrageenan công nghiệp thực phẩm; món rong sụn giải nhiệt.",
  "suThatThuVi":"Carrageenan chiết từ rong sụn có mặt trong rất nhiều thực phẩm quen thuộc: kem, sữa, thạch, xúc xích.",
  "mauDacTrung":["#9aa84a","#dfe6c0"],"nguon":"https://vi.wikipedia.org/wiki/Rong_s%E1%BB%A5n"},
]

def main():
    data = json.load(open(PATH, encoding='utf-8'))
    existing = {c['id'] for c in data['cay']}
    added = 0
    groups = [('lam-nghiep', NGAP_MAN), ('lam-nghiep', CAY_CANH),
              ('chan-nuoi', THU_DAC_SAN), ('chan-nuoi', BO_SAT_NUOI),
              ('thuy-san', CA_BIEN), ('thuy-san', NHUYEN_THE)]
    for lv, recs in groups:
        for rec in recs:
            if rec['id'] in existing:
                print('SKIP (exists):', rec['id']); continue
            rec['linhVuc'] = lv
            rec['anh'] = f"img/{rec['id']}.jpg"
            data['cay'].append(rec); added += 1
    data['_meta']['capNhat'] = '2026-05-27'
    json.dump(data, open(PATH, 'w', encoding='utf-8'), ensure_ascii=False, indent=2)
    print(f'Added {added} mục. Tổng: {len(data["cay"])} mục.')

if __name__ == '__main__':
    main()
