#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Bổ sung 38 cây mới (28 nông nghiệp + 10 lâm nghiệp) vào data/cay.json.
Bỏ qua cây đã tồn tại (theo id). Chạy: python3 scripts/add-plants.py"""
import json, os

base = os.path.join(os.path.dirname(__file__), '..')
path = os.path.join(base, 'data', 'tu-dien-nong-lam-ngu.json')


def ls(*pairs):
    return [{"giaiDoan": g, "thoiGian": t} for g, t in pairs]


def P(id, ten, sci, khac, ho, nhom, bo, chi, loai, xuatXu, moTa, loaiThan,
      chieuCao, chuKy, anhSang, nuoc, loaiDat, vungTrong, muaVu, dieuKien,
      nhanGiong, thuHoach, nangSuat, lich, sauBenh, giaTri, dinhDuong,
      huongVi, yhct, thiTruong, thuVi, mau, nguon):
    return {
        "id": id, "ten": ten, "tenKhoaHoc": sci, "tenKhac": khac, "ho": ho,
        "nhom": nhom, "anh": f"img/{id}.jpg", "anhChiTiet": f"img/detail/{id}.jpg",
        "xuatXu": xuatXu,
        "phanLoai": {"bo": bo, "ho": ho, "chi": chi, "loai": loai},
        "moTa": moTa, "loaiThan": loaiThan, "chieuCao": chieuCao, "chuKy": chuKy,
        "anhSang": anhSang, "nuoc": nuoc, "loaiDat": loaiDat, "vungTrong": vungTrong,
        "muaVu": muaVu, "dieuKien": dieuKien, "nhanGiong": nhanGiong,
        "thoiGianThuHoach": thuHoach, "nangSuat": nangSuat, "lichSinhTruong": lich,
        "sauBenh": sauBenh, "giaTri": giaTri, "dinhDuong": dinhDuong,
        "huongVi": huongVi, "yHocCoTruyen": yhct, "thiTruong": thiTruong,
        "suThatThuVi": thuVi, "mauDacTrung": mau, "nguon": nguon,
    }


NEW = [
    # ============ ĂN QUẢ (11) ============
    P("du-du", "Đu đủ", "Carica papaya", "Papaya · cây đu đủ", "Đu đủ (Caricaceae)",
      "an-qua", "Cải (Brassicales)", "Carica", "C. papaya",
      "Có nguồn gốc Trung Mỹ; du nhập và trồng phổ biến khắp Việt Nam, cho quả quanh năm.",
      "Đu đủ là cây ăn quả thân thảo mọc nhanh, cho quả quanh năm, trồng khắp vườn nhà và trang trại ở Việt Nam.",
      "Cây thân thảo hóa gỗ, thân rỗng không phân nhánh", "2–5 m", "Cây lâu năm ngắn (3–4 năm)",
      "Ưa nắng hoàn toàn", "Trung bình — cần ẩm, sợ úng", "Đất tơi xốp, thoát nước tốt, giàu mùn",
      "Khắp cả nước, nhiều ở Nam Bộ và miền Trung", "Trồng quanh năm, ra quả sau 7–11 tháng",
      "Cần thoát nước tốt, nhiệt độ 25–30°C; rất sợ ngập úng gây thối rễ",
      "Gieo hạt", "7–11 tháng sau trồng, thu quanh năm", "30–60 kg quả/cây/năm",
      ls(("Gieo hạt / cây con", "Tháng 0–2"), ("Phát triển thân lá", "Tháng 2–6"),
         ("Ra hoa", "Tháng 6–8"), ("Đậu quả & lớn", "Tháng 8–11"), ("Thu hoạch liên tục", "Tháng 11+")),
      "Nhện đỏ, rệp, bệnh khảm virus, thối rễ",
      "Trái cây giàu vitamin, ăn tươi & chế biến; đu đủ xanh làm gỏi, nấu canh",
      "Giàu vitamin C, A, folate, enzyme papain hỗ trợ tiêu hóa",
      "Ngọt mát, thịt mềm khi chín", "Đu đủ xanh hầm chân giò lợi sữa; nhựa và lá hỗ trợ tiêu hóa",
      "Tiêu thụ nội địa lớn, xuất khẩu tươi & sấy",
      "Đu đủ chứa enzyme papain — được dùng làm mềm thịt và trong công nghiệp thực phẩm",
      ["#F2A23C", "#E8643B"], "https://vi.wikipedia.org/wiki/%C4%90u_%C4%91%E1%BB%A7"),

    P("mang-cut", "Măng cụt", "Garcinia mangostana", "Mangosteen · nữ hoàng trái cây", "Bứa (Clusiaceae)",
      "an-qua", "Sơ ri (Malpighiales)", "Garcinia", "G. mangostana",
      "Có nguồn gốc Đông Nam Á (quần đảo Sunda); trồng nhiều ở Nam Bộ, nổi tiếng Lái Thiêu, Chợ Lách.",
      "Măng cụt là cây ăn quả nhiệt đới quý, vỏ tím dày, ruột trắng ngọt thanh — được mệnh danh 'nữ hoàng trái cây'.",
      "Cây gỗ thường xanh tán hình tháp", "7–25 m", "Cây lâu năm (chục năm)",
      "Ưa bóng khi nhỏ, ưa nắng khi lớn", "Nhiều — cần ẩm đều quanh năm", "Đất phù sa, thịt sâu, giàu mùn",
      "Đông Nam Bộ và ĐBSCL (Bình Dương, Bến Tre, Vĩnh Long)", "Ra hoa tháng 12–2, quả chín tháng 5–8",
      "Khí hậu nóng ẩm, mưa nhiều; sinh trưởng chậm, cần che bóng giai đoạn cây con",
      "Gieo hạt (hạt vô tính) hoặc ghép", "Bói quả sau 7–10 năm", "50–200 kg quả/cây/năm khi trưởng thành",
      ls(("Ươm cây con (che bóng)", "Năm 1–2"), ("Trồng & kiến thiết", "Năm 2–6"),
         ("Bói quả", "Năm 7–10"), ("Cho quả ổn định", "Năm 10+")),
      "Sâu vẽ bùa, bọ trĩ, bệnh chảy nhựa thân, sượng múi",
      "Trái cây cao cấp, ăn tươi; vỏ giàu chất chống oxy hóa",
      "Giàu vitamin C, mangan, chất xơ và xanthone chống oxy hóa", "Ngọt thanh, hơi chua nhẹ, mọng nước",
      "Vỏ măng cụt sắc nước trị tiêu chảy, kiết lỵ trong dân gian",
      "Đặc sản giá trị cao, xuất khẩu sang Trung Quốc; măng cụt Lái Thiêu nổi tiếng",
      "Măng cụt mọc rất chậm — phải mất 7–10 năm cây mới bắt đầu cho quả",
      ["#5E2750", "#E7C9A0"], "https://vi.wikipedia.org/wiki/M%C4%83ng_c%E1%BB%A5t"),

    P("oi", "Ổi", "Psidium guajava", "Guava · ổi ta", "Sim (Myrtaceae)",
      "an-qua", "Sim (Myrtales)", "Psidium", "P. guajava",
      "Có nguồn gốc Trung và Nam Mỹ; nay trồng phổ biến khắp Việt Nam, nhiều giống ổi ngon.",
      "Ổi là cây ăn quả dễ trồng, sai quả, cho thu hoạch nhanh; giòn ngọt, giàu vitamin C.",
      "Cây gỗ nhỏ / cây bụi, vỏ nhẵn bong mảng", "3–10 m", "Cây lâu năm (chục năm)",
      "Ưa nắng hoàn toàn", "Trung bình — chịu hạn khá", "Thích nghi nhiều loại đất, ưa đất thịt thoát nước",
      "Khắp cả nước, nhiều ở ĐBSCL và Đông Nam Bộ", "Ra hoa & quả gần như quanh năm",
      "Dễ tính, chịu được đất nghèo; tỉa cành để sai quả",
      "Gieo hạt, chiết cành, ghép", "Bói quả sau 1–2 năm, thu quanh năm", "20–50 tấn/ha/năm",
      ls(("Trồng cây giống", "Tháng 0"), ("Kiến thiết tán", "Tháng 1–12"),
         ("Ra hoa đậu quả", "Năm 1–2"), ("Thu hoạch liên tục", "Năm 2+")),
      "Ruồi đục quả, rệp sáp, bệnh thán thư",
      "Trái cây ăn tươi & ép nước; lá ổi làm trà, dược liệu",
      "Rất giàu vitamin C (cao hơn cam), chất xơ, vitamin A", "Giòn ngọt, thơm; có giống ruột hồng",
      "Lá ổi non trị tiêu chảy, đau bụng; búp ổi nhai chữa đau răng",
      "Tiêu thụ nội địa rộng rãi; ổi không hạt, ổi nữ hoàng giá tốt",
      "Quả ổi chứa vitamin C gấp 4–5 lần cam — một quả đủ nhu cầu cả ngày",
      ["#9CB04A", "#E26A8D"], "https://vi.wikipedia.org/wiki/%E1%BB%94i"),

    P("na", "Na (Mãng cầu ta)", "Annona squamosa", "Sugar apple · mãng cầu ta · sa lê", "Na (Annonaceae)",
      "an-qua", "Mộc lan (Magnoliales)", "Annona", "A. squamosa",
      "Có nguồn gốc nhiệt đới châu Mỹ; trồng nhiều ở miền Bắc (Lạng Sơn, Đồng Bành) và Nam Bộ.",
      "Na là cây ăn quả với quả tròn nhiều mắt, thịt trắng ngọt thơm; cây nhỏ dễ trồng vùng đồi.",
      "Cây gỗ nhỏ rụng lá mùa khô", "3–7 m", "Cây lâu năm",
      "Ưa nắng hoàn toàn", "Trung bình — chịu hạn tốt", "Đất thoát nước, kể cả đất đồi sỏi đá vôi",
      "Lạng Sơn, Tây Ninh, Bà Rịa–Vũng Tàu", "Ra hoa tháng 3–5, quả chín tháng 7–9",
      "Chịu hạn, ưa đất đá vôi; thụ phấn bổ sung giúp đậu quả tốt",
      "Gieo hạt, ghép", "Bói quả sau 2–3 năm", "20–40 kg quả/cây/năm",
      ls(("Trồng cây giống", "Năm 0"), ("Kiến thiết tán", "Năm 1–2"),
         ("Bói quả", "Năm 2–3"), ("Ra hoa", "Tháng 3–5"), ("Thu hoạch", "Tháng 7–9")),
      "Rệp sáp, bọ vòi voi, bệnh thán thư",
      "Trái cây đặc sản ăn tươi, giá trị kinh tế cao vùng đồi", "Giàu vitamin C, B6, kali, chất xơ",
      "Ngọt đậm, thơm, thịt mềm nhiều mắt", "Hạt na giã trị chấy; lá na dùng ngoài da (lưu ý hạt độc)",
      "Na Lạng Sơn (Chi Lăng) là đặc sản nổi tiếng, giá cao",
      "Quả na chín 'mở mắt' — các mắt giãn ra và chuyển màu khi đạt độ chín",
      ["#A7C957", "#6A994E"], "https://vi.wikipedia.org/wiki/M%C3%A3ng_c%E1%BA%A7u_ta"),

    P("bo", "Bơ", "Persea americana", "Avocado · cây bơ", "Long não (Lauraceae)",
      "an-qua", "Long não (Laurales)", "Persea", "P. americana",
      "Có nguồn gốc Trung Mỹ; trồng nhiều ở Tây Nguyên (Đắk Lắk, Lâm Đồng), nổi tiếng bơ sáp.",
      "Bơ là cây ăn quả cho trái giàu chất béo lành mạnh; Tây Nguyên là vùng trồng bơ lớn nhất nước.",
      "Cây gỗ thường xanh tán rộng", "10–20 m", "Cây lâu năm (chục năm)",
      "Ưa nắng", "Trung bình — cần ẩm, sợ úng", "Đất đỏ bazan, thịt sâu, thoát nước tốt",
      "Tây Nguyên (Đắk Lắk, Lâm Đồng, Đắk Nông)", "Ra hoa tháng 12–2, quả chín tháng 5–9",
      "Ưa khí hậu mát Tây Nguyên; rất sợ ngập úng, gió mạnh làm rụng quả",
      "Ghép (giữ giống), gieo hạt", "Bói quả sau 3–4 năm", "80–200 kg quả/cây/năm",
      ls(("Ghép & trồng", "Năm 0–1"), ("Kiến thiết cơ bản", "Năm 1–3"),
         ("Bói quả", "Năm 3–4"), ("Cho quả ổn định", "Năm 5+")),
      "Bọ xít muỗi, rệp sáp, bệnh thối rễ Phytophthora",
      "Trái cây giàu dinh dưỡng, ăn tươi, sinh tố; dầu bơ mỹ phẩm",
      "Giàu chất béo không bão hòa đơn, vitamin E, K, kali", "Béo ngậy, thịt mịn dẻo (bơ sáp)",
      "Dầu bơ dưỡng da, tóc; quả bổ dưỡng cho người gầy yếu",
      "Bơ sáp Đắk Lắk, bơ booth, bơ 034 giá cao; xuất khẩu tiềm năng",
      "Hoa bơ nở theo cơ chế đực–cái lệch giờ — cần trồng xen giống để đậu quả tốt",
      ["#586F2B", "#C9B458"], "https://vi.wikipedia.org/wiki/B%C6%A1"),

    P("dua-thom", "Dứa (Thơm/Khóm)", "Ananas comosus", "Pineapple · thơm · khóm", "Dứa (Bromeliaceae)",
      "an-qua", "Hòa thảo (Poales)", "Ananas", "A. comosus",
      "Có nguồn gốc Nam Mỹ; trồng nhiều ở ĐBSCL, Ninh Bình, Thanh Hóa, Nghệ An.",
      "Dứa là cây ăn quả thân thảo, lá dài có gai, cho một quả lớn nhiều mắt ngọt thơm.",
      "Cây thân thảo, lá hình kiếm xếp hoa thị", "0,8–1,5 m", "Cây hàng năm (15–24 tháng/vụ)",
      "Ưa nắng hoàn toàn", "Trung bình — chịu hạn tốt", "Đất phèn nhẹ, đất đồi, thoát nước",
      "ĐBSCL (Tiền Giang, Kiên Giang), Ninh Bình (Đồng Giao), Bắc Trung Bộ", "Trồng quanh năm, xử lý ra hoa chủ động",
      "Chịu hạn, chịu phèn; có thể xử lý hóa chất cho ra hoa đồng loạt",
      "Trồng bằng chồi (chồi ngọn, chồi cuống)", "15–24 tháng sau trồng", "40–60 tấn/ha",
      ls(("Trồng chồi", "Tháng 0"), ("Sinh trưởng lá", "Tháng 1–10"),
         ("Xử lý ra hoa", "Tháng 10–12"), ("Quả lớn & chín", "Tháng 14–24")),
      "Rệp sáp (truyền bệnh héo), bệnh thối nõn, tuyến trùng",
      "Quả ăn tươi & đóng hộp, nước ép; lá lấy sợi", "Giàu vitamin C, mangan, enzyme bromelain",
      "Ngọt chua hài hòa, thơm đặc trưng", "Bromelain hỗ trợ tiêu hóa, kháng viêm",
      "Nguyên liệu chế biến xuất khẩu (đóng hộp, cô đặc); khóm Cầu Đúc nổi tiếng",
      "Dứa chứa bromelain phân giải protein — ăn nhiều có thể làm rát lưỡi",
      ["#F4C430", "#7A8B3A"], "https://vi.wikipedia.org/wiki/D%E1%BB%A9a"),

    P("chanh-leo", "Chanh leo (Chanh dây)", "Passiflora edulis", "Passion fruit · mác mác", "Lạc tiên (Passifloraceae)",
      "an-qua", "Sơ ri (Malpighiales)", "Passiflora", "P. edulis",
      "Có nguồn gốc Nam Mỹ; trồng nhiều ở Tây Nguyên (Gia Lai, Đắk Nông) và miền núi phía Bắc.",
      "Chanh leo là cây leo cho quả tròn chứa ruột vàng chua thơm nồng, làm nước giải khát.",
      "Cây leo thân mềm, có tua cuốn", "Leo 5–10 m", "Cây lâu năm ngắn (3–5 năm)",
      "Ưa nắng hoàn toàn", "Nhiều — cần ẩm đều", "Đất tơi xốp, giàu mùn, thoát nước",
      "Tây Nguyên (Gia Lai, Đắk Nông, Lâm Đồng), miền núi phía Bắc", "Ra hoa & quả nhiều đợt trong năm",
      "Cần giàn leo; tỉa cành, thoát nước tốt để tránh bệnh",
      "Gieo hạt, giâm hom, ghép", "5–6 tháng sau trồng, thu nhiều đợt", "30–50 tấn/ha/năm",
      ls(("Trồng & làm giàn", "Tháng 0–1"), ("Leo phủ giàn", "Tháng 1–4"),
         ("Ra hoa đậu quả", "Tháng 4–6"), ("Thu hoạch nhiều đợt", "Tháng 6+")),
      "Nhện đỏ, bọ trĩ, bệnh virus xoăn lá, đốm dầu",
      "Quả làm nước ép, sinh tố; xuất khẩu cô đặc giá trị cao", "Giàu vitamin C, A, chất xơ, chất chống oxy hóa",
      "Chua thanh, thơm nồng đặc trưng", "Hỗ trợ an thần, dễ ngủ; thanh nhiệt",
      "Xuất khẩu nước cô đặc & quả tươi tăng mạnh; Nafoods, Đồng Giao thu mua",
      "Hoa chanh leo có cấu trúc độc đáo, từng được ví như biểu tượng tôn giáo ('passion flower')",
      ["#5B2A86", "#F4C430"], "https://vi.wikipedia.org/wiki/Chanh_leo"),

    P("vu-sua", "Vú sữa", "Chrysophyllum cainito", "Star apple · vú sữa Lò Rèn", "Hồng xiêm (Sapotaceae)",
      "an-qua", "Thạch nam (Ericales)", "Chrysophyllum", "C. cainito",
      "Có nguồn gốc Trung Mỹ & Antilles; trồng nhiều ở ĐBSCL, nổi tiếng vú sữa Lò Rèn Vĩnh Kim.",
      "Vú sữa là cây ăn quả cho trái tròn vỏ tím/xanh, ruột mềm trắng ngọt như sữa.",
      "Cây gỗ thường xanh, lá mặt dưới ánh đồng", "10–15 m", "Cây lâu năm",
      "Ưa nắng", "Trung bình — cần ẩm", "Đất phù sa, thịt, thoát nước tốt",
      "ĐBSCL (Tiền Giang, Cần Thơ, Bến Tre)", "Ra hoa tháng 2–3, quả chín tháng 12–3 năm sau",
      "Khí hậu nhiệt đới ẩm; cần tưới đủ giai đoạn nuôi quả",
      "Ghép, chiết cành, gieo hạt", "Bói quả sau 3–4 năm", "150–300 quả/cây/năm",
      ls(("Trồng cây giống", "Năm 0"), ("Kiến thiết tán", "Năm 1–3"),
         ("Bói quả", "Năm 3–4"), ("Cho quả ổn định", "Năm 5+")),
      "Sâu đục quả, rệp sáp, bệnh thán thư, thối quả",
      "Trái cây đặc sản ăn tươi, giá trị xuất khẩu", "Giàu vitamin C, canxi, chất xơ",
      "Ngọt mềm, mọng 'sữa' khi chín", "Quả hỗ trợ nhuận tràng nhẹ; vỏ và lá làm thuốc dân gian",
      "Vú sữa Lò Rèn Vĩnh Kim từng xuất khẩu sang Mỹ; đặc sản giá cao",
      "Bóp nhẹ quả vú sữa chín sẽ tiết ra dịch trắng như sữa — nguồn gốc tên gọi",
      ["#7D5BA6", "#C9DEB0"], "https://vi.wikipedia.org/wiki/V%C3%BA_s%E1%BB%AFa_(c%C3%A2y)"),

    P("khe", "Khế", "Averrhoa carambola", "Star fruit · khế chua · khế ngọt", "Chua me đất (Oxalidaceae)",
      "an-qua", "Chua me đất (Oxalidales)", "Averrhoa", "A. carambola",
      "Có nguồn gốc Đông Nam Á; trồng phổ biến trong vườn nhà khắp Việt Nam.",
      "Khế là cây ăn quả thân thuộc vườn nhà, quả 5 cạnh cắt ngang hình sao, có khế chua và khế ngọt.",
      "Cây gỗ nhỏ tán xòe", "5–12 m", "Cây lâu năm",
      "Ưa nắng, chịu bóng nhẹ", "Trung bình — cần ẩm", "Đất thịt, phù sa, giàu mùn",
      "Khắp cả nước, vườn nhà nông thôn", "Ra hoa & quả nhiều đợt, rộ tháng 6–9",
      "Dễ trồng, ưa ẩm; tránh đất phèn mặn",
      "Gieo hạt, chiết, ghép", "Bói quả sau 3–4 năm, thu nhiều đợt", "100–300 kg quả/cây/năm",
      ls(("Trồng cây giống", "Năm 0"), ("Kiến thiết", "Năm 1–3"),
         ("Ra hoa nhiều đợt", "Năm 3+"), ("Thu hoạch", "Tháng 6–9 rộ")),
      "Ruồi đục quả, sâu đục quả, bệnh thán thư",
      "Quả ăn tươi, nấu canh chua, làm mứt; cây cảnh vườn", "Giàu vitamin C, chất xơ, chất chống oxy hóa",
      "Khế chua dùng nấu ăn; khế ngọt ăn tươi giòn thanh", "Quả và lá khế thanh nhiệt, lợi tiểu, trị mẩn ngứa",
      "Tiêu thụ nội địa & vườn nhà; ít thương mại hóa lớn",
      "Cắt ngang quả khế ra hình ngôi sao 5 cánh — nên tiếng Anh gọi là 'star fruit'",
      ["#E3B505", "#9CB04A"], "https://vi.wikipedia.org/wiki/Kh%E1%BA%BF"),

    P("nho", "Nho", "Vitis vinifera", "Grape · cây nho", "Nho (Vitaceae)",
      "an-qua", "Nho (Vitales)", "Vitis", "V. vinifera",
      "Có nguồn gốc vùng Địa Trung Hải–Tây Á; ở Việt Nam trồng tập trung ở Ninh Thuận, Bình Thuận.",
      "Nho là cây leo cho chùm quả mọng; Ninh Thuận nắng gió là thủ phủ nho của Việt Nam.",
      "Cây leo thân gỗ, có tua cuốn", "Leo 2–3 m trên giàn", "Cây lâu năm (10–15 năm)",
      "Ưa nắng hoàn toàn", "Trung bình — chịu hạn, sợ úng", "Đất cát pha, phù sa thoát nước tốt",
      "Ninh Thuận, Bình Thuận", "2–3 vụ/năm nhờ cắt cành điều khiển",
      "Khí hậu khô nóng ít mưa lý tưởng; cần giàn và cắt tỉa kỹ",
      "Giâm cành, ghép", "Bói quả sau 1–2 năm; mỗi vụ ~3–4 tháng", "15–25 tấn/ha/năm",
      ls(("Trồng & làm giàn", "Tháng 0–3"), ("Cắt cành tạo vụ", "Mỗi vụ"),
         ("Ra hoa đậu quả", "Tuần 4–6 sau cắt"), ("Quả chín thu hoạch", "Tháng 3–4 sau cắt")),
      "Bọ trĩ, nhện, bệnh phấn trắng, sương mai, thán thư",
      "Quả ăn tươi, làm rượu vang, nho khô; du lịch nông nghiệp", "Giàu vitamin C, K, chất chống oxy hóa (resveratrol)",
      "Ngọt, mọng nước; có giống chua làm vang", "Nho và rượu vang điều độ tốt cho tim mạch",
      "Nho Ninh Thuận (NH01-48, nho đỏ) gắn du lịch vườn nho; rượu vang Phan Rang",
      "Ninh Thuận khô nóng bậc nhất VN — chính khí hậu này giúp nho ngọt và đậu vụ liên tục",
      ["#6A2E5C", "#A7C957"], "https://vi.wikipedia.org/wiki/Nho"),

    P("hong", "Hồng", "Diospyros kaki", "Persimmon · hồng giòn · hồng Đà Lạt", "Thị (Ebenaceae)",
      "an-qua", "Thạch nam (Ericales)", "Diospyros", "D. kaki",
      "Có nguồn gốc Đông Á; ở Việt Nam trồng nhiều ở Đà Lạt, Mộc Châu, Lạng Sơn — vùng khí hậu mát.",
      "Hồng là cây ăn quả ôn đới cho quả cam đỏ; có hồng giòn và hồng ngâm, đặc sản vùng cao mát.",
      "Cây gỗ nhỏ rụng lá mùa đông", "5–12 m", "Cây lâu năm",
      "Ưa nắng", "Trung bình — cần ẩm vừa", "Đất thịt sâu, thoát nước, giàu mùn",
      "Đà Lạt (Lâm Đồng), Mộc Châu (Sơn La), Lạng Sơn", "Ra hoa tháng 3–4, quả chín tháng 9–11",
      "Cần khí hậu mát, có mùa đông lạnh để rụng lá phân hóa mầm hoa",
      "Ghép, gieo hạt", "Bói quả sau 3–5 năm", "50–150 kg quả/cây/năm",
      ls(("Trồng cây giống", "Năm 0"), ("Kiến thiết", "Năm 1–4"),
         ("Bói quả", "Năm 3–5"), ("Ra hoa", "Tháng 3–4"), ("Thu hoạch", "Tháng 9–11")),
      "Rệp sáp, ruồi đục quả, bệnh đốm lá, thán thư",
      "Quả ăn tươi (hồng giòn) hoặc khử chát (hồng ngâm); đặc sản du lịch", "Giàu vitamin A, C, chất xơ, chất chống oxy hóa",
      "Hồng giòn ngọt giòn; hồng ngâm/treo gió ngọt đậm", "Quả hồng và tai hồng dùng trong Đông y trị ho, nấc",
      "Hồng Đà Lạt treo gió thành đặc sản cao cấp; gắn du lịch vùng cao",
      "Hồng tươi rất chát do tannin — phải ngâm/ủ hoặc treo gió mới hết chát và ngọt",
      ["#E8743B", "#C9A227"], "https://vi.wikipedia.org/wiki/H%E1%BB%93ng_(c%C3%A2y)"),

    # ============ RAU (12) ============
    P("bap-cai", "Bắp cải", "Brassica oleracea var. capitata", "Cabbage · cải bắp", "Cải (Brassicaceae)",
      "rau", "Cải (Brassicales)", "Brassica", "B. oleracea",
      "Có nguồn gốc châu Âu; rau ôn đới phổ biến vụ đông, trồng nhiều ở Đà Lạt, đồng bằng Bắc Bộ.",
      "Bắp cải là rau ăn lá cuộn thành bắp chắc, rau vụ đông quen thuộc bữa cơm Việt.",
      "Cây thân thảo, lá cuộn thành bắp", "30–50 cm", "Cây hàng năm (70–110 ngày)",
      "Ưa nắng, ưa mát", "Nhiều — cần ẩm đều", "Đất thịt nhẹ, giàu mùn, thoát nước",
      "Đà Lạt, đồng bằng & trung du Bắc Bộ (vụ đông)", "Gieo tháng 8–12 (vụ đông), thu sau 70–110 ngày",
      "Ưa khí hậu mát 15–22°C; nóng quá không cuốn bắp",
      "Gieo hạt ươm cây con rồi cấy", "70–110 ngày sau gieo", "30–50 tấn/ha",
      ls(("Ươm cây con", "Ngày 0–25"), ("Trồng & hồi xanh", "Ngày 25–40"),
         ("Trải lá & cuốn bắp", "Ngày 40–80"), ("Thu hoạch", "Ngày 80–110")),
      "Sâu tơ, sâu xanh bướm trắng, rệp, bệnh thối nhũn",
      "Rau ăn lá phổ biến, luộc, xào, muối dưa, làm gỏi", "Giàu vitamin C, K, chất xơ, ít calo",
      "Giòn, ngọt nhẹ khi chín tới", "Nước ép bắp cải hỗ trợ dạ dày trong dân gian",
      "Rau vụ đông chủ lực; Đà Lạt cung cấp quanh năm",
      "Một bắp cải là một chồi khổng lồ — gồm hàng chục lá non cuộn chặt quanh đỉnh sinh trưởng",
      ["#A7C957", "#E9EDC9"], "https://vi.wikipedia.org/wiki/B%E1%BA%AFp_c%E1%BA%A3i"),

    P("ca-rot", "Cà rốt", "Daucus carota", "Carrot · củ cà rốt", "Hoa tán (Apiaceae)",
      "rau", "Hoa tán (Apiales)", "Daucus", "D. carota",
      "Có nguồn gốc Trung Á–châu Âu; rau củ ôn đới trồng nhiều ở Đà Lạt, Hải Dương, Bắc Ninh.",
      "Cà rốt là rau ăn củ màu cam, giàu beta-caroten; trồng vụ đông và quanh năm ở vùng mát.",
      "Cây thân thảo, rễ củ phình to", "Củ 15–25 cm; lá 30–50 cm", "Cây hàng năm (90–120 ngày)",
      "Ưa nắng, ưa mát", "Trung bình — ẩm đều", "Đất cát pha, tơi xốp, sâu để củ phát triển",
      "Đà Lạt, Hải Dương, Bắc Ninh, đồng bằng Bắc Bộ", "Gieo vụ đông (8–12), thu sau 90–120 ngày",
      "Ưa mát 16–24°C; đất tơi sâu cho củ thẳng đẹp",
      "Gieo hạt thẳng", "90–120 ngày sau gieo", "25–40 tấn/ha",
      ls(("Gieo hạt", "Ngày 0–10"), ("Cây con & tỉa", "Ngày 10–35"),
         ("Phình củ", "Ngày 35–90"), ("Thu hoạch", "Ngày 90–120")),
      "Tuyến trùng nốt sần, sâu xám, bệnh thối củ, đốm lá",
      "Rau củ ăn tươi, nấu, ép nước; thức ăn dinh dưỡng", "Rất giàu beta-caroten (vitamin A), chất xơ, kali",
      "Ngọt, giòn, thơm nhẹ", "Cà rốt bổ mắt, sáng da nhờ vitamin A",
      "Tiêu thụ nội địa lớn; Đà Lạt, Hải Dương cung cấp chính",
      "Cà rốt nguyên thủy có màu tím/trắng — màu cam phổ biến ngày nay do người Hà Lan lai tạo",
      ["#E8743B", "#6A994E"], "https://vi.wikipedia.org/wiki/C%C3%A0_r%E1%BB%91t"),

    P("ot", "Ớt", "Capsicum annuum", "Chili · ớt cay · ớt chỉ thiên", "Cà (Solanaceae)",
      "rau", "Cà (Solanales)", "Capsicum", "C. annuum",
      "Có nguồn gốc Trung & Nam Mỹ; gia vị không thể thiếu, trồng khắp Việt Nam.",
      "Ớt là cây cho quả cay làm gia vị; từ ớt chỉ thiên, ớt sừng đến ớt hiểm, có mặt mọi bữa ăn Việt.",
      "Cây thân thảo hóa gỗ, phân nhánh", "0,5–1,2 m", "Cây hàng năm / lâu năm ngắn",
      "Ưa nắng hoàn toàn", "Trung bình — cần ẩm, sợ úng", "Đất thịt nhẹ, thoát nước, giàu mùn",
      "Khắp cả nước; nhiều ở miền Trung, ĐBSCL", "Trồng quanh năm, thu nhiều đợt",
      "Ưa nóng ẩm; thoát nước tốt tránh thối rễ, héo xanh",
      "Gieo hạt ươm cây con", "Thu sau 70–90 ngày, hái nhiều đợt", "10–25 tấn/ha",
      ls(("Ươm cây con", "Ngày 0–30"), ("Trồng & sinh trưởng", "Ngày 30–55"),
         ("Ra hoa đậu quả", "Ngày 55–75"), ("Thu hái nhiều đợt", "Ngày 75+")),
      "Bọ trĩ, rệp, bệnh thán thư (nổ trái), héo xanh vi khuẩn",
      "Gia vị tươi, khô, tương ớt; xuất khẩu ớt khô & đông lạnh", "Giàu vitamin C, A, hợp chất capsaicin",
      "Cay nồng (capsaicin), thơm; ớt ngọt thì không cay", "Ớt kích thích tiêu hóa, giảm đau ngoài da (capsaicin)",
      "Ớt tươi & khô xuất khẩu sang Trung Quốc, Hàn Quốc",
      "Độ cay của ớt đo bằng thang Scoville — ớt hiểm Việt Nam cay hơn nhiều loại ớt phương Tây",
      ["#C1121F", "#6A994E"], "https://vi.wikipedia.org/wiki/%E1%BB%9At"),

    P("ca-tim", "Cà tím", "Solanum melongena", "Eggplant · cà dái dê · cà tím dài", "Cà (Solanaceae)",
      "rau", "Cà (Solanales)", "Solanum", "S. melongena",
      "Có nguồn gốc Ấn Độ–Đông Nam Á; rau quả quen thuộc, trồng khắp Việt Nam.",
      "Cà tím là rau ăn quả vỏ tím bóng, thịt mềm; món nướng, kho, xào quen thuộc.",
      "Cây thân thảo hóa gỗ, phân nhánh", "0,5–1,2 m", "Cây hàng năm / lâu năm ngắn",
      "Ưa nắng hoàn toàn", "Trung bình — cần ẩm đều", "Đất thịt nhẹ, giàu mùn, thoát nước",
      "Khắp cả nước", "Trồng quanh năm, thu nhiều đợt",
      "Ưa nóng ẩm; cần đủ nắng và phân để sai quả",
      "Gieo hạt ươm cây con", "Thu sau 70–90 ngày, hái nhiều đợt", "25–40 tấn/ha",
      ls(("Ươm cây con", "Ngày 0–30"), ("Trồng & sinh trưởng", "Ngày 30–55"),
         ("Ra hoa đậu quả", "Ngày 55–75"), ("Thu hái nhiều đợt", "Ngày 75+")),
      "Bọ rùa 28 chấm, sâu đục quả, bệnh héo xanh, đốm lá",
      "Rau quả nướng, kho, xào; món chay phổ biến", "Giàu chất xơ, kali, chất chống oxy hóa (nasunin ở vỏ)",
      "Thịt mềm, vị nhạt thấm gia vị", "Cà tím hỗ trợ hạ cholesterol; tính mát",
      "Tiêu thụ nội địa rộng; có giống cà tím dài và cà tím tròn",
      "Màu tím của vỏ cà đến từ nasunin — một chất chống oxy hóa bảo vệ tế bào",
      ["#5E2750", "#9CB04A"], "https://vi.wikipedia.org/wiki/C%C3%A0_t%C3%ADm"),

    P("hanh-la", "Hành lá", "Allium fistulosum", "Scallion · hành hoa · hành ta", "Hành (Amaryllidaceae)",
      "rau", "Măng tây (Asparagales)", "Allium", "A. fistulosum",
      "Có nguồn gốc Đông Á; gia vị rau thơm trồng khắp Việt Nam, có mặt trong hầu hết món ăn.",
      "Hành lá là rau gia vị thân hành nhỏ, lá ống xanh; gần như món Việt nào cũng cần.",
      "Cây thân thảo, lá ống rỗng", "30–50 cm", "Cây hàng năm (45–60 ngày)",
      "Ưa nắng, ưa mát", "Nhiều — cần ẩm đều", "Đất thịt nhẹ, giàu mùn, thoát nước",
      "Khắp cả nước, chuyên canh ở ĐBSCL & ven đô", "Trồng quanh năm, thu sau 45–60 ngày",
      "Dễ trồng, mau thu; cần ẩm và thoát nước tốt",
      "Trồng bằng tép/nhánh hoặc gieo hạt", "45–60 ngày sau trồng", "15–25 tấn/ha/vụ",
      ls(("Trồng nhánh / gieo", "Ngày 0"), ("Bén rễ & đẻ nhánh", "Ngày 5–25"),
         ("Vươn lá", "Ngày 25–45"), ("Thu hoạch", "Ngày 45–60")),
      "Sâu xanh, dòi đục lá, bệnh thối nhũn, sương mai",
      "Rau gia vị tươi cho hầu hết món ăn; hành phi", "Giàu vitamin K, C, A, hợp chất lưu huỳnh",
      "Thơm cay nhẹ đặc trưng", "Hành giải cảm, làm ấm; cháo hành giải cảm dân gian",
      "Rau gia vị thiết yếu, tiêu thụ hằng ngày khắp cả nước",
      "Hành lá khác hành tây — nó không tạo củ to mà ăn cả thân trắng lẫn lá xanh",
      ["#6A994E", "#E9EDC9"], "https://vi.wikipedia.org/wiki/H%C3%A0nh_l%C3%A1"),

    P("toi", "Tỏi", "Allium sativum", "Garlic · tỏi ta · tỏi Lý Sơn", "Hành (Amaryllidaceae)",
      "rau", "Măng tây (Asparagales)", "Allium", "A. sativum",
      "Có nguồn gốc Trung Á; gia vị quan trọng, nổi tiếng tỏi Lý Sơn, tỏi Phan Rang, tỏi Bắc.",
      "Tỏi là cây gia vị lấy củ gồm nhiều tép, vị cay nồng; vừa là gia vị vừa là vị thuốc.",
      "Cây thân thảo, củ gồm nhiều tép", "30–60 cm", "Cây hàng năm (110–140 ngày)",
      "Ưa nắng, ưa mát", "Trung bình — ẩm vừa, sợ úng", "Đất cát pha, tơi xốp, thoát nước (cát biển Lý Sơn)",
      "Lý Sơn (Quảng Ngãi), Phan Rang, Bắc Giang, Hải Dương", "Trồng vụ đông (9–11), thu sau ~4 tháng",
      "Ưa mát khô lúc tạo củ; đất tơi thoát nước tránh thối củ",
      "Trồng bằng tép tỏi giống", "110–140 ngày sau trồng", "5–10 tấn củ khô/ha",
      ls(("Trồng tép", "Ngày 0"), ("Mọc mầm & ra lá", "Ngày 5–40"),
         ("Tạo củ", "Ngày 40–110"), ("Thu hoạch & phơi", "Ngày 110–140")),
      "Sâu xanh, bệnh sương mai, thối củ, vàng lá",
      "Gia vị thiết yếu; tỏi đen, tinh dầu tỏi; vị thuốc", "Giàu hợp chất allicin, vitamin C, mangan",
      "Cay nồng, thơm hăng đặc trưng", "Tỏi kháng khuẩn, hỗ trợ tim mạch, hạ mỡ máu",
      "Tỏi Lý Sơn (tỏi cô đơn) đặc sản giá cao; tỏi đen chế biến giá trị gia tăng",
      "Tỏi 'cô đơn' Lý Sơn chỉ có một tép duy nhất — hiếm và được ưa chuộng làm thuốc",
      ["#EDE0D4", "#9CB04A"], "https://vi.wikipedia.org/wiki/T%E1%BB%8Fi"),

    P("kho-qua", "Khổ qua (Mướp đắng)", "Momordica charantia", "Bitter melon · mướp đắng", "Bầu bí (Cucurbitaceae)",
      "rau", "Bầu bí (Cucurbitales)", "Momordica", "M. charantia",
      "Có nguồn gốc nhiệt đới châu Á; rau quả quen thuộc Nam Bộ, trồng khắp Việt Nam.",
      "Khổ qua là cây leo cho quả sần đắng đặc trưng; món nhồi thịt, xào trứng, canh giải nhiệt.",
      "Cây leo thân mềm, có tua cuốn", "Leo 2–4 m", "Cây hàng năm (60–90 ngày)",
      "Ưa nắng hoàn toàn", "Nhiều — cần ẩm đều", "Đất thịt nhẹ, giàu mùn, thoát nước",
      "Khắp cả nước, nhiều ở Nam Bộ", "Trồng quanh năm, thu sau 50–60 ngày",
      "Cần giàn leo; ưa nóng ẩm, thoát nước tốt",
      "Gieo hạt thẳng", "Thu sau 50–60 ngày, hái nhiều đợt", "20–35 tấn/ha",
      ls(("Gieo hạt & làm giàn", "Ngày 0–10"), ("Leo phủ giàn", "Ngày 10–35"),
         ("Ra hoa đậu quả", "Ngày 35–50"), ("Thu hái nhiều đợt", "Ngày 50+")),
      "Ruồi đục quả, rệp, bệnh sương mai, phấn trắng",
      "Rau quả nấu canh, xào, nhồi thịt; trà khổ qua", "Giàu vitamin C, chất xơ, hợp chất charantin",
      "Đắng đặc trưng, hậu mát", "Khổ qua hỗ trợ hạ đường huyết; thanh nhiệt giải độc",
      "Tiêu thụ nội địa; trà khổ qua rừng làm sản phẩm sức khỏe",
      "Vị đắng của khổ qua đến từ momordicin — chất được nghiên cứu hỗ trợ hạ đường huyết",
      ["#6A994E", "#A7C957"], "https://vi.wikipedia.org/wiki/M%C6%B0%E1%BB%9Bp_%C4%91%E1%BA%AFng"),

    P("bi-do", "Bí đỏ (Bí ngô)", "Cucurbita moschata", "Pumpkin · bí rợ", "Bầu bí (Cucurbitaceae)",
      "rau", "Bầu bí (Cucurbitales)", "Cucurbita", "C. moschata",
      "Có nguồn gốc châu Mỹ; trồng khắp Việt Nam, phổ biến vùng trung du và miền núi.",
      "Bí đỏ là cây bò cho quả lớn ruột vàng cam, vị bùi ngọt; nấu canh, súp, làm bánh.",
      "Cây thân bò, lá lớn có lông ráp", "Bò 3–6 m", "Cây hàng năm (90–120 ngày)",
      "Ưa nắng hoàn toàn", "Trung bình — chịu hạn khá", "Đất thịt nhẹ, đất đồi, thoát nước",
      "Khắp cả nước, nhiều ở trung du & miền núi", "Trồng quanh năm, thu sau 90–120 ngày",
      "Dễ tính, chịu hạn; cần đất rộng cho dây bò",
      "Gieo hạt thẳng", "90–120 ngày sau gieo", "15–30 tấn/ha",
      ls(("Gieo hạt", "Ngày 0–10"), ("Bò lan & ra hoa", "Ngày 10–50"),
         ("Đậu & lớn quả", "Ngày 50–90"), ("Thu hoạch", "Ngày 90–120")),
      "Rệp, bọ dưa, ruồi đục quả, bệnh phấn trắng",
      "Rau quả nấu canh, súp, làm bánh; ngọn & hoa cũng ăn được", "Giàu beta-caroten (vitamin A), chất xơ, kali",
      "Bùi ngọt, thịt vàng dẻo", "Bí đỏ bổ mắt, bổ não dân gian; hạt bí trị giun",
      "Tiêu thụ nội địa lớn; bí đỏ để được lâu, dễ vận chuyển",
      "Cả quả, ngọn (rau bí), hoa và hạt bí đỏ đều ăn được — một cây cho nhiều loại thực phẩm",
      ["#E8743B", "#C9A227"], "https://vi.wikipedia.org/wiki/B%C3%AD_ng%C3%B4"),

    P("su-su", "Su su", "Sechium edule", "Chayote · su su", "Bầu bí (Cucurbitaceae)",
      "rau", "Bầu bí (Cucurbitales)", "Sechium", "S. edule",
      "Có nguồn gốc Trung Mỹ; trồng nhiều ở vùng mát như Tam Đảo, Sa Pa, Đà Lạt.",
      "Su su là cây leo cho quả xanh và ngọn non làm rau; đặc sản rau sạch vùng mát.",
      "Cây leo lâu năm, tua cuốn khỏe", "Leo 5–10 m", "Cây lâu năm ngắn",
      "Ưa nắng, ưa mát", "Nhiều — cần ẩm đều", "Đất thịt giàu mùn, thoát nước",
      "Tam Đảo, Sa Pa, Mộc Châu, Đà Lạt", "Trồng đầu mùa, thu quả & ngọn nhiều đợt",
      "Ưa khí hậu mát ẩm; cần giàn chắc cho dây leo",
      "Trồng cả quả già để nảy mầm", "Thu ngọn sau ~2 tháng, quả sau ~3 tháng", "30–60 tấn quả/ha",
      ls(("Trồng quả giống & làm giàn", "Tháng 0–1"), ("Leo phủ giàn", "Tháng 1–2"),
         ("Thu ngọn", "Tháng 2+"), ("Ra hoa & thu quả", "Tháng 3+")),
      "Rệp, nhện đỏ, bệnh sương mai, thối quả",
      "Quả & ngọn luộc, xào; rau sạch vùng mát", "Giàu chất xơ, vitamin C, folate, ít calo",
      "Quả & ngọn ngọt mát, giòn", "Su su tính mát, lợi tiểu, nhuận tràng nhẹ",
      "Đặc sản rau vùng mát (ngọn su su Tam Đảo, Sa Pa) giá tốt",
      "Một gốc su su có thể phủ kín cả giàn lớn và cho thu hoạch ngọn lẫn quả suốt nhiều tháng",
      ["#A7C957", "#E9EDC9"], "https://vi.wikipedia.org/wiki/Su_su"),

    P("bau", "Bầu", "Lagenaria siceraria", "Bottle gourd · bầu nậm · bầu sao", "Bầu bí (Cucurbitaceae)",
      "rau", "Bầu bí (Cucurbitales)", "Lagenaria", "L. siceraria",
      "Có nguồn gốc châu Phi/châu Á; cây giàn quen thuộc vườn nhà khắp Việt Nam.",
      "Bầu là cây leo cho quả dài non làm rau; canh bầu, bầu xào là món dân dã mùa hè.",
      "Cây leo thân mềm, có lông, tua cuốn", "Leo 4–8 m", "Cây hàng năm (75–100 ngày)",
      "Ưa nắng hoàn toàn", "Nhiều — cần ẩm đều", "Đất thịt nhẹ, giàu mùn, thoát nước",
      "Khắp cả nước, vườn nhà nông thôn", "Trồng đầu mùa mưa/xuân, thu nhiều đợt",
      "Cần giàn; ưa nóng ẩm, đủ nước nuôi quả",
      "Gieo hạt thẳng", "Thu sau 60–75 ngày, hái nhiều đợt", "25–40 tấn/ha",
      ls(("Gieo hạt & làm giàn", "Ngày 0–12"), ("Leo phủ giàn", "Ngày 12–40"),
         ("Ra hoa đậu quả", "Ngày 40–60"), ("Thu hái nhiều đợt", "Ngày 60+")),
      "Bọ dưa, ruồi đục quả, rệp, bệnh sương mai",
      "Rau quả nấu canh, luộc, xào; quả già làm gáo/bầu khô", "Nhiều nước, ít calo, có vitamin C, chất xơ",
      "Ngọt mát, mềm khi non", "Bầu tính mát, lợi tiểu, giải nhiệt mùa hè",
      "Tiêu thụ nội địa & vườn nhà; rau mùa hè dân dã",
      "Quả bầu già khô cứng từng được dùng làm gáo múc nước, bình đựng — 'bầu nậm' truyền thống",
      ["#9CB04A", "#E9EDC9"], "https://vi.wikipedia.org/wiki/B%E1%BA%A7u"),

    P("muop", "Mướp", "Luffa aegyptiaca", "Luffa · mướp hương · mướp ta", "Bầu bí (Cucurbitaceae)",
      "rau", "Bầu bí (Cucurbitales)", "Luffa", "L. aegyptiaca",
      "Có nguồn gốc nhiệt đới châu Á; cây giàn vườn nhà quen thuộc khắp Việt Nam.",
      "Mướp là cây leo cho quả dài non làm rau; quả già tạo xơ mướp dùng cọ rửa.",
      "Cây leo thân có cạnh, tua cuốn", "Leo 4–8 m", "Cây hàng năm (70–100 ngày)",
      "Ưa nắng hoàn toàn", "Nhiều — cần ẩm đều", "Đất thịt nhẹ, giàu mùn, thoát nước",
      "Khắp cả nước, vườn nhà nông thôn", "Trồng đầu mùa mưa/xuân, thu nhiều đợt",
      "Cần giàn; ưa nóng ẩm, đủ nước nuôi quả",
      "Gieo hạt thẳng", "Thu sau 50–70 ngày, hái nhiều đợt", "20–35 tấn/ha",
      ls(("Gieo hạt & làm giàn", "Ngày 0–12"), ("Leo phủ giàn", "Ngày 12–40"),
         ("Ra hoa đậu quả", "Ngày 40–55"), ("Thu hái nhiều đợt", "Ngày 55+")),
      "Bọ dưa, ruồi đục quả, rệp, bệnh sương mai",
      "Rau quả nấu canh, xào; quả già lấy xơ mướp", "Nhiều nước, có vitamin C, chất xơ, ít calo",
      "Ngọt mát, mềm thơm (mướp hương)", "Mướp tính mát, lợi sữa, thông tiểu; xơ mướp cọ rửa",
      "Tiêu thụ nội địa & vườn nhà; xơ mướp làm sản phẩm tắm thiên nhiên",
      "Quả mướp để già khô đi sẽ thành xơ mướp — miếng cọ rửa hoàn toàn tự nhiên",
      ["#A7C957", "#C9A227"], "https://vi.wikipedia.org/wiki/M%C6%B0%E1%BB%9Bp"),

    P("xa-lach", "Xà lách", "Lactuca sativa", "Lettuce · rau diếp · xà lách", "Cúc (Asteraceae)",
      "rau", "Cúc (Asterales)", "Lactuca", "L. sativa",
      "Có nguồn gốc Địa Trung Hải; rau ăn sống phổ biến, trồng nhiều ở Đà Lạt và ven đô.",
      "Xà lách là rau ăn lá tươi giòn, dùng ăn sống, cuốn, salad; rau sạch vùng mát chủ lực.",
      "Cây thân thảo, lá xếp hoa thị", "20–35 cm", "Cây hàng năm (40–65 ngày)",
      "Ưa nắng nhẹ, ưa mát", "Nhiều — cần ẩm đều", "Đất thịt nhẹ, tơi xốp, giàu mùn",
      "Đà Lạt, vành đai rau ven đô (Hà Nội, TP.HCM)", "Trồng quanh năm vùng mát, thu sau 40–65 ngày",
      "Ưa mát 15–22°C; nóng quá dễ đắng và trổ ngồng sớm",
      "Gieo hạt ươm cây con rồi cấy", "40–65 ngày sau gieo", "15–25 tấn/ha/vụ",
      ls(("Ươm cây con", "Ngày 0–18"), ("Trồng & hồi xanh", "Ngày 18–30"),
         ("Trải lá", "Ngày 30–50"), ("Thu hoạch", "Ngày 45–65")),
      "Sâu xanh, rệp, ốc sên, bệnh thối nhũn, sương mai",
      "Rau ăn sống, salad, cuốn; rau sạch giá trị", "Giàu vitamin K, A, folate, nước, ít calo",
      "Giòn, mát, ngọt nhẹ", "Xà lách tính mát, hỗ trợ ngủ ngon (lactucarium) trong dân gian",
      "Rau ăn sống chủ lực; thủy canh & rau sạch Đà Lạt phát triển mạnh",
      "Xà lách thuộc họ Cúc — cùng họ với hoa cúc và hướng dương, khác hẳn các loại cải",
      ["#A7C957", "#E9EDC9"], "https://vi.wikipedia.org/wiki/X%C3%A0_l%C3%A1ch"),

    # ============ LƯƠNG THỰC (2) ============
    P("khoai-tay", "Khoai tây", "Solanum tuberosum", "Potato · khoai tây Đà Lạt", "Cà (Solanaceae)",
      "luong-thuc", "Cà (Solanales)", "Solanum", "S. tuberosum",
      "Có nguồn gốc dãy Andes Nam Mỹ; ở Việt Nam trồng nhiều ở Đà Lạt và đồng bằng Bắc Bộ vụ đông.",
      "Khoai tây là cây lương thực lấy củ giàu tinh bột; vừa là rau vừa là lương thực, vụ đông quan trọng.",
      "Cây thân thảo, củ là thân ngầm phình to", "40–70 cm", "Cây hàng năm (85–110 ngày)",
      "Ưa nắng, ưa mát", "Trung bình — ẩm đều, sợ úng", "Đất thịt nhẹ, tơi xốp, thoát nước",
      "Đà Lạt (Lâm Đồng), đồng bằng Bắc Bộ (vụ đông)", "Trồng vụ đông (10–12), thu sau ~3 tháng",
      "Ưa mát 15–20°C; đất tơi xốp cho củ phát triển; tránh úng gây thối củ",
      "Trồng bằng củ giống", "85–110 ngày sau trồng", "15–30 tấn/ha",
      ls(("Trồng củ giống", "Ngày 0"), ("Mọc mầm & ra lá", "Ngày 0–30"),
         ("Hình thành & phình củ", "Ngày 30–85"), ("Thu hoạch", "Ngày 85–110")),
      "Rệp, bọ hà khoai tây, bệnh mốc sương, héo xanh",
      "Lương thực & rau: luộc, chiên, nấu; nguyên liệu chế biến", "Giàu tinh bột, vitamin C, kali, vitamin B6",
      "Bùi, bở khi chín", "Khoai tây luộc dễ tiêu; đắp lát khoai làm dịu da (dân gian)",
      "Nguyên liệu khoai tây chế biến (snack, khoai chiên) nhu cầu lớn; Đà Lạt cung cấp chính",
      "Củ khoai tây thực ra là thân ngầm phình to (củ thân), không phải rễ củ như khoai lang",
      ["#C9A227", "#9C6B30"], "https://vi.wikipedia.org/wiki/Khoai_t%C3%A2y"),

    P("khoai-mon", "Khoai môn", "Colocasia esculenta", "Taro · khoai sọ · môn", "Ráy (Araceae)",
      "luong-thuc", "Trạch tả (Alismatales)", "Colocasia", "C. esculenta",
      "Có nguồn gốc Đông Nam Á; cây lương thực lấy củ lâu đời, trồng khắp Việt Nam.",
      "Khoai môn là cây lấy củ giàu tinh bột, lá to hình tim; củ bùi dẻo nấu canh, làm bánh, chè.",
      "Cây thân thảo, lá to hình khiên, củ ngầm", "0,6–1,5 m", "Cây hàng năm (5–8 tháng)",
      "Ưa nắng, chịu bóng nhẹ", "Nhiều — ưa ẩm, chịu đất trũng", "Đất thịt ẩm, giàu mùn, kể cả đất trũng",
      "Khắp cả nước, nhiều ở miền núi & ĐBSCL", "Trồng đầu mùa mưa, thu sau 5–8 tháng",
      "Ưa ẩm, chịu được đất ngập nước nông; cần đủ ẩm cho củ to",
      "Trồng bằng củ con / chồi", "5–8 tháng sau trồng", "15–25 tấn củ/ha",
      ls(("Trồng củ giống", "Tháng 0"), ("Ra lá & đẻ nhánh", "Tháng 1–3"),
         ("Phình củ", "Tháng 3–6"), ("Thu hoạch", "Tháng 5–8")),
      "Sâu khoang, nhện, bệnh sương mai lá, thối củ",
      "Lương thực & thực phẩm: canh, hầm, bánh khoai, chè", "Giàu tinh bột, chất xơ, kali, vitamin B6",
      "Bùi, dẻo, thơm khi chín", "Khoai môn dễ tiêu, bổ tỳ vị (Đông y); lưu ý nhựa gây ngứa khi sống",
      "Tiêu thụ nội địa; khoai môn cao cấp (môn sáp) làm bánh, kem",
      "Nhựa khoai môn sống chứa tinh thể canxi oxalat gây ngứa — phải nấu chín kỹ mới ăn được",
      ["#7D5BA6", "#9C6B30"], "https://vi.wikipedia.org/wiki/Khoai_m%C3%B4n"),

    # ============ CÔNG NGHIỆP (3) ============
    P("dau-phong", "Đậu phộng (Lạc)", "Arachis hypogaea", "Peanut · groundnut · lạc", "Đậu (Fabaceae)",
      "cong-nghiep", "Đậu (Fabales)", "Arachis", "A. hypogaea",
      "Có nguồn gốc Nam Mỹ; cây công nghiệp lấy dầu & thực phẩm, trồng khắp Việt Nam.",
      "Đậu phộng là cây lấy hạt giàu dầu và đạm; quả chín dưới đất, vừa ép dầu vừa làm thực phẩm.",
      "Cây thân thảo thấp, quả phát triển trong đất", "30–60 cm", "Cây hàng năm (90–120 ngày)",
      "Ưa nắng hoàn toàn", "Trung bình — chịu hạn khá", "Đất cát pha, tơi xốp, thoát nước",
      "Bắc Trung Bộ, Tây Nguyên, Đông Nam Bộ, ĐBSCL", "Trồng 2 vụ (xuân & thu), thu sau 90–120 ngày",
      "Đất tơi xốp cho tia quả đâm xuống; cố định đạm cải tạo đất",
      "Gieo hạt thẳng", "90–120 ngày sau gieo", "2–4 tấn quả khô/ha",
      ls(("Gieo hạt", "Ngày 0–7"), ("Sinh trưởng & ra hoa", "Ngày 7–40"),
         ("Tia quả đâm đất & tạo quả", "Ngày 40–90"), ("Thu hoạch", "Ngày 90–120")),
      "Sâu khoang, sâu xám, bệnh héo xanh, đốm lá, thối quả",
      "Lấy dầu ăn (dầu lạc), thực phẩm (rang, ép, làm bơ); khô dầu làm thức ăn chăn nuôi",
      "Giàu chất béo, đạm thực vật, vitamin E, folate", "Bùi béo khi rang chín",
      "Lạc bổ dưỡng, dầu lạc nấu ăn; lưu ý nấm mốc sinh aflatoxin", "Dầu lạc & lạc nhân tiêu thụ nội địa và xuất khẩu",
      "Hoa đậu phộng thụ phấn trên không nhưng quả lại chui xuống đất để phát triển — gọi là 'tia quả'",
      ["#C9A227", "#9C6B30"], "https://vi.wikipedia.org/wiki/L%E1%BA%A1c"),

    P("dau-nanh", "Đậu nành (Đậu tương)", "Glycine max", "Soybean · đậu tương", "Đậu (Fabaceae)",
      "cong-nghiep", "Đậu (Fabales)", "Glycine", "G. max",
      "Có nguồn gốc Đông Á; cây công nghiệp lấy hạt giàu đạm & dầu, trồng nhiều ở ĐBSH, Tây Nguyên.",
      "Đậu nành là cây lấy hạt giàu protein nhất trong các loại đậu; nguyên liệu đậu phụ, sữa, dầu, tương.",
      "Cây thân thảo, quả có lông", "40–80 cm", "Cây hàng năm (75–100 ngày)",
      "Ưa nắng hoàn toàn", "Trung bình — cần ẩm đều", "Đất thịt nhẹ, phù sa, thoát nước",
      "Đồng bằng sông Hồng, Tây Nguyên, ĐBSCL", "Trồng nhiều vụ trong năm, thu sau 75–100 ngày",
      "Cố định đạm cải tạo đất; cần đủ ẩm giai đoạn ra hoa & vào hạt",
      "Gieo hạt thẳng", "75–100 ngày sau gieo", "1,5–2,5 tấn hạt/ha",
      ls(("Gieo hạt", "Ngày 0–7"), ("Sinh trưởng & ra hoa", "Ngày 7–45"),
         ("Vào hạt & chắc hạt", "Ngày 45–80"), ("Thu hoạch", "Ngày 80–100")),
      "Sâu cuốn lá, sâu đục quả, rệp, bệnh gỉ sắt, đốm lá",
      "Nguyên liệu đậu phụ, sữa đậu nành, dầu, nước tương; khô đậu chăn nuôi",
      "Rất giàu protein thực vật, dầu, isoflavone", "Bùi nhẹ; chế biến đa dạng",
      "Đậu nành bổ dưỡng, tốt cho tim mạch, nội tiết (isoflavone)", "Nhu cầu chế biến lớn; phần lớn vẫn nhập khẩu",
      "Đậu nành chứa tới ~40% protein — cao nhất trong các loại hạt đậu thông dụng",
      ["#E3C16F", "#9CB04A"], "https://vi.wikipedia.org/wiki/%C4%90%E1%BA%ADu_t%C6%B0%C6%A1ng"),

    P("bong-vai", "Bông vải", "Gossypium hirsutum", "Cotton · cây bông", "Bông (Malvaceae)",
      "cong-nghiep", "Bông (Malvales)", "Gossypium", "G. hirsutum",
      "Có nguồn gốc Trung Mỹ; cây công nghiệp lấy sợi, từng trồng nhiều ở Tây Nguyên, Nam Trung Bộ.",
      "Bông vải là cây lấy sợi từ quả nang; sợi bông là nguyên liệu dệt may quan trọng.",
      "Cây thân thảo hóa gỗ, phân cành", "1–1,5 m", "Cây hàng năm (150–180 ngày)",
      "Ưa nắng hoàn toàn", "Trung bình — chịu hạn khá", "Đất thịt nhẹ, thoát nước, giàu dinh dưỡng",
      "Tây Nguyên, Nam Trung Bộ (Ninh Thuận, Bình Thuận)", "Trồng đầu mùa mưa, thu sau ~5–6 tháng",
      "Ưa nắng nóng, khô lúc nở quả; mưa nhiều lúc thu làm hỏng xơ",
      "Gieo hạt thẳng", "150–180 ngày sau gieo", "1,5–2,5 tấn bông hạt/ha",
      ls(("Gieo hạt", "Ngày 0–10"), ("Sinh trưởng & ra nụ", "Ngày 10–70"),
         ("Ra hoa & tạo quả nang", "Ngày 70–130"), ("Quả nứt & thu bông", "Ngày 130–180")),
      "Sâu xanh, sâu hồng đục quả, rầy, bọ trĩ, bệnh héo",
      "Lấy sợi bông dệt vải; hạt ép dầu & làm thức ăn chăn nuôi", "Hạt bông chứa dầu & đạm (cho chăn nuôi)",
      "—", "Hạt bông & dầu bông dùng trong công nghiệp (không ăn trực tiếp do gossypol)",
      "Nguyên liệu dệt may; sản xuất trong nước nhỏ, chủ yếu nhập bông xơ",
      "Sợi bông là lông trên hạt — mỗi quả nang bung ra để lộ búi xơ trắng bao quanh hạt",
      ["#F5F0E6", "#6A994E"], "https://vi.wikipedia.org/wiki/B%C3%B4ng_v%E1%BA%A3i"),

    # ============ LÂM NGHIỆP (10) ============
    P("giang-huong", "Giáng hương", "Pterocarpus macrocarpus", "Burma padauk · dáng hương", "Đậu (Fabaceae)",
      "lam-nghiep", "Đậu (Fabales)", "Pterocarpus", "P. macrocarpus",
      "Loài gỗ quý bản địa Đông Nam Á; phân bố ở rừng Tây Nguyên, miền Trung Việt Nam.",
      "Giáng hương là cây gỗ quý nhóm I, gỗ đỏ cam thơm; được trồng và bảo tồn ở Tây Nguyên, miền Trung.",
      "Cây gỗ lớn, thân tròn thẳng", "15–30 m", "Cây lâu năm, khai thác sau 40–50 năm",
      "Ưa nắng hoàn toàn", "Trung bình — chịu hạn tốt", "Đất đỏ bazan, đất thịt thoát nước, pH 6–7",
      "Tây Nguyên (Kon Tum, Gia Lai, Đắk Lắk), miền Trung", "Trồng đầu mùa mưa, ra hoa vàng tháng 3–5",
      "Ưa khí hậu nhiệt đới có mùa khô; chịu hạn tốt khi trưởng thành",
      "Gieo hạt, giâm hom", "40–50 năm (gỗ lớn)", "3–4 m³ gỗ/ha/năm",
      ls(("Gieo hạt / trồng", "Năm 1–2"), ("Phát triển thân", "Năm 2–8"),
         ("Sinh trưởng đường kính", "Năm 8–20"), ("Trưởng thành", "Năm 20–40"), ("Khai thác", "Năm 40–50")),
      "Sâu đục thân, sâu ăn lá, nấm thối rễ",
      "Gỗ quý nhóm I màu đỏ cam, vân đẹp — đồ nội thất cao cấp, tượng, mỹ nghệ; cây bóng mát đô thị",
      "—", "—", "Vỏ và gỗ dùng trong y học cổ truyền",
      "Gỗ giáng hương giá 10–20 triệu đ/m³; nhóm gỗ quý hiếm, được bảo tồn",
      "Mùa hoa, giáng hương nở vàng rực và thường rụng đồng loạt sau mưa — tạo 'thảm hoa vàng' đặc trưng phố núi",
      ["#C8521E", "#E3B505"], "https://vi.wikipedia.org/wiki/Gi%C3%A1ng_h%C6%B0%C6%A1ng"),

    P("trac", "Trắc", "Dalbergia cochinchinensis", "Siamese rosewood · trắc đỏ", "Đậu (Fabaceae)",
      "lam-nghiep", "Đậu (Fabales)", "Dalbergia", "D. cochinchinensis",
      "Loài gỗ quý bậc nhất Đông Dương; phân bố rừng tự nhiên Tây Nguyên, Nam Trung Bộ, biên giới Việt–Lào.",
      "Trắc là cây gỗ quý nhóm I, gỗ nâu đỏ tới đen vân đẹp, rất nặng và bền — gỗ mỹ nghệ giá cao bậc nhất.",
      "Cây gỗ lớn, thân tròn", "20–25 m", "Cây lâu năm, khai thác sau 50–80 năm",
      "Ưa nắng hoàn toàn", "Trung bình — chịu hạn tốt", "Đất dốc thoát nước tốt, pH trung tính",
      "Tây Nguyên (Kon Tum, Gia Lai), Quảng Nam, Quảng Trị", "Trồng đầu mùa mưa, sinh trưởng chậm",
      "Sinh trưởng rất chậm; ưa khí hậu nhiệt đới ẩm có mùa khô",
      "Giâm hom, ghép, gieo hạt", "50–80 năm (gỗ quý)", "~2 m³ gỗ/ha/năm",
      ls(("Trồng cây con", "Năm 1–3"), ("Sinh trưởng chậm", "Năm 3–15"),
         ("Phát triển đường kính", "Năm 15–40"), ("Khai thác gỗ quý", "Năm 40–80")),
      "Sâu đục thân, nấm bệnh gốc",
      "Gỗ quý nhóm I, nâu đỏ–đen vân 3D — tượng, bàn ghế, đồ thờ, mỹ nghệ cao cấp",
      "—", "—", "—",
      "Gỗ trắc giá 15–30 triệu đ/m³, trắc cổ thụ cao hơn nhiều; thuộc nhóm gỗ quý được bảo vệ nghiêm ngặt",
      "Gỗ trắc nặng tới mức thả xuống nước gần như chìm — tỷ trọng xấp xỉ 1, hiếm có ở các loài gỗ",
      ["#5A2E22", "#9C6B30"], "https://vi.wikipedia.org/wiki/Tr%E1%BA%AFc_(c%C3%A2y)"),

    P("sao-den", "Sao đen", "Hopea odorata", "Sao den · makha", "Dầu (Dipterocarpaceae)",
      "lam-nghiep", "Bông (Malvales)", "Hopea", "H. odorata",
      "Loài gỗ lớn bản địa; phân bố rừng Tây Nguyên, Đông Nam Bộ; trồng làm cây công trình đô thị.",
      "Sao đen là cây gỗ lớn vừa cho gỗ quý vừa làm cây xanh đường phố; tán cao, thân thẳng đẹp.",
      "Cây gỗ lớn, thân thẳng tròn", "20–40 m", "Cây lâu năm, khai thác sau 40–50 năm",
      "Ưa nắng, chịu bóng khi nhỏ", "Trung bình đến nhiều", "Đất thịt sâu, thoát nước tốt",
      "Tây Nguyên, Đông Nam Bộ; trồng đường phố nhiều đô thị", "Trồng đầu mùa mưa; quả có cánh phát tán nhờ gió",
      "Ưa khí hậu nhiệt đới ẩm; cây con cần che bóng nhẹ",
      "Gieo hạt, giâm hom", "40–50 năm (gỗ)", "3–4 m³ gỗ/ha/năm",
      ls(("Ươm & trồng", "Năm 1–3"), ("Sinh trưởng nhanh", "Năm 3–12"),
         ("Phát triển ổn định", "Năm 12–30"), ("Khai thác", "Năm 40–50")),
      "Sâu đục thân, sâu ăn lá, nấm bệnh",
      "Gỗ nhóm I–II bền chắc — nội thất, đóng tàu, sàn; cây bóng mát đường phố; nhựa làm vecni",
      "—", "—", "Vỏ cây dùng làm thuốc dân gian (đau răng)",
      "Gỗ sao đen 5–8 triệu đ/m³; phổ biến làm cây xanh đô thị nhờ tán đẹp, chịu khói bụi",
      "Quả sao đen có hai cánh dài, khi rụng xoay tròn như chong chóng để phát tán theo gió đi xa",
      ["#3A4A2E", "#8B5E3C"], "https://vi.wikipedia.org/wiki/Sao_%C4%91en"),

    P("po-mu", "Pơ mu", "Fokienia hodginsii", "Fujian cypress · tô hạp hương", "Hoàng đàn (Cupressaceae)",
      "lam-nghiep", "Thông (Pinales)", "Fokienia", "F. hodginsii",
      "Loài cây lá kim quý hiếm, phân bố rừng núi cao Bắc Bộ & Bắc Trung Bộ; có tên trong Sách Đỏ Việt Nam.",
      "Pơ mu là cây gỗ lá kim quý, gỗ thơm nhẹ, màu vàng nâu; hiếm và được bảo tồn ở rừng núi cao.",
      "Cây gỗ lớn thường xanh, lá vảy dẹt", "15–30 m", "Cây lâu năm, sinh trưởng chậm",
      "Ưa nắng, chịu lạnh", "Nhiều — ưa ẩm cao", "Đất chua, mùn dày, pH 5–6, núi cao",
      "Lào Cai, Hà Giang, Nghệ An, Lâm Đồng (núi cao 1500–2500 m)", "Trồng vụ xuân/thu; tái sinh tự nhiên khó",
      "Ưa khí hậu mát ẩm núi cao; sinh trưởng chậm, nhạy cảm với thay đổi môi trường",
      "Gieo hạt (cần xử lý), giâm hom (khó)", "40–50 năm (gỗ quý), rất chậm", "1–1,5 m³ gỗ/ha/năm",
      ls(("Ươm & trồng (che bóng)", "Năm 1–3"), ("Sinh trưởng chậm", "Năm 3–10"),
         ("Tạo gỗ tâm thơm", "Năm 10–30"), ("Khai thác (hạn chế)", "Năm 30–50")),
      "Ít sâu bệnh (khí hậu lạnh); nấm gốc nếu trồng vùng ấm",
      "Gỗ quý nhóm IIA thơm tự nhiên — đồ mỹ nghệ, tủ đựng, tượng; tinh dầu hương liệu",
      "—", "—", "Tinh dầu pơ mu xua côn trùng, làm hương liệu",
      "Gỗ pơ mu hiếm, giá cao; loài được bảo tồn (Sách Đỏ Việt Nam)",
      "Có cây pơ mu cổ thụ ở vùng cao được xác định hơn 1000 năm tuổi — thuộc hàng cây cổ nhất Việt Nam",
      ["#A98D5B", "#5A6B4A"], "https://vi.wikipedia.org/wiki/P%C6%A1_mu"),

    P("sen-mat", "Sến mật", "Madhuca pasquieri", "Sen mat · gỗ sến", "Hồng xiêm (Sapotaceae)",
      "lam-nghiep", "Thạch nam (Ericales)", "Madhuca", "M. pasquieri",
      "Loài gỗ quý bản địa thuộc bộ 'tứ thiết'; phân bố rừng Bắc Bộ, Bắc Trung Bộ (Tam Quy – Thanh Hóa).",
      "Sến mật là một trong 'tứ thiết' (đinh–lim–sến–táu) — gỗ cực cứng, lõi sậm, rất bền với mối mọt.",
      "Cây gỗ lớn, thân tròn thẳng", "15–20 m", "Cây lâu năm, khai thác sau 50–70 năm",
      "Ưa nắng hoàn toàn", "Trung bình đến nhiều", "Đất feralit, đất thịt, thoát nước",
      "Lào Cai, Lạng Sơn, Thanh Hóa (rừng Tam Quy), Quảng Bình", "Trồng đầu mùa mưa; sinh trưởng chậm",
      "Ưa khí hậu nhiệt đới ẩm; cây tái sinh chậm, gỗ tích lũy lâu",
      "Gieo hạt (tỷ lệ nảy mầm thấp)", "50–70 năm (gỗ quý)", "2–2,5 m³ gỗ/ha/năm",
      ls(("Ươm & trồng", "Năm 1–2"), ("Sinh trưởng & tạo lõi", "Năm 2–10"),
         ("Phát triển ổn định", "Năm 10–35"), ("Khai thác gỗ quý", "Năm 35–70")),
      "Sâu đục thân, nấm gỗ",
      "Gỗ 'tứ thiết' cực bền — cột nhà, cầu, bàn ghế, mỹ nghệ; hạt ép dầu",
      "—", "—", "Hạt sến ép dầu thắp & dùng trong dân gian",
      "Gỗ sến 8–15 triệu đ/m³; thuộc nhóm tứ thiết quý của Việt Nam",
      "Gỗ sến chứa nhiều tannin nên kháng mối mọt và nấm mốc vượt trội — dân gian dùng làm cán công cụ",
      ["#2E2A22", "#9C6B30"], "https://vi.wikipedia.org/wiki/S%E1%BA%BFn_m%E1%BA%ADt"),

    P("dau-rai", "Dầu rái", "Dipterocarpus alatus", "Resin tree · dầu nước", "Dầu (Dipterocarpaceae)",
      "lam-nghiep", "Bông (Malvales)", "Dipterocarpus", "D. alatus",
      "Loài đại thụ rừng nhiệt đới Nam Bộ & Tây Nguyên; vừa cho gỗ vừa cho nhựa dầu rái.",
      "Dầu rái là cây gỗ lớn vượt tán rừng, cho gỗ tốt và nhựa dầu rái — từng dùng trám thuyền, làm vecni.",
      "Cây gỗ rất lớn, thân thẳng vút", "30–50 m", "Cây lâu năm, khai thác sau 60–80 năm",
      "Ưa nắng khi lớn, chịu bóng khi nhỏ", "Nhiều — ưa ẩm", "Đất đỏ bazan, phù sa cổ, thoát nước",
      "Đông Nam Bộ (Tây Ninh, Bình Phước), Tây Nguyên", "Trồng đầu mùa mưa; quả có hai cánh dài",
      "Ưa khí hậu nhiệt đới ẩm; cây con cần che bóng, lớn vươn vượt tán",
      "Gieo hạt (khó bảo quản), giâm hom", "60–80 năm (gỗ); trích nhựa khi trưởng thành", "1,5–2 m³ gỗ/ha/năm",
      ls(("Ươm & trồng (che bóng)", "Năm 1–5"), ("Vươn tán", "Năm 5–20"),
         ("Trưởng thành & ra hoa", "Năm 20–50"), ("Khai thác gỗ", "Năm 60–80")),
      "Sâu đục thân, nấm gỗ",
      "Gỗ nhóm I–II — xây dựng, đóng tàu, nội thất; nhựa dầu rái làm vecni, trám thuyền, đốt đèn",
      "—", "—", "Nhựa dầu rái dùng làm chất kết dính, chống thấm truyền thống",
      "Gỗ dầu rái 5–10 triệu đ/m³; nhựa dầu rái là lâm sản truyền thống Nam Bộ",
      "Nhựa cây từng được dân gian dùng làm dầu thắp đèn và trám thuyền — nguồn gốc tên gọi 'dầu rái'",
      ["#6B4A2E", "#C9A227"], "https://vi.wikipedia.org/wiki/D%E1%BA%A7u_r%C3%A1i"),

    P("xoan-ta", "Xoan ta", "Melia azedarach", "Chinaberry · xoan trắng · sầu đông", "Xoan (Meliaceae)",
      "lam-nghiep", "Xoan (Sapindales)", "Melia", "M. azedarach",
      "Cây gỗ mọc nhanh nguồn gốc Á–Úc; trồng rừng kinh tế phổ biến khắp Việt Nam, nhất là Trung Bộ.",
      "Xoan ta là cây trồng rừng mọc nhanh, chu kỳ ngắn 10–15 năm; gỗ nhẹ dễ chế biến, làm nhà, đồ mộc.",
      "Cây gỗ rụng lá mùa đông", "15–20 m", "Cây lâu năm, khai thác sau 10–15 năm",
      "Ưa nắng hoàn toàn", "Trung bình — chịu hạn khá", "Đất thịt thoát nước, thích nghi rộng",
      "Khắp cả nước, nhiều ở Trung Bộ, Tây Nguyên", "Trồng đầu mùa mưa, ra hoa tím tháng 2–4",
      "Dễ tính, mọc nhanh, thích nghi nhiều loại đất; chu kỳ ngắn hợp đầu tư nông hộ",
      "Gieo hạt, giâm hom", "10–15 năm (gỗ)", "5–8 m³ gỗ/ha/năm",
      ls(("Gieo hạt / trồng", "Năm 1"), ("Sinh trưởng rất nhanh", "Năm 1–5"),
         ("Phát triển đường kính", "Năm 5–10"), ("Khai thác", "Năm 10–15")),
      "Sâu ăn lá, sâu đục ngọn, bệnh đốm lá",
      "Gỗ nhóm III mọc nhanh — làm nhà, đồ mộc, bao bì, ván; quả & lá làm thuốc trừ sâu sinh học",
      "—", "—", "Hạt và lá xoan dùng làm thuốc trừ sâu, trị giun (lưu ý độc)",
      "Gỗ xoan ta 2–3 triệu đ/m³; cây trồng rừng kinh tế ngắn ngày phổ biến cho nông hộ",
      "Hạt và lá xoan chứa hoạt chất xua đuổi côn trùng — dân gian lót lá xoan chống mọt cho thóc gạo",
      ["#8B7B9E", "#9C6B30"], "https://vi.wikipedia.org/wiki/Xoan"),

    P("que", "Quế", "Cinnamomum cassia", "Cinnamon · quế đơn", "Long não (Lauraceae)",
      "lam-nghiep", "Long não (Laurales)", "Cinnamomum", "C. cassia",
      "Cây lâm sản ngoài gỗ giá trị cao; trồng nhiều ở Yên Bái (Văn Yên), Quảng Nam, Quảng Ngãi (Trà My).",
      "Quế là cây lấy vỏ và tinh dầu thơm; vừa là gia vị, dược liệu, vừa là lâm sản xuất khẩu chủ lực.",
      "Cây gỗ nhỏ thường xanh, vỏ thơm", "8–15 m", "Cây lâu năm; bóc vỏ sau 8–10 năm",
      "Ưa nắng, chịu bóng nhẹ khi nhỏ", "Trung bình — cần ẩm đều", "Đất feralit, thịt, thoát nước, pH 5,5–7",
      "Yên Bái (Văn Yên), Quảng Nam, Quảng Ngãi (Trà My), Thanh Hóa", "Trồng đầu mùa mưa; bóc vỏ vụ xuân & thu",
      "Ưa khí hậu nhiệt đới ẩm vùng đồi núi; cần đất tơi thoát nước",
      "Gieo hạt (hạt tươi)", "8–10 năm bóc vỏ; tinh dầu từ cành lá sớm hơn", "Vỏ khô 0,5–0,8 tấn/ha/năm",
      ls(("Gieo hạt / trồng", "Năm 1–2"), ("Sinh trưởng thân lá", "Năm 2–5"),
         ("Tích lũy tinh dầu vỏ", "Năm 5–8"), ("Bóc vỏ & chưng tinh dầu", "Năm 8+")),
      "Sâu đục thân, rệp, bệnh đốm lá, tua mực",
      "Vỏ quế làm gia vị & dược liệu; tinh dầu quế hương liệu, dầu gió; lâm sản xuất khẩu",
      "—", "Cay nồng, ngọt ấm đặc trưng", "Quế ấm bụng, kích thích tuần hoàn, trị cảm lạnh (Đông y)",
      "Vỏ quế & tinh dầu xuất khẩu mạnh; quế Văn Yên có chỉ dẫn địa lý",
      "Quế Việt Nam (giống Trà My, Văn Yên) thuộc loại hàm lượng tinh dầu cao bậc nhất thế giới",
      ["#8B3A2A", "#C8794A"], "https://vi.wikipedia.org/wiki/Qu%E1%BA%BF_%C4%91%C6%A1n"),

    P("hoi", "Hồi (Đại hồi)", "Illicium verum", "Star anise · đại hồi · bát giác hương", "Hồi (Schisandraceae)",
      "lam-nghiep", "Hồi (Austrobaileyales)", "Illicium", "I. verum",
      "Cây lâm sản ngoài gỗ đặc sản; trồng chủ yếu ở Lạng Sơn, Cao Bằng, Quảng Ninh.",
      "Hồi là cây lấy quả hình sao 8 cánh chứa tinh dầu thơm; gia vị & dược liệu đặc sản vùng Đông Bắc.",
      "Cây gỗ nhỏ thường xanh", "8–15 m", "Cây lâu năm; cho quả sau 5–8 năm",
      "Ưa sáng vừa, chịu bóng nhẹ", "Nhiều — ưa ẩm cao", "Đất chua, mùn, thoát nước, pH 5–6",
      "Lạng Sơn, Cao Bằng, Quảng Ninh (núi 600–1500 m)", "Ra hoa, quả chín thu 2 vụ (mùa & chiêm)",
      "Ưa khí hậu mát ẩm vùng cao Đông Bắc; sinh trưởng chậm lúc nhỏ",
      "Gieo hạt (khó nảy)", "5–8 năm cho quả", "Quả tươi 3–5 tấn/ha (1 tấn khô)",
      ls(("Ươm & trồng", "Năm 1–2"), ("Sinh trưởng chậm", "Năm 2–4"),
         ("Ra hoa & quả bói", "Năm 5–6"), ("Cho quả ổn định", "Năm 6+")),
      "Sâu ăn lá, bệnh thán thư, nấm đốm lá",
      "Quả hồi làm gia vị (phở, ngũ vị), dược liệu; tinh dầu (axit shikimic) cho dược phẩm",
      "—", "Thơm ngọt ấm đặc trưng", "Hồi ấm bụng, trị đầy hơi, cảm lạnh (Đông y)",
      "Quả hồi & tinh dầu xuất khẩu; nguyên liệu sản xuất thuốc kháng virus (Tamiflu)",
      "Quả hồi là nguồn axit shikimic — nguyên liệu từng dùng sản xuất thuốc cúm Tamiflu",
      ["#8B4A2A", "#C9A227"], "https://vi.wikipedia.org/wiki/%C4%90%E1%BA%A1i_h%E1%BB%93i"),

    P("tram-gio", "Tràm gió", "Melaleuca cajuputi", "Cajuput · tràm lấy dầu", "Sim (Myrtaceae)",
      "lam-nghiep", "Sim (Myrtales)", "Melaleuca", "M. cajuputi",
      "Cây rừng ngập & lâm sản tinh dầu; phân bố rừng U Minh (Cà Mau, Kiên Giang) và Nam Bộ.",
      "Tràm gió là cây rừng tràm cho tinh dầu tràm (cajeput); gắn với rừng U Minh và nghề chưng cất dầu tràm.",
      "Cây gỗ vừa, vỏ bong nhiều lớp mỏng", "15–25 m", "Cây lâu năm; thu lá lấy dầu sau 8–12 năm",
      "Ưa nắng hoàn toàn", "Nhiều — chịu ngập từng phần", "Đất phèn, đất than bùn, ngập nông",
      "U Minh Hạ (Cà Mau), Kiên Giang, Long An, Đồng Tháp", "Trồng đầu mùa mưa; thu lá quanh năm để cất dầu",
      "Chịu được đất phèn, ngập nước nông; là cây giữ rừng ngập, phòng cháy",
      "Gieo hạt, tái sinh tự nhiên", "8–12 năm (dầu); 20–25 năm (gỗ)", "Tinh dầu 40–80 lít/ha/năm",
      ls(("Gieo / tái sinh", "Năm 1–2"), ("Sinh trưởng nhanh", "Năm 2–4"),
         ("Thu lá chưng dầu", "Năm 4–8"), ("Thu ổn định / lấy gỗ", "Năm 8+")),
      "Sâu ăn lá, nấm đốm lá",
      "Tinh dầu tràm (cajeput) làm dầu gió, dầu xoa, kháng khuẩn; gỗ làm cừ tràm xây dựng; giữ rừng ngập",
      "—", "—", "Dầu tràm xoa bóp trị cảm lạnh, sổ mũi cho trẻ; sát khuẩn nhẹ",
      "Tinh dầu tràm & cừ tràm tiêu thụ rộng; gắn sinh kế rừng U Minh",
      "Cừ tràm — thân tràm gió — từng là vật liệu đóng móng nhà phổ biến khắp miền Tây Nam Bộ",
      ["#4A6B3A", "#C9B97A"], "https://vi.wikipedia.org/wiki/Tr%C3%A0m_gi%C3%B3"),
]


def main():
    with open(path, 'r', encoding='utf-8') as f:
        d = json.load(f)
    existing = {c['id'] for c in d['cay']}
    added = 0
    for p in NEW:
        if p['id'] in existing:
            print('SKIP (exists):', p['id'])
            continue
        d['cay'].append(p)
        existing.add(p['id'])
        added += 1
    d['_meta']['capNhat'] = '2026-05-26'
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(d, f, ensure_ascii=False, indent=2)
    # thống kê theo nhóm
    grp = {}
    for c in d['cay']:
        grp[c['nhom']] = grp.get(c['nhom'], 0) + 1
    print(f'Đã thêm {added} cây. Tổng: {len(d["cay"])} cây.')
    for k, v in grp.items():
        print(f'  {k}: {v}')


if __name__ == '__main__':
    main()
