#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Chèn 20 mục Chăn nuôi + Thủy sản vào data/cay.json (idempotent — bỏ qua id đã có).
Chạy: python3 scripts/add-nong-lam-ngu-data.py"""
import json, os
BASE = os.path.join(os.path.dirname(__file__), '..')
PATH = os.path.join(BASE, 'data', 'tu-dien-nong-lam-ngu.json')

CHAN_NUOI = [
 {"id":"bo-sua","ten":"Bò sữa","tenKhoaHoc":"Bos taurus","tenKhac":"Dairy cattle","nhom":"gia-suc",
  "xuatXu":"Thuần hóa từ bò rừng cách đây ~10.000 năm; giống bò sữa cao sản (Holstein Friesian) nhập vào VN từ thập niên 1970.",
  "moTa":"Bò sữa là vật nuôi lấy sữa chủ lực, cho sản lượng sữa cao gấp nhiều lần bò cỏ. Được nuôi tập trung ở các vùng khí hậu mát.",
  "giong":"Holstein Friesian (HF), bò lai HF với bò lai Sind","trongLuong":"450–650 kg (bò cái trưởng thành)",
  "thucAn":"Cỏ tươi, cỏ ủ chua, thức ăn tinh (cám, ngô, khô đậu), khoáng","chuongTrai":"Chuồng thoáng mát, 6–10 m²/con, có khu vắt sữa, làm mát mùa nóng",
  "sinhSan":"Thành thục ~15–18 tháng; mang thai ~9 tháng, đẻ 1 bê/năm","thoiGianNuoi":"Khai thác sữa 5–6 chu kỳ (mỗi chu kỳ ~305 ngày)",
  "sanPham":"Sữa tươi 15–25 lít/ngày; bê giống; phân bón","benhThuongGap":"Viêm vú, lở mồm long móng, tụ huyết trùng, ký sinh trùng đường máu",
  "vungNuoi":"Mộc Châu (Sơn La), Lâm Đồng, Củ Chi, Ba Vì, Nghệ An",
  "giaTri":"Trụ cột ngành sữa nội địa; thu nhập ổn định cho nông hộ liên kết doanh nghiệp.",
  "suThatThuVi":"Một con bò sữa cao sản uống tới 100–150 lít nước/ngày để tạo sữa.",
  "mauDacTrung":["#1c1c1c","#f2efe6"],"nguon":"https://vi.wikipedia.org/wiki/B%C3%B2_s%E1%BB%AFa"},

 {"id":"trau","ten":"Trâu","tenKhoaHoc":"Bubalus bubalis","tenKhac":"Water buffalo · trâu nước","nhom":"gia-suc",
  "xuatXu":"Thuần hóa ở châu Á hơn 5.000 năm; gắn bó với nền nông nghiệp lúa nước Việt Nam.",
  "moTa":"Trâu là sức kéo truyền thống của đồng ruộng VN, nay nuôi chủ yếu lấy thịt và sinh sản. Chịu nóng ẩm và đầm lầy tốt.",
  "giong":"Trâu nội (trâu ngố, trâu gié), trâu Murrah lai","trongLuong":"350–600 kg (trâu trưởng thành)",
  "thucAn":"Cỏ, rơm rạ, thân cây ngô, phụ phẩm nông nghiệp","chuongTrai":"Chuồng đơn giản, cần chỗ đầm tắm; chăn thả đồng cỏ",
  "sinhSan":"Mang thai ~10–11 tháng, đẻ 1 nghé mỗi 1,5–2 năm","thoiGianNuoi":"Nuôi thịt 2–3 năm; trâu cày dùng 8–12 năm",
  "sanPham":"Thịt trâu, sức kéo, da, sừng, phân bón","benhThuongGap":"Lở mồm long móng, tụ huyết trùng, sán lá gan",
  "vungNuoi":"Trung du & miền núi phía Bắc, Bắc Trung Bộ",
  "giaTri":"Thịt trâu giá trị cao; tài sản tích lũy của nông hộ miền núi.",
  "suThatThuVi":"Trâu thích ngâm mình dưới bùn để hạ nhiệt và tránh ruồi muỗi — vì tuyến mồ hôi rất ít.",
  "mauDacTrung":["#3a3a3a","#cdb892"],"nguon":"https://vi.wikipedia.org/wiki/Tr%C3%A2u"},

 {"id":"lon","ten":"Lợn (Heo)","tenKhoaHoc":"Sus domesticus","tenKhac":"Pig · heo","nhom":"gia-suc",
  "xuatXu":"Thuần hóa từ lợn rừng hàng nghìn năm; là vật nuôi lấy thịt phổ biến nhất Việt Nam.",
  "moTa":"Lợn là nguồn thịt chính trong bữa ăn người Việt. Lớn nhanh, tận dụng được nhiều loại thức ăn.",
  "giong":"Lợn ngoại (Yorkshire, Landrace, Duroc), lợn lai, lợn nội (Móng Cái, lợn ỉ)","trongLuong":"90–120 kg khi xuất chuồng",
  "thucAn":"Cám công nghiệp, ngô, cám gạo, rau, phụ phẩm","chuongTrai":"Chuồng sạch, thoáng, nền dễ thoát nước; 0,8–1,2 m²/con thịt",
  "sinhSan":"Mang thai ~114 ngày (3 tháng 3 tuần 3 ngày), 10–14 con/lứa, 2–2,5 lứa/năm","thoiGianNuoi":"Lợn thịt 5–6 tháng",
  "sanPham":"Thịt, mỡ, da, phân; con giống","benhThuongGap":"Dịch tả lợn châu Phi, tai xanh (PRRS), lở mồm long móng, tiêu chảy",
  "vungNuoi":"Khắp cả nước; tập trung Đồng bằng Sông Hồng, Đông Nam Bộ",
  "giaTri":"Chiếm phần lớn sản lượng thịt nội địa; sinh kế của hàng triệu nông hộ.",
  "suThatThuVi":"Lợn nái mang thai đúng '3 tháng 3 tuần 3 ngày' — câu nhà nông hay truyền nhau.",
  "mauDacTrung":["#e8b7a8","#f3e3da"],"nguon":"https://vi.wikipedia.org/wiki/L%E1%BB%A3n_nh%C3%A0"},

 {"id":"de","ten":"Dê","tenKhoaHoc":"Capra hircus","tenKhac":"Goat","nhom":"gia-suc",
  "xuatXu":"Một trong những vật nuôi thuần hóa sớm nhất (~10.000 năm); nuôi rộng ở vùng đồi núi VN.",
  "moTa":"Dê dễ nuôi, ăn tạp, leo trèo giỏi, thích hợp vùng đồi gò khô hạn; nuôi lấy thịt và sữa.",
  "giong":"Dê cỏ (Bách Thảo), dê Boer, dê Saanen (lấy sữa)","trongLuong":"30–50 kg (dê thịt), dê Boer tới 70–90 kg",
  "thucAn":"Lá cây, cỏ, cây bụi, phụ phẩm; thích thức ăn thô xanh","chuongTrai":"Chuồng sàn cao ráo, thoáng; cần sân chơi, tránh ẩm ướt",
  "sinhSan":"Mang thai ~5 tháng, 1–3 con/lứa, ~1,5 lứa/năm","thoiGianNuoi":"Dê thịt 7–10 tháng",
  "sanPham":"Thịt dê, sữa dê, da","benhThuongGap":"Tụ huyết trùng, viêm loét miệng, ký sinh trùng, chướng hơi dạ cỏ",
  "vungNuoi":"Ninh Thuận, Bình Thuận, miền núi phía Bắc, Tây Nguyên",
  "giaTri":"Vốn ít, quay vòng nhanh; thịt và sữa dê được ưa chuộng.",
  "suThatThuVi":"Đồng tử mắt dê hình chữ nhật nằm ngang, giúp quan sát gần 320° để cảnh giác thú dữ.",
  "mauDacTrung":["#cbb89a","#f2ece0"],"nguon":"https://vi.wikipedia.org/wiki/D%C3%AA_nh%C3%A0"},

 {"id":"ga","ten":"Gà","tenKhoaHoc":"Gallus gallus domesticus","tenKhac":"Chicken","nhom":"gia-cam",
  "xuatXu":"Thuần hóa từ gà rừng lông đỏ ở Đông Nam Á; vật nuôi lấy thịt – trứng phổ biến nhất thế giới.",
  "moTa":"Gà cung cấp thịt và trứng, nuôi từ nông hộ nhỏ tới trang trại công nghiệp. Vòng đời ngắn, quay vòng nhanh.",
  "giong":"Gà ta (gà ri, gà nòi), gà công nghiệp (lông trắng), gà lai, gà thả vườn","trongLuong":"1,5–3 kg (gà thịt)",
  "thucAn":"Cám công nghiệp, ngô, thóc, rau, côn trùng","chuongTrai":"Chuồng kín hoặc thả vườn; cần khô ráo, thoáng, đủ sáng",
  "sinhSan":"Đẻ trứng sau ~5–6 tháng tuổi; gà công nghiệp đẻ ~250–300 trứng/năm","thoiGianNuoi":"Gà công nghiệp 42–50 ngày; gà ta 3–4 tháng",
  "sanPham":"Thịt, trứng, lông, phân","benhThuongGap":"Cúm gia cầm (H5N1), Newcastle (gà rù), Gumboro, tụ huyết trùng",
  "vungNuoi":"Khắp cả nước",
  "giaTri":"Nguồn đạm rẻ và phổ biến nhất; sinh kế nông hộ.",
  "suThatThuVi":"Gà có thể nhớ và phân biệt hơn 100 khuôn mặt (cả người lẫn gà) khác nhau.",
  "mauDacTrung":["#b5402e","#e8c15a"],"nguon":"https://vi.wikipedia.org/wiki/G%C3%A0_nh%C3%A0"},

 {"id":"vit","ten":"Vịt","tenKhoaHoc":"Anas platyrhynchos domesticus","tenKhac":"Domestic duck","nhom":"gia-cam",
  "xuatXu":"Thuần hóa từ vịt trời; gắn với canh tác lúa nước, nuôi thả đồng sau mùa gặt.",
  "moTa":"Vịt nuôi lấy thịt và trứng, đặc biệt phù hợp vùng sông nước Đồng bằng Sông Cửu Long; tận dụng thóc rơi, ốc, cá nhỏ.",
  "giong":"Vịt cỏ, vịt bầu, vịt siêu thịt (CV Super M), vịt siêu trứng (Khaki Campbell)","trongLuong":"1,8–3,2 kg (vịt thịt)",
  "thucAn":"Thóc, cám, ốc, cá tạp, rau, bèo; chăn thả đồng","chuongTrai":"Cần ao/mương để bơi; chuồng úm khô ráo cho vịt con",
  "sinhSan":"Đẻ sau ~5 tháng; vịt siêu trứng ~250–300 trứng/năm","thoiGianNuoi":"Vịt thịt 45–60 ngày",
  "sanPham":"Thịt, trứng (trứng vịt lộn, trứng muối), lông","benhThuongGap":"Dịch tả vịt, cúm gia cầm, viêm gan vịt",
  "vungNuoi":"Đồng bằng Sông Cửu Long, Đồng bằng Sông Hồng",
  "giaTri":"Mô hình 'lúa – vịt' giúp diệt sâu ốc, tăng thu nhập kép cho nông dân.",
  "suThatThuVi":"Lông vịt không thấm nước nhờ lớp dầu tự tiết từ tuyến phao câu — vịt thường rỉa lông để bôi dầu này.",
  "mauDacTrung":["#2f6b4f","#e8dcc0"],"nguon":"https://vi.wikipedia.org/wiki/V%E1%BB%8Bt_nh%C3%A0"},

 {"id":"ngan","ten":"Ngan","tenKhoaHoc":"Cairina moschata","tenKhac":"Muscovy duck · vịt xiêm","nhom":"gia-cam",
  "xuatXu":"Có nguồn gốc Nam Mỹ, du nhập VN lâu đời; miền Nam gọi là 'vịt xiêm'.",
  "moTa":"Ngan to con hơn vịt, thịt nhiều nạc, ít mỡ; nuôi lấy thịt là chính. Bơi ít hơn vịt thường.",
  "giong":"Ngan nội, ngan Pháp (R51, R71)","trongLuong":"Ngan đực 4–5 kg, ngan cái 2,5–3 kg",
  "thucAn":"Cám, thóc, ngô, rau xanh, ốc","chuongTrai":"Chuồng khô thoáng, có sân; cần ít nước hơn vịt",
  "sinhSan":"Mỗi lứa 12–18 trứng, ấp ~35 ngày (lâu hơn vịt)","thoiGianNuoi":"Ngan thịt 70–90 ngày",
  "sanPham":"Thịt nạc, trứng","benhThuongGap":"Cúm gia cầm, dịch tả, viêm gan",
  "vungNuoi":"Khắp cả nước, nhiều ở miền Bắc & miền Nam",
  "giaTri":"Thịt ngan được ưa chuộng (cháo ngan, ngan om); giá cao hơn vịt.",
  "suThatThuVi":"Con lai giữa ngan và vịt gọi là 'con mula' — to khỏe nhưng không sinh sản được.",
  "mauDacTrung":["#222222","#d8453a"],"nguon":"https://vi.wikipedia.org/wiki/Ngan_b%C6%B0%E1%BB%9Bu_m%C5%A9i"},

 {"id":"chim-cut","ten":"Chim cút","tenKhoaHoc":"Coturnix japonica","tenKhac":"Japanese quail","nhom":"gia-cam",
  "xuatXu":"Thuần hóa ở Nhật Bản; nuôi công nghiệp lấy trứng & thịt, du nhập VN mạnh từ thập niên 1970.",
  "moTa":"Chim cút nhỏ, đẻ trứng sớm và nhiều, vòng đời ngắn; nuôi mật độ cao trên lồng tầng, vốn ít.",
  "giong":"Cút Nhật (lấy trứng), cút Pharaoh (lấy thịt)","trongLuong":"120–150 g/con",
  "thucAn":"Cám viên giàu đạm, ngô, tấm","chuongTrai":"Lồng nhiều tầng, kín gió, ấm; mật độ 50–60 con/m²",
  "sinhSan":"Đẻ trứng từ ~40–45 ngày tuổi; ~250–300 trứng/năm","thoiGianNuoi":"Cút thịt 35–40 ngày",
  "sanPham":"Trứng cút, thịt cút","benhThuongGap":"Newcastle, thương hàn, tiêu chảy, ngộ độc thức ăn",
  "vungNuoi":"Đông Nam Bộ, Đồng bằng Sông Cửu Long",
  "giaTri":"Vốn nhỏ, thu hồi nhanh; trứng cút là món ăn bình dân phổ biến.",
  "suThatThuVi":"Cút mái bắt đầu đẻ chỉ sau ~6 tuần tuổi — thuộc loại gia cầm thành thục nhanh nhất.",
  "mauDacTrung":["#8a6f4b","#e3d6bd"],"nguon":"https://vi.wikipedia.org/wiki/Chim_c%C3%BAt"},

 {"id":"ong-mat","ten":"Ong mật","tenKhoaHoc":"Apis cerana / Apis mellifera","tenKhac":"Honey bee","nhom":"vat-nuoi-khac",
  "xuatXu":"Ong nội (Apis cerana) bản địa châu Á; ong ngoại (Apis mellifera) nhập nuôi lấy mật quy mô lớn.",
  "moTa":"Ong mật được nuôi lấy mật, phấn hoa, sữa ong chúa và để thụ phấn cây trồng. Sống thành đàn có tổ chức cao.",
  "giong":"Ong nội Apis cerana, ong Ý Apis mellifera","trongLuong":"Một đàn 20.000–60.000 con (ong thợ, ong chúa, ong đực)",
  "thucAn":"Mật hoa và phấn hoa tự nhiên; cho ăn bổ sung đường khi thiếu hoa","chuongTrai":"Thùng nuôi ong (cầu ong) đặt nơi gần nguồn hoa, thoáng mát",
  "sinhSan":"Ong chúa đẻ 1.000–2.000 trứng/ngày; đàn nhân lên bằng cách chia đàn","thoiGianNuoi":"Quay mật theo mùa hoa (nhiều đợt/năm)",
  "sanPham":"Mật ong, phấn hoa, sữa ong chúa, sáp ong, keo ong","benhThuongGap":"Thối ấu trùng, ve ký sinh (Varroa), bệnh bào tử",
  "vungNuoi":"Tây Nguyên, Đông Nam Bộ, miền núi phía Bắc (theo mùa hoa cà phê, nhãn, vải)",
  "giaTri":"Mật ong xuất khẩu; ong thụ phấn làm tăng năng suất cây trồng nhiều lần.",
  "suThatThuVi":"Để làm ra 1 kg mật, đàn ong phải bay tổng quãng đường tương đương vài vòng quanh Trái Đất.",
  "mauDacTrung":["#caa12f","#f0dca0"],"nguon":"https://vi.wikipedia.org/wiki/Ong_m%E1%BA%ADt"},

 {"id":"tho","ten":"Thỏ","tenKhoaHoc":"Oryctolagus cuniculus","tenKhac":"Domestic rabbit","nhom":"vat-nuoi-khac",
  "xuatXu":"Thuần hóa từ thỏ rừng châu Âu; nuôi lấy thịt, lông và làm động vật thí nghiệm.",
  "moTa":"Thỏ sinh sản rất nhanh, ăn rau cỏ, vốn đầu tư thấp; thịt nạc giàu đạm, ít cholesterol.",
  "giong":"Thỏ New Zealand trắng, thỏ California, thỏ nội","trongLuong":"2,5–5 kg (thỏ thịt trưởng thành)",
  "thucAn":"Rau xanh, cỏ, lá, cám viên; cần nước sạch","chuongTrai":"Lồng sàn lưới khô ráo, thoáng, tránh nóng và gió lùa",
  "sinhSan":"Mang thai ~30 ngày, 6–9 con/lứa, tới 6–7 lứa/năm","thoiGianNuoi":"Thỏ thịt 3–3,5 tháng",
  "sanPham":"Thịt thỏ, lông, da","benhThuongGap":"Bại huyết (xuất huyết thỏ), ghẻ, cầu trùng, tiêu chảy",
  "vungNuoi":"Khắp cả nước (nông hộ nhỏ)",
  "giaTri":"Quay vòng vốn nhanh nhờ sinh sản mạnh; phù hợp nuôi gia đình.",
  "suThatThuVi":"Một cặp thỏ có thể sinh ra hàng trăm con cháu trong một năm — biểu tượng của sự sinh sôi.",
  "mauDacTrung":["#9c9690","#efe9e0"],"nguon":"https://vi.wikipedia.org/wiki/Th%E1%BB%8F_nh%C3%A0"},
]

THUY_SAN = [
 {"id":"ca-tra","ten":"Cá tra","tenKhoaHoc":"Pangasius hypophthalmus","tenKhac":"Striped catfish","nhom":"ca-nuoi",
  "xuatXu":"Cá da trơn bản địa lưu vực sông Mekong; trở thành thủy sản xuất khẩu chủ lực của VN.",
  "moTa":"Cá tra nuôi ao/bè cho năng suất rất cao, thịt trắng; là mặt hàng xuất khẩu tỷ đô của Đồng bằng Sông Cửu Long.",
  "moiTruongNuoc":"Nước ngọt (sông, ao); chịu được nước thiếu oxy nhờ hô hấp khí trời","nhietDoPH":"26–30°C, pH 6,5–8",
  "thucAn":"Thức ăn viên công nghiệp giàu đạm; cám, phụ phẩm","hinhThucNuoi":"Ao đất thâm canh, mật độ 20–40 con/m²; lồng bè",
  "thuHoach":"6–8 tháng, đạt 1–1,5 kg/con","sanLuong":"200–400 tấn/ha/vụ (ao thâm canh)",
  "sanPham":"Phi lê đông lạnh xuất khẩu, cá thịt, bột cá","benhThuongGap":"Gan thận mủ, xuất huyết, trắng gan trắng mang, ký sinh trùng",
  "vungNuoi":"An Giang, Đồng Tháp, Cần Thơ, Vĩnh Long (Đồng bằng Sông Cửu Long)",
  "giaTri":"Một trong những mặt hàng thủy sản xuất khẩu lớn nhất VN, đi hơn 140 thị trường.",
  "suThatThuVi":"Cá tra có cơ quan hô hấp phụ, ngoi lên đớp khí trời nên sống được ở ao nước rất đục, ít oxy.",
  "mauDacTrung":["#8a96a0","#e3e7ea"],"nguon":"https://vi.wikipedia.org/wiki/C%C3%A1_tra"},

 {"id":"ca-ro-phi","ten":"Cá rô phi","tenKhoaHoc":"Oreochromis niloticus","tenKhac":"Nile tilapia","nhom":"ca-nuoi",
  "xuatXu":"Nguồn gốc châu Phi, nhập vào VN nuôi rộng rãi nhờ dễ nuôi, lớn nhanh.",
  "moTa":"Cá rô phi ăn tạp, chịu đựng tốt, thịt chắc ít xương; nuôi ao, lồng và cả ruộng lúa.",
  "moiTruongNuoc":"Nước ngọt và lợ nhẹ","nhietDoPH":"25–32°C, pH 6,5–8,5",
  "thucAn":"Ăn tạp: cám, bèo, tảo, phụ phẩm, thức ăn viên","hinhThucNuoi":"Ao, lồng bè, mật độ 5–10 con/m²",
  "thuHoach":"4–6 tháng, đạt 0,5–0,8 kg/con","sanLuong":"15–25 tấn/ha/vụ",
  "sanPham":"Cá thịt, phi lê xuất khẩu","benhThuongGap":"Liên cầu khuẩn (Streptococcus), nấm, ký sinh trùng",
  "vungNuoi":"Khắp cả nước; nhiều ở ĐBSCL, miền Bắc",
  "giaTri":"Cá thịt phổ thông giá rẻ; tiềm năng xuất khẩu phi lê tăng nhanh.",
  "suThatThuVi":"Cá rô phi mẹ ngậm trứng và cá con trong miệng để bảo vệ — gọi là tập tính 'ấp miệng'.",
  "mauDacTrung":["#6b7d8a","#dfe4e6"],"nguon":"https://vi.wikipedia.org/wiki/C%C3%A1_r%C3%B4_phi"},

 {"id":"ca-loc","ten":"Cá lóc","tenKhoaHoc":"Channa striata","tenKhac":"Snakehead · cá quả","nhom":"ca-nuoi",
  "xuatXu":"Cá nước ngọt bản địa phổ biến khắp ao đồng VN; nay nuôi thâm canh thương phẩm.",
  "moTa":"Cá lóc dữ, ăn động vật, thịt ngon ít xương dăm; chịu được nước tù nhờ hô hấp khí trời.",
  "moiTruongNuoc":"Nước ngọt (ao, ruộng, mương)","nhietDoPH":"26–32°C, pH 6,5–8",
  "thucAn":"Cá tạp, thức ăn viên đạm cao; tập tính ăn thịt","hinhThucNuoi":"Ao, bể lót bạt, vèo; mật độ cao 40–60 con/m²",
  "thuHoach":"5–7 tháng, đạt 0,5–1 kg/con","sanLuong":"Rất cao trong bể bạt thâm canh",
  "sanPham":"Cá thịt tươi, khô cá lóc, chả cá","benhThuongGap":"Lở loét, nấm thủy mi, ký sinh trùng, gan thận mủ",
  "vungNuoi":"Đồng bằng Sông Cửu Long (An Giang, Đồng Tháp, Trà Vinh)",
  "giaTri":"Đặc sản đồng quê; khô cá lóc và mắm là sản phẩm giá trị cao.",
  "suThatThuVi":"Cá lóc trườn được trên cạn và sống nhiều giờ ngoài nước để di chuyển sang vùng nước khác.",
  "mauDacTrung":["#4e5a3a","#d8d3bd"],"nguon":"https://vi.wikipedia.org/wiki/C%C3%A1_l%C3%B3c"},

 {"id":"ca-dieu-hong","ten":"Cá điêu hồng","tenKhoaHoc":"Oreochromis sp.","tenKhac":"Red tilapia · cá rô phi đỏ","nhom":"ca-nuoi",
  "xuatXu":"Dòng rô phi lai màu đỏ hồng, được chọn tạo và nuôi phổ biến ở VN.",
  "moTa":"Cá điêu hồng thịt trắng, màu đỏ đẹp bắt mắt nên dễ bán; nuôi lồng bè trên sông là chính.",
  "moiTruongNuoc":"Nước ngọt và lợ nhẹ","nhietDoPH":"25–32°C, pH 6,5–8,5",
  "thucAn":"Thức ăn viên, cám, phụ phẩm","hinhThucNuoi":"Lồng bè trên sông, ao; mật độ 50–80 con/m³ lồng",
  "thuHoach":"4–6 tháng, đạt 0,5–0,9 kg/con","sanLuong":"Cao trong nuôi lồng bè",
  "sanPham":"Cá thịt tươi (chợ, nhà hàng)","benhThuongGap":"Liên cầu khuẩn, xuất huyết, ký sinh trùng",
  "vungNuoi":"Sông Tiền, sông Hậu, hồ thủy lợi miền Trung & Nam",
  "giaTri":"Cá thương phẩm tiêu thụ nội địa mạnh nhờ màu đẹp, thịt ngon.",
  "suThatThuVi":"Màu hồng đỏ là do đột biến gen sắc tố — không phải nhuộm như nhiều người lầm tưởng.",
  "mauDacTrung":["#c0573f","#f0d9cf"],"nguon":"https://vi.wikipedia.org/wiki/C%C3%A1_di%C3%AAu_h%E1%BB%93ng"},

 {"id":"tom-the","ten":"Tôm thẻ chân trắng","tenKhoaHoc":"Litopenaeus vannamei","tenKhac":"Whiteleg shrimp","nhom":"giap-xac",
  "xuatXu":"Nguồn gốc Đông Thái Bình Dương (châu Mỹ), nhập nuôi VN từ ~2000, nay là tôm nuôi chủ lực.",
  "moTa":"Tôm thẻ lớn nhanh, nuôi mật độ cao, thời gian ngắn; là mặt hàng thủy sản xuất khẩu hàng đầu.",
  "moiTruongNuoc":"Nước lợ và mặn (ao ven biển)","nhietDoPH":"25–32°C, độ mặn 5–25‰, pH 7,5–8,5",
  "thucAn":"Thức ăn viên đạm cao chuyên cho tôm","hinhThucNuoi":"Ao bạt/ao đất thâm canh, mật độ 80–300 con/m²; có sục khí",
  "thuHoach":"70–100 ngày, đạt 40–100 con/kg","sanLuong":"10–40 tấn/ha/vụ (siêu thâm canh)",
  "sanPham":"Tôm đông lạnh xuất khẩu, tôm tươi","benhThuongGap":"Đốm trắng, hoại tử gan tụy cấp (EMS), phân trắng, đỏ thân",
  "vungNuoi":"Cà Mau, Bạc Liêu, Sóc Trăng, Trà Vinh, ven biển miền Trung",
  "giaTri":"Trụ cột kim ngạch xuất khẩu thủy sản VN (cùng cá tra).",
  "suThatThuVi":"Tôm lột xác để lớn — mỗi lần lột vỏ cũ, cơ thể tăng kích thước rồi vỏ mới cứng dần lại.",
  "mauDacTrung":["#cdbfa6","#eee6d6"],"nguon":"https://vi.wikipedia.org/wiki/T%C3%B4m_th%E1%BA%BB_ch%C3%A2n_tr%E1%BA%AFng"},

 {"id":"tom-su","ten":"Tôm sú","tenKhoaHoc":"Penaeus monodon","tenKhac":"Giant tiger prawn","nhom":"giap-xac",
  "xuatXu":"Tôm bản địa vùng Ấn Độ Dương – Tây Thái Bình Dương; tôm nuôi truyền thống của VN trước tôm thẻ.",
  "moTa":"Tôm sú con to, giá cao, vằn như hổ; nuôi quảng canh và thâm canh, hợp mô hình tôm – rừng, tôm – lúa.",
  "moiTruongNuoc":"Nước lợ và mặn","nhietDoPH":"26–32°C, độ mặn 10–25‰, pH 7,5–8,5",
  "thucAn":"Thức ăn viên, mùn bã, sinh vật đáy","hinhThucNuoi":"Quảng canh, quảng canh cải tiến, thâm canh; mật độ 5–30 con/m²",
  "thuHoach":"4–5 tháng, đạt 20–40 con/kg (con to)","sanLuong":"Thấp hơn tôm thẻ nhưng giá bán cao hơn",
  "sanPham":"Tôm đông lạnh xuất khẩu (cỡ lớn giá cao)","benhThuongGap":"Đốm trắng, đầu vàng, MBV, hoại tử gan tụy",
  "vungNuoi":"Cà Mau, Bạc Liêu, Kiên Giang (mô hình tôm – rừng ngập mặn)",
  "giaTri":"Tôm cỡ lớn giá trị cao; mô hình tôm – rừng thân thiện sinh thái, có chứng nhận sạch.",
  "suThatThuVi":"Tôm sú có thể đạt kích thước rất lớn — con cái dài tới hơn 30 cm, nặng 200–300 g.",
  "mauDacTrung":["#3a3a4a","#c9b89a"],"nguon":"https://vi.wikipedia.org/wiki/T%C3%B4m_s%C3%BA"},

 {"id":"cua-bien","ten":"Cua biển","tenKhoaHoc":"Scylla serrata","tenKhac":"Mud crab · cua bùn","nhom":"giap-xac",
  "xuatXu":"Cua bản địa vùng rừng ngập mặn ven biển VN; nuôi và khai thác tự nhiên.",
  "moTa":"Cua biển sống vùng nước lợ, thịt và gạch ngon, giá trị cao; nuôi trong ao, vuông tôm hoặc rừng ngập mặn.",
  "moiTruongNuoc":"Nước lợ ven biển, rừng ngập mặn","nhietDoPH":"25–30°C, độ mặn 10–25‰",
  "thucAn":"Cá tạp, nhuyễn thể, thức ăn tươi","hinhThucNuoi":"Nuôi ao/vuông, nuôi cua trong hộp (cua cốm/cua lột), mật độ thấp",
  "thuHoach":"3–5 tháng, đạt 250–500 g/con","sanLuong":"Thấp, nuôi xen canh là chính",
  "sanPham":"Cua thịt, cua gạch, cua cốm (cua lột)","benhThuongGap":"Ký sinh trùng, bệnh đốm, mềm vỏ do thiếu khoáng",
  "vungNuoi":"Cà Mau, Bạc Liêu, Trà Vinh, Bến Tre (vùng rừng ngập mặn)",
  "giaTri":"Đặc sản giá cao; cua Cà Mau là thương hiệu nổi tiếng.",
  "suThatThuVi":"Cua phải lột vỏ để lớn; ngay sau khi lột, cua mềm toàn thân — đó chính là món 'cua lột' đắt tiền.",
  "mauDacTrung":["#5a4632","#c8a06a"],"nguon":"https://vi.wikipedia.org/wiki/Cua_xanh"},

 {"id":"ngheu","ten":"Nghêu","tenKhoaHoc":"Meretrix lyrata","tenKhac":"Hard clam · ngao","nhom":"thuy-san-khac",
  "xuatXu":"Nhuyễn thể hai mảnh vỏ bản địa vùng bãi triều ven biển VN.",
  "moTa":"Nghêu sống vùi trong cát bãi triều, lọc tảo phù du để ăn nên không cần cho ăn; nuôi bãi cho sản lượng lớn, sạch.",
  "moiTruongNuoc":"Nước mặn – lợ, bãi triều cát ven biển","nhietDoPH":"26–30°C, độ mặn 15–25‰",
  "thucAn":"Lọc tảo và mùn hữu cơ trong nước (không cho ăn)","hinhThucNuoi":"Thả giống trên bãi triều, quây lưới giữ; mật độ 200–500 con/m²",
  "thuHoach":"10–14 tháng, đạt 40–60 con/kg","sanLuong":"15–25 tấn/ha",
  "sanPham":"Nghêu thịt, nghêu sống xuất khẩu","benhThuongGap":"Chết hàng loạt do nắng nóng, độ mặn đột biến, ô nhiễm bãi",
  "vungNuoi":"Bến Tre, Tiền Giang, Trà Vinh, Nam Định, Thái Bình",
  "giaTri":"Nghêu Bến Tre đạt chứng nhận MSC (khai thác bền vững) — xuất khẩu EU.",
  "suThatThuVi":"Nghêu là 'máy lọc nước' tự nhiên — mỗi con lọc nhiều lít nước biển mỗi ngày để bắt tảo.",
  "mauDacTrung":["#b8a888","#efe8d6"],"nguon":"https://vi.wikipedia.org/wiki/Ngh%C3%AAu"},

 {"id":"hau","ten":"Hàu","tenKhoaHoc":"Crassostrea sp.","tenKhac":"Oyster","nhom":"thuy-san-khac",
  "xuatXu":"Nhuyễn thể hai mảnh vỏ bám đá vùng cửa sông ven biển; nuôi treo giàn phổ biến.",
  "moTa":"Hàu lọc nước để ăn, bám vào giá thể; nuôi treo dây/giàn cho năng suất cao, giàu kẽm và đạm.",
  "moiTruongNuoc":"Nước lợ – mặn, vùng cửa sông ven biển","nhietDoPH":"25–30°C, độ mặn 10–25‰",
  "thucAn":"Lọc tảo phù du và mùn hữu cơ (không cho ăn)","hinhThucNuoi":"Nuôi treo dây, giàn bè, đóng cọc; bám trên giá thể",
  "thuHoach":"6–10 tháng","sanLuong":"Cao theo giàn treo",
  "sanPham":"Hàu sống, hàu thịt, hàu sữa","benhThuongGap":"Chết do ô nhiễm, độ mặn thay đổi, ký sinh",
  "vungNuoi":"Quảng Ninh, Khánh Hòa, Bến Tre, Cần Giờ (TP.HCM)",
  "giaTri":"Đặc sản giàu dinh dưỡng (kẽm cao); vốn ít vì không tốn thức ăn.",
  "suThatThuVi":"Hàu có thể thay đổi giới tính qua các mùa sinh sản trong đời.",
  "mauDacTrung":["#8d8473","#e8e2d2"],"nguon":"https://vi.wikipedia.org/wiki/H%C3%A0u"},

 {"id":"ech","ten":"Ếch","tenKhoaHoc":"Hoplobatrachus rugulosus","tenKhac":"Frog · ếch đồng","nhom":"thuy-san-khac",
  "xuatXu":"Ếch đồng bản địa; nay nuôi thương phẩm thay cho đánh bắt tự nhiên.",
  "moTa":"Ếch nuôi bể/vèo cho thịt trắng, ít mỡ, lớn nhanh; ăn thức ăn viên, dễ nuôi mật độ cao.",
  "moiTruongNuoc":"Nước ngọt; cần chỗ cạn để ếch lên cạn","nhietDoPH":"25–32°C, pH 6,5–8",
  "thucAn":"Thức ăn viên nổi đạm cao; cá tạp","hinhThucNuoi":"Bể lót bạt, vèo lưới, mật độ 60–120 con/m²",
  "thuHoach":"2,5–3,5 tháng, đạt 4–6 con/kg","sanLuong":"Cao trong bể thâm canh",
  "sanPham":"Ếch thịt (đùi ếch), ếch giống","benhThuongGap":"Trướng hơi, lở loét, mù mắt, đường ruột",
  "vungNuoi":"Đồng bằng Sông Cửu Long, một số tỉnh miền Bắc",
  "giaTri":"Thịt ếch được ưa chuộng; vốn ít, quay vòng nhanh.",
  "suThatThuVi":"Ếch trải qua biến thái hoàn toàn: từ nòng nọc thở bằng mang dưới nước thành ếch thở bằng phổi trên cạn.",
  "mauDacTrung":["#5d6b3a","#d6d6bd"],"nguon":"https://vi.wikipedia.org/wiki/%E1%BA%BCch_%C4%91%E1%BB%93ng"},
]

def main():
    data = json.load(open(PATH, encoding='utf-8'))
    existing = {c['id'] for c in data['cay']}
    added = 0
    for lv, recs in (('chan-nuoi', CHAN_NUOI), ('thuy-san', THUY_SAN)):
        for rec in recs:
            if rec['id'] in existing:
                print('SKIP (exists):', rec['id']); continue
            rec['linhVuc'] = lv
            rec['anh'] = f"img/{rec['id']}.jpg"
            data['cay'].append(rec); added += 1
    data['_meta']['capNhat'] = '2026-05-27'
    json.dump(data, open(PATH,'w',encoding='utf-8'), ensure_ascii=False, indent=2)
    print(f'Added {added} mục. Tổng: {len(data["cay"])} mục.')

if __name__ == '__main__':
    main()
