#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Chèn 30 mục mở rộng lên 150 loài vào data/cay.json (idempotent — bỏ qua id đã có).
Cây dùng schema thực vật; chăn nuôi & thủy sản dùng schema riêng. python3 scripts/add-expand-150-data.py"""
import json, os
BASE = os.path.join(os.path.dirname(__file__), '..')
PATH = os.path.join(BASE, 'data', 'tu-dien-nong-lam-ngu.json')

# ===== TRỒNG TRỌT (+4) =====
TRONG_TROT = [
 {"id":"mong-toi","ten":"Mồng tơi","tenKhoaHoc":"Basella alba","tenKhac":"Malabar spinach","nhom":"rau",
  "ho":"Mồng tơi (Basellaceae)","phanLoai":{"bo":"Cẩm chướng (Caryophyllales)","ho":"Mồng tơi (Basellaceae)","chi":"Basella","loai":"B. alba"},
  "moTa":"Rau mồng tơi là loại rau ăn lá dây leo quen thuộc mùa hè, lá dày nhớt, mát, dễ trồng quanh nhà.",
  "hinhThai":"Dây leo thân mềm màu xanh hoặc tím, lá đơn hình tim dày mọng, hoa nhỏ màu hồng tím, quả mọng đen.",
  "loaiThan":"Dây leo thân thảo","chieuCao":"Leo dài 2–4 m","chuKy":"Cây hàng năm","anhSang":"Ưa nắng, chịu bán râm",
  "nuoc":"Ưa ẩm, tưới đều","loaiDat":"Đất tơi xốp, giàu mùn","vungTrong":"Khắp cả nước, trồng quanh vườn nhà",
  "nhanGiong":"Gieo hạt hoặc giâm cành","thoiGianThuHoach":"30–45 ngày, hái nhiều đợt","nangSuat":"Thu liên tục trong vụ",
  "giaTri":"Rau mát giàu chất nhầy, vitamin và sắt; món canh giải nhiệt mùa hè.","boPhanDung":"Lá và đọt non làm rau ăn; nấu canh, luộc.",
  "xuatXu":"Có nguồn gốc nhiệt đới châu Á, trồng lâu đời ở Việt Nam.","suThatThuVi":"Chất nhầy trong mồng tơi giúp nhuận tràng, dân gian dùng làm rau mát cho người nóng trong.",
  "mauDacTrung":["#3f6b3a","#7a2e5a"],"nguon":"https://vi.wikipedia.org/wiki/M%E1%BB%93ng_t%C6%A1i"},
 {"id":"rau-den","ten":"Rau dền","tenKhoaHoc":"Amaranthus tricolor","tenKhac":"Amaranth","nhom":"rau",
  "ho":"Dền (Amaranthaceae)","phanLoai":{"bo":"Cẩm chướng (Caryophyllales)","ho":"Dền (Amaranthaceae)","chi":"Amaranthus","loai":"A. tricolor"},
  "moTa":"Rau dền là rau ăn lá mùa hè phổ biến, có dền xanh và dền đỏ, nấu canh ngọt mát.",
  "hinhThai":"Cây thân thảo đứng, lá đơn hình trứng màu xanh hoặc đỏ tía, cụm hoa nhỏ dạng bông.",
  "loaiThan":"Cây thân thảo","chieuCao":"30–80 cm","chuKy":"Cây hàng năm","anhSang":"Ưa nắng",
  "nuoc":"Ưa ẩm vừa","loaiDat":"Đất tơi xốp thoát nước","vungTrong":"Khắp cả nước",
  "nhanGiong":"Gieo hạt","thoiGianThuHoach":"25–35 ngày","nangSuat":"Cao, mau thu",
  "giaTri":"Rau mát giàu sắt, canxi và chất xơ; dền đỏ cho nước canh màu hồng đẹp.","boPhanDung":"Thân lá non làm rau; luộc, nấu canh.",
  "xuatXu":"Có nguồn gốc nhiệt đới, trồng phổ biến ở châu Á.","suThatThuVi":"Hạt rau dền (amaranth) là loại 'siêu hạt' giàu đạm, từng là lương thực của người Aztec.",
  "mauDacTrung":["#7a2230","#4f7a34"],"nguon":"https://vi.wikipedia.org/wiki/Chi_D%E1%BB%81n"},
 {"id":"hanh-tim","ten":"Hành tím","tenKhoaHoc":"Allium ascalonicum","tenKhac":"Shallot","nhom":"gia-vi",
  "ho":"Hành (Amaryllidaceae)","phanLoai":{"bo":"Măng tây (Asparagales)","ho":"Hành (Amaryllidaceae)","chi":"Allium","loai":"A. ascalonicum"},
  "moTa":"Hành tím là gia vị đặc trưng của bếp Việt — củ nhỏ màu tím đỏ, thơm nồng, dùng phi thơm và làm hành phi.",
  "hinhThai":"Cây thân thảo, củ nhỏ hình trứng vỏ tím đỏ mọc thành chùm, lá hình ống rỗng màu xanh.",
  "loaiThan":"Cây thân hành","chieuCao":"20–40 cm","chuKy":"Cây hàng năm","anhSang":"Ưa nắng",
  "nuoc":"Vừa phải, tránh úng","loaiDat":"Đất cát pha, thoát nước tốt","vungTrong":"Sóc Trăng, Ninh Thuận (Vĩnh Châu nổi tiếng)",
  "nhanGiong":"Trồng bằng củ","thoiGianThuHoach":"55–70 ngày","nangSuat":"15–20 tấn/ha",
  "giaTri":"Gia vị thiết yếu; hành phi và hành tím là đặc sản, có giá trị xuất khẩu.","boPhanDung":"Củ làm gia vị; lá ăn như hành lá.",
  "xuatXu":"Có nguồn gốc Tây Á, trồng lâu đời khắp Việt Nam.","suThatThuVi":"Hành tím Vĩnh Châu (Sóc Trăng) là vùng trồng hành tím lớn nhất nước, gắn với cộng đồng người Khmer.",
  "mauDacTrung":["#7a3a55","#caa46b"],"nguon":"https://vi.wikipedia.org/wiki/H%C3%A0nh_t%C3%A2y"},
 {"id":"hong-xiem","ten":"Hồng xiêm (Sapôchê)","tenKhoaHoc":"Manilkara zapota","tenKhac":"Sapodilla · Sa pô chê","nhom":"an-qua",
  "ho":"Hồng xiêm (Sapotaceae)","phanLoai":{"bo":"Thạch nam (Ericales)","ho":"Hồng xiêm (Sapotaceae)","chi":"Manilkara","loai":"M. zapota"},
  "moTa":"Hồng xiêm (miền Nam gọi sa pô chê) là cây ăn quả nhiệt đới, quả nâu ngọt đậm, thịt mềm cát mịn.",
  "hinhThai":"Cây gỗ thường xanh, lá đơn bóng hình bầu dục, hoa nhỏ trắng, quả tròn vỏ nâu, thịt nâu nhiều hạt đen bóng.",
  "loaiThan":"Cây gỗ nhỏ","chieuCao":"8–15 m","chuKy":"Cây lâu năm","anhSang":"Ưa nắng",
  "nuoc":"Trung bình, chịu hạn khá","loaiDat":"Đất phù sa, thịt nhẹ","vungTrong":"Đồng bằng Sông Cửu Long, Đông Nam Bộ",
  "nhanGiong":"Ghép cành, chiết","thoiGianThuHoach":"Sau trồng 3–5 năm cho quả","nangSuat":"50–100 kg/cây/năm khi trưởng thành",
  "giaTri":"Quả ăn tươi ngọt đậm; gỗ và mủ chicle từng dùng làm kẹo cao su.","boPhanDung":"Quả ăn tươi; mủ cây (chicle) làm gốc kẹo cao su.",
  "xuatXu":"Có nguồn gốc Trung Mỹ (Mexico), du nhập trồng phổ biến ở Việt Nam.","suThatThuVi":"Mủ cây hồng xiêm (chicle) chính là nguyên liệu gốc của kẹo cao su truyền thống.",
  "mauDacTrung":["#7a5230","#caa46b"],"nguon":"https://vi.wikipedia.org/wiki/H%E1%BB%93ng_xi%C3%AAm"},
]
# ===== LÂM NGHIỆP (+6) =====
LAM_NGHIEP = [
 {"id":"mun","ten":"Mun","tenKhoaHoc":"Diospyros mun","tenKhac":"Ebony · gỗ mun","nhom":"go-quy",
  "ho":"Thị (Ebenaceae)","phanLoai":{"bo":"Thạch nam (Ericales)","ho":"Thị (Ebenaceae)","chi":"Diospyros","loai":"D. mun"},
  "moTa":"Mun là cây gỗ quý cho lõi gỗ đen tuyền nặng, mịn, cực bền — dùng làm đồ mỹ nghệ, tượng và đồ thờ.",
  "hinhThai":"Cây gỗ nhỏ đến trung bình, lá đơn nhỏ bóng, hoa nhỏ, lõi gỗ màu đen tuyền cứng và nặng.",
  "loaiThan":"Cây gỗ","chieuCao":"7–18 m","chuKy":"Cây lâu năm","anhSang":"Ưa sáng khi trưởng thành",
  "nuoc":"Chịu hạn","loaiDat":"Đất núi đá vôi, đất khô","vungTrong":"Khánh Hòa, Ninh Thuận, vùng núi đá Nam Trung Bộ",
  "nhanGiong":"Gieo hạt (sinh trưởng chậm)","thoiGianThuHoach":"Khai thác gỗ sau hàng chục năm","nangSuat":"—",
  "giaTri":"Gỗ mun đen quý hiếm, giá rất cao; biểu tượng của đồ gỗ mỹ nghệ cao cấp.","boPhanDung":"Lõi gỗ đen làm tượng, đồ mỹ nghệ, nhạc cụ.",
  "baoTon":"Bị khai thác quá mức, thuộc nhóm nguy cấp cần bảo vệ ở Việt Nam.",
  "xuatXu":"Loài bản địa vùng núi đá khô Nam Trung Bộ Việt Nam.","suThatThuVi":"Gỗ mun nặng tới mức chìm trong nước và để lâu càng đen bóng như sừng.",
  "mauDacTrung":["#1a1a1a","#7a6a4a"],"nguon":"https://vi.wikipedia.org/wiki/Mun_(c%C3%A2y)"},
 {"id":"hoang-dan","ten":"Hoàng đàn","tenKhoaHoc":"Cupressus tonkinensis","tenKhac":"Tonkin cypress","nhom":"go-quy",
  "ho":"Hoàng đàn (Cupressaceae)","phanLoai":{"bo":"Thông (Pinales)","ho":"Hoàng đàn (Cupressaceae)","chi":"Cupressus","loai":"C. tonkinensis"},
  "moTa":"Hoàng đàn là cây lá kim quý hiếm, gỗ và rễ thơm, được dùng làm hương liệu, đồ mỹ nghệ và trầm.",
  "hinhThai":"Cây lá kim thường xanh, lá vảy nhỏ thơm, nón tròn nhỏ, vỏ nâu đỏ, gỗ thơm.",
  "loaiThan":"Cây gỗ lá kim","chieuCao":"10–20 m","chuKy":"Cây lâu năm","anhSang":"Ưa sáng",
  "nuoc":"Chịu hạn","loaiDat":"Núi đá vôi","vungTrong":"Lạng Sơn, vùng núi đá vôi Đông Bắc",
  "nhanGiong":"Gieo hạt, giâm cành","thoiGianThuHoach":"Sinh trưởng rất chậm","nangSuat":"—",
  "giaTri":"Gỗ và rễ thơm quý; tinh dầu làm hương; rất hiếm trong tự nhiên.","boPhanDung":"Gỗ, rễ làm hương, mỹ nghệ; tinh dầu.",
  "baoTon":"Cực kỳ nguy cấp, gần như tuyệt chủng ngoài tự nhiên — được ưu tiên bảo tồn.",
  "xuatXu":"Loài đặc hữu vùng núi đá vôi Đông Bắc Việt Nam.","suThatThuVi":"Hoàng đàn quý đến mức từng bị săn lùng tận diệt để lấy rễ thơm, nay phải nhân giống bảo tồn.",
  "mauDacTrung":["#4a5a3a","#9c7a4a"],"nguon":"https://vi.wikipedia.org/wiki/Ho%C3%A0ng_%C4%91%C3%A0n"},
 {"id":"keo-la-tram","ten":"Keo lá tràm","tenKhoaHoc":"Acacia auriculiformis","tenKhac":"Earleaf acacia","nhom":"trong-rung",
  "ho":"Đậu (Fabaceae)","phanLoai":{"bo":"Đậu (Fabales)","ho":"Đậu (Fabaceae)","chi":"Acacia","loai":"A. auriculiformis"},
  "moTa":"Keo lá tràm là cây trồng rừng mọc nhanh, cố định đạm, phủ xanh đất trống và cho gỗ nguyên liệu.",
  "hinhThai":"Cây gỗ nhỏ, lá giả (phyllode) hình lưỡi liềm cong, hoa bông màu vàng, quả đậu xoắn cong.",
  "loaiThan":"Cây gỗ","chieuCao":"15–25 m","chuKy":"Cây lâu năm (chu kỳ ngắn)","anhSang":"Ưa sáng hoàn toàn",
  "nuoc":"Chịu hạn tốt","loaiDat":"Chịu được đất nghèo, đất chua","vungTrong":"Trồng rừng khắp cả nước, nhất là đất trống đồi trọc",
  "nhanGiong":"Gieo hạt, cấy mô","thoiGianThuHoach":"Khai thác sau 6–8 năm","nangSuat":"Cho gỗ dăm, gỗ nguyên liệu giấy",
  "giaTri":"Phủ xanh nhanh, cải tạo đất nhờ cố định đạm; gỗ làm dăm, giấy, ván.","boPhanDung":"Gỗ làm dăm, ván, giấy; cây che phủ cải tạo đất.",
  "baoTon":"Cây trồng phổ biến — không bị đe dọa.",
  "xuatXu":"Nguồn gốc Australia, nhập trồng rừng ở Việt Nam.","suThatThuVi":"Cái ta tưởng là 'lá' của keo thực ra là cuống lá dẹt (phyllode) — lá thật đã tiêu giảm để chịu hạn.",
  "mauDacTrung":["#5a6b2e","#caa83a"],"nguon":"https://vi.wikipedia.org/wiki/Keo_l%C3%A1_tr%C3%A0m"},
 {"id":"tre-gai","ten":"Tre gai","tenKhoaHoc":"Bambusa bambos","tenKhac":"Thorny bamboo","nhom":"trong-rung",
  "ho":"Hòa thảo (Poaceae)","phanLoai":{"bo":"Hòa thảo (Poales)","ho":"Hòa thảo (Poaceae)","chi":"Bambusa","loai":"B. bambos"},
  "moTa":"Tre gai là loài tre mọc thành bụi dày có gai, gắn với lũy tre làng, dùng làm vật liệu và măng ăn.",
  "hinhThai":"Bụi tre cao, thân đốt rỗng màu xanh, cành có gai cong, lá hình mác nhỏ.",
  "loaiThan":"Cây thân tre (hòa thảo thân hóa gỗ)","chieuCao":"10–25 m","chuKy":"Cây lâu năm","anhSang":"Ưa sáng",
  "nuoc":"Ưa ẩm, ven sông","loaiDat":"Đất phù sa, ven làng","vungTrong":"Khắp cả nước, lũy tre làng quê",
  "nhanGiong":"Tách bụi, giâm hom gốc","thoiGianThuHoach":"Khai thác thân 3–4 năm tuổi","nangSuat":"Cho thân tre và măng",
  "giaTri":"Vật liệu xây dựng, đan lát, làm giấy; măng làm thực phẩm; chắn gió giữ đất.","boPhanDung":"Thân làm vật liệu, đan lát; măng ăn.",
  "baoTon":"Cây trồng phổ biến — không bị đe dọa.",
  "xuatXu":"Loài bản địa Nam Á và Đông Nam Á, gắn bó văn hóa làng quê Việt.","suThatThuVi":"Tre có thể vươn cao cả mét mỗi ngày — thuộc nhóm thực vật mọc nhanh nhất hành tinh.",
  "mauDacTrung":["#4f7a3a","#bcae6a"],"nguon":"https://vi.wikipedia.org/wiki/Tre_gai"},
 {"id":"song-may","ten":"Song mây","tenKhoaHoc":"Calamus tetradactylus","tenKhac":"Rattan · mây","nhom":"lam-san",
  "ho":"Cau (Arecaceae)","phanLoai":{"bo":"Cau (Arecales)","ho":"Cau (Arecaceae)","chi":"Calamus","loai":"C. tetradactylus"},
  "moTa":"Song mây là cây họ cau dạng dây leo có gai, thân dẻo dai — nguyên liệu đan lát mây tre xuất khẩu.",
  "hinhThai":"Dây leo thân mảnh dài có gai, lá lông chim, thân dẻo bền sau khi xử lý.",
  "loaiThan":"Dây leo họ cau","chieuCao":"Leo dài hàng chục mét","chuKy":"Cây lâu năm","anhSang":"Ưa bóng dưới tán rừng",
  "nuoc":"Ưa ẩm","loaiDat":"Đất rừng ẩm","vungTrong":"Rừng miền Trung, miền núi phía Bắc",
  "nhanGiong":"Gieo hạt","thoiGianThuHoach":"Khai thác thân sau 5–7 năm","nangSuat":"Cho sợi mây nguyên liệu",
  "giaTri":"Lâm sản ngoài gỗ giá trị; nguyên liệu đan bàn ghế, giỏ mây xuất khẩu.","boPhanDung":"Thân (sợi mây) đan lát, làm đồ thủ công.",
  "baoTon":"Khai thác tự nhiên nhiều, đang được trồng để giảm áp lực rừng.",
  "xuatXu":"Loài bản địa rừng nhiệt đới Việt Nam.","suThatThuVi":"Một sợi mây có thể dài tới hàng trăm mét, leo bám tán rừng nhờ gai móc.",
  "mauDacTrung":["#9c7a3a","#5a6b3a"],"nguon":"https://vi.wikipedia.org/wiki/M%C3%A2y_(th%E1%BB%B1c_v%E1%BA%ADt)"},
 {"id":"boi-loi-do","ten":"Bời lời đỏ","tenKhoaHoc":"Litsea glutinosa","tenKhac":"Indian laurel","nhom":"lam-san",
  "ho":"Long não (Lauraceae)","phanLoai":{"bo":"Long não (Laurales)","ho":"Long não (Lauraceae)","chi":"Litsea","loai":"L. glutinosa"},
  "moTa":"Bời lời đỏ là cây gỗ nhỏ cho vỏ chứa chất nhầy làm keo, hương; trồng làm lâm sản và phủ xanh.",
  "hinhThai":"Cây gỗ nhỏ, lá đơn bóng, hoa nhỏ vàng, quả tròn nhỏ, vỏ chứa nhiều chất nhầy.",
  "loaiThan":"Cây gỗ nhỏ","chieuCao":"6–15 m","chuKy":"Cây lâu năm","anhSang":"Ưa sáng, chịu bán râm",
  "nuoc":"Ưa ẩm vừa","loaiDat":"Đất đồi, đất rừng","vungTrong":"Tây Nguyên, miền Trung",
  "nhanGiong":"Gieo hạt","thoiGianThuHoach":"Khai thác vỏ sau vài năm","nangSuat":"Cho vỏ bời lời nguyên liệu",
  "giaTri":"Vỏ làm keo, nhang hương; lá và vỏ dùng trong dược liệu dân gian.","boPhanDung":"Vỏ cây làm keo dán, bột nhang; lá làm thuốc.",
  "baoTon":"Cây trồng và mọc tự nhiên phổ biến — không bị đe dọa.",
  "xuatXu":"Loài bản địa nhiệt đới châu Á.","suThatThuVi":"Bột vỏ bời lời là chất kết dính tự nhiên — nguyên liệu truyền thống để làm nhang (hương).",
  "mauDacTrung":["#7a3a2e","#5a6b3a"],"nguon":"https://vi.wikipedia.org/wiki/B%E1%BB%9Di_l%E1%BB%9Di"},
]
# ===== CHĂN NUÔI (+10) =====
CHAN_NUOI = [
 {"id":"bo-thit","ten":"Bò thịt","tenKhoaHoc":"Bos taurus","tenKhac":"Beef cattle · bò vàng","nhom":"gia-suc",
  "moTa":"Bò thịt (gồm bò vàng nội và bò lai) nuôi lấy thịt, tận dụng cỏ và phụ phẩm, phổ biến ở nông hộ.",
  "giong":"Bò vàng VN, bò lai Sind, bò lai BBB/Brahman","trongLuong":"250–500 kg (bò lai cao hơn)",
  "thucAn":"Cỏ, rơm, phụ phẩm nông nghiệp, thức ăn tinh vỗ béo","chuongTrai":"Chuồng thoáng, có sân; kết hợp chăn thả",
  "sinhSan":"Mang thai ~9 tháng, 1 bê/năm","thoiGianNuoi":"Nuôi thịt 18–24 tháng, vỗ béo 2–3 tháng cuối",
  "sanPham":"Thịt bò, con giống, da, phân","benhThuongGap":"Lở mồm long móng, tụ huyết trùng, ký sinh trùng",
  "vungNuoi":"Trung Bộ, Tây Nguyên, Đồng bằng Sông Cửu Long","giaTri":"Nguồn thịt đỏ giá trị; bò lai cải thiện năng suất rõ rệt.",
  "suThatThuVi":"Bò có dạ dày 4 ngăn và nhai lại — nhờ vi sinh vật dạ cỏ tiêu hóa được cỏ mà người không tiêu hóa nổi.",
  "mauDacTrung":["#a0622e","#e8d3a8"],"nguon":"https://vi.wikipedia.org/wiki/B%C3%B2_nh%C3%A0"},
 {"id":"cuu","ten":"Cừu","tenKhoaHoc":"Ovis aries","tenKhac":"Sheep","nhom":"gia-suc",
  "moTa":"Cừu nuôi lấy thịt và lông, thích nghi vùng khô hạn nắng gió; ở VN tập trung tại Ninh Thuận, Bình Thuận.",
  "giong":"Cừu Phan Rang (thích nghi khô hạn)","trongLuong":"35–55 kg",
  "thucAn":"Cỏ, lá cây bụi, phụ phẩm; chịu khô hạn","chuongTrai":"Chuồng sàn cao thoáng, có bãi chăn thả",
  "sinhSan":"Mang thai ~5 tháng, 1–2 con/lứa","thoiGianNuoi":"Cừu thịt 7–9 tháng",
  "sanPham":"Thịt cừu, lông, da","benhThuongGap":"Ký sinh trùng, tụ huyết trùng, bệnh móng",
  "vungNuoi":"Ninh Thuận, Bình Thuận (vùng khô hạn)","giaTri":"Thịt cừu đặc sản; gắn với du lịch đồng cừu Ninh Thuận.",
  "suThatThuVi":"Cừu Phan Rang là giống cừu hiếm hoi thích nghi được khí hậu khô nóng nhiệt đới của Việt Nam.",
  "mauDacTrung":["#e8e2d2","#b5a07a"],"nguon":"https://vi.wikipedia.org/wiki/C%E1%BB%ABu_nh%C3%A0"},
 {"id":"huou-sao","ten":"Hươu sao","tenKhoaHoc":"Cervus nippon","tenKhac":"Sika deer","nhom":"gia-suc",
  "moTa":"Hươu sao nuôi chủ yếu lấy nhung (sừng non) — dược liệu quý; lông nâu đốm trắng đặc trưng.",
  "giong":"Hươu sao thuần dưỡng","trongLuong":"50–80 kg",
  "thucAn":"Lá cây, cỏ, củ quả; ăn thực vật đa dạng","chuongTrai":"Chuồng chắc chắn có sân vận động, yên tĩnh",
  "sinhSan":"Mang thai ~7,5 tháng, 1 con/lứa","thoiGianNuoi":"Hươu đực cắt nhung mỗi năm sau 2–3 tuổi",
  "sanPham":"Nhung hươu (dược liệu), con giống, thịt","benhThuongGap":"Chướng bụng, ký sinh trùng, stress",
  "vungNuoi":"Hà Tĩnh (Hương Sơn), Nghệ An","giaTri":"Nhung hươu là dược liệu bồi bổ giá trị cao; nghề nuôi truyền thống.",
  "suThatThuVi":"Mỗi năm hươu đực rụng sừng cũ và mọc lại cặp nhung mới — nhung non phủ nhung mịn chính là phần quý giá.",
  "mauDacTrung":["#8a5a2e","#e8d3a8"],"nguon":"https://vi.wikipedia.org/wiki/H%C6%B0%C6%A1u_sao"},
 {"id":"bo-cau","ten":"Bồ câu","tenKhoaHoc":"Columba livia domestica","tenKhac":"Domestic pigeon","nhom":"gia-cam",
  "moTa":"Bồ câu nuôi lấy thịt (bồ câu ra ràng) và làm cảnh; sinh sản nhanh, dễ nuôi, ít bệnh.",
  "giong":"Bồ câu ta, bồ câu Pháp (lấy thịt)","trongLuong":"500–700 g/con",
  "thucAn":"Thóc, ngô, đậu, cám viên","chuongTrai":"Chuồng tổ từng ô, khô ráo, thoáng, yên tĩnh",
  "sinhSan":"Đẻ 2 trứng/lứa, ấp ~18 ngày, 7–9 lứa/năm","thoiGianNuoi":"Bồ câu ra ràng 28–35 ngày",
  "sanPham":"Thịt bồ câu ra ràng, chim cảnh","benhThuongGap":"Newcastle, đậu bồ câu, hô hấp",
  "vungNuoi":"Khắp cả nước","giaTri":"Thịt bổ dưỡng được ưa chuộng; vốn nhỏ, quay vòng nhanh.",
  "suThatThuVi":"Chim bồ câu bố mẹ tiết 'sữa diều' để mớm cho con — loài chim hiếm hoi 'cho con bú' bằng sữa.",
  "mauDacTrung":["#8a8f99","#d8d2c4"],"nguon":"https://vi.wikipedia.org/wiki/B%E1%BB%93_c%C3%A2u_nh%C3%A0"},
 {"id":"ga-tay","ten":"Gà tây","tenKhoaHoc":"Meleagris gallopavo","tenKhac":"Turkey","nhom":"gia-cam",
  "moTa":"Gà tây là gia cầm cỡ lớn nuôi lấy thịt, con đực có đuôi xòe và yếm đỏ; thịt nhiều, ít mỡ.",
  "giong":"Gà tây nội, gà tây lai","trongLuong":"Trống 8–12 kg, mái 4–6 kg",
  "thucAn":"Cám, ngô, rau xanh, chăn thả","chuongTrai":"Chuồng rộng có sân thả, khô thoáng",
  "sinhSan":"Đẻ theo mùa, ấp ~28 ngày","thoiGianNuoi":"4–5 tháng",
  "sanPham":"Thịt gà tây","benhThuongGap":"Đầu đen (Histomonas), Newcastle, tụ huyết trùng",
  "vungNuoi":"Rải rác cả nước (mô hình trang trại)","giaTri":"Thịt nạc nhiều, phù hợp nuôi lấy thịt quy mô; dịp lễ tiêu thụ cao.",
  "suThatThuVi":"Gà tây trống xòe đuôi và phồng yếm đỏ để khoe mẽ; da mặt đổi màu theo cảm xúc.",
  "mauDacTrung":["#3a2e2a","#a0402e"],"nguon":"https://vi.wikipedia.org/wiki/G%C3%A0_t%C3%A2y"},
 {"id":"da-dieu","ten":"Đà điểu","tenKhoaHoc":"Struthio camelus","tenKhac":"Ostrich","nhom":"gia-cam",
  "moTa":"Đà điểu là chim lớn nhất hành tinh, nuôi lấy thịt, da và trứng; chạy nhanh, không bay.",
  "giong":"Đà điểu châu Phi","trongLuong":"90–150 kg",
  "thucAn":"Cỏ, rau, cám viên; cần sỏi nhỏ hỗ trợ tiêu hóa","chuongTrai":"Sân chạy rộng rào chắc, nền cát khô",
  "sinhSan":"Đẻ trứng to (~1,5 kg/quả), ấp ~42 ngày","thoiGianNuoi":"Nuôi thịt 10–12 tháng",
  "sanPham":"Thịt đỏ ít mỡ, da (làm đồ da cao cấp), trứng, lông","benhThuongGap":"Bệnh đường ruột, stress, què chân",
  "vungNuoi":"Ba Vì, Khánh Hòa, các trang trại lớn","giaTri":"Thịt đỏ giàu đạm ít cholesterol; da đà điểu là hàng da cao cấp.",
  "suThatThuVi":"Đà điểu chạy tới 70 km/h và một quả trứng đà điểu nặng bằng khoảng 24 quả trứng gà.",
  "mauDacTrung":["#2a2a2a","#d8c4a0"],"nguon":"https://vi.wikipedia.org/wiki/%C4%90%C3%A0_%C4%91i%E1%BB%83u"},
 {"id":"tam","ten":"Tằm","tenKhoaHoc":"Bombyx mori","tenKhac":"Silkworm · con tằm","nhom":"vat-nuoi-khac",
  "moTa":"Tằm là ấu trùng ăn lá dâu, nhả tơ làm kén — nền tảng nghề ươm tơ dệt lụa truyền thống.",
  "giong":"Tằm dâu lưỡng hệ, đa hệ","trongLuong":"Kén ~2 g; nuôi theo nong/né",
  "thucAn":"Lá dâu tằm tươi (ăn liên tục)","chuongTrai":"Nong nia, né tằm nơi sạch, thoáng, kín gió",
  "sinhSan":"Vòng đời ~25–30 ngày: trứng → tằm → kén → ngài","thoiGianNuoi":"Một lứa tằm ~20–25 ngày tới khi lên kén",
  "sanPham":"Tơ tằm (kén), nhộng tằm (thực phẩm)","benhThuongGap":"Bệnh gai, bủng, vôi (do nấm/vi khuẩn)",
  "vungNuoi":"Lâm Đồng (Bảo Lộc), Hà Nam, vùng trồng dâu","giaTri":"Nền của nghề tơ lụa (Bảo Lộc, Vạn Phúc); nhộng tằm là món ăn giàu đạm.",
  "suThatThuVi":"Một con tằm nhả sợi tơ dài liên tục 700–1.500 m để cuộn thành một cái kén.",
  "mauDacTrung":["#e8e2cf","#c9b06a"],"nguon":"https://vi.wikipedia.org/wiki/T%E1%BA%B1m"},
 {"id":"trun-que","ten":"Trùn quế","tenKhoaHoc":"Perionyx excavatus","tenKhac":"Earthworm · giun quế","nhom":"vat-nuoi-khac",
  "moTa":"Trùn quế nuôi để xử lý chất thải hữu cơ, tạo phân trùn và làm thức ăn giàu đạm cho gia cầm, thủy sản.",
  "giong":"Trùn quế (giun quế)","trongLuong":"Nuôi theo luống, sinh khối tính bằng kg/m²",
  "thucAn":"Phân gia súc, rác hữu cơ, bã thực vật","chuongTrai":"Luống nuôi che mát, ẩm, thoát nước; nền phân hữu cơ",
  "sinhSan":"Sinh sản rất nhanh, lưỡng tính, đẻ kén liên tục","thoiGianNuoi":"Thu sinh khối & phân sau 30–45 ngày",
  "sanPham":"Phân trùn quế (phân bón hữu cơ), sinh khối trùn làm thức ăn chăn nuôi","benhThuongGap":"Chết do nắng nóng, ngập úng, thức ăn ôi",
  "vungNuoi":"Khắp cả nước (mô hình nông nghiệp tuần hoàn)","giaTri":"Biến rác hữu cơ thành phân bón quý; mắt xích nông nghiệp tuần hoàn, hữu cơ.",
  "suThatThuVi":"Trùn quế ăn lượng thức ăn gần bằng trọng lượng cơ thể mỗi ngày, biến phân chuồng thành phân bón sạch.",
  "mauDacTrung":["#7a3a2e","#3a2a22"],"nguon":"https://vi.wikipedia.org/wiki/Tr%C3%B9n_qu%E1%BA%BF"},
 {"id":"de-men","ten":"Dế","tenKhoaHoc":"Gryllus bimaculatus","tenKhac":"Cricket · dế mèn","nhom":"vat-nuoi-khac",
  "moTa":"Dế nuôi làm thực phẩm giàu đạm và mồi câu/thức ăn vật nuôi; vòng đời ngắn, vốn rất nhỏ.",
  "giong":"Dế ta, dế Thái","trongLuong":"Nuôi theo thùng/chuồng, tính theo kg",
  "thucAn":"Cám, rau, cỏ, bí ngô","chuongTrai":"Thùng/xô có rế giấy, lưới che, thoáng ấm",
  "sinhSan":"Đẻ trứng vào khay đất ẩm, nở sau ~10 ngày","thoiGianNuoi":"Thu hoạch sau 35–45 ngày",
  "sanPham":"Dế thương phẩm (thực phẩm), mồi câu, thức ăn chim cá","benhThuongGap":"Chết do ẩm thấp, nấm, mật độ quá dày",
  "vungNuoi":"Đồng bằng Sông Cửu Long, Đông Nam Bộ","giaTri":"Đạm côn trùng bền vững; món dế chiên là đặc sản đồng quê.",
  "suThatThuVi":"Côn trùng như dế được xem là nguồn 'đạm xanh' tương lai vì nuôi tốn rất ít nước và thức ăn so với gia súc.",
  "mauDacTrung":["#3a2e22","#8a6a3a"],"nguon":"https://vi.wikipedia.org/wiki/D%E1%BA%BF_m%C3%A8n"},
 {"id":"nhim","ten":"Nhím","tenKhoaHoc":"Hystrix brachyura","tenKhac":"Porcupine","nhom":"vat-nuoi-khac",
  "moTa":"Nhím nuôi lấy thịt đặc sản, thân phủ lông gai; dễ nuôi, ít bệnh, ăn tạp.",
  "giong":"Nhím bờm (nhím ta)","trongLuong":"10–18 kg",
  "thucAn":"Củ quả, rau, ngô, phụ phẩm","chuongTrai":"Chuồng xi măng chắc, khô ráo, có hang trú",
  "sinhSan":"Mang thai ~3 tháng, 1–3 con/lứa, 2 lứa/năm","thoiGianNuoi":"Nuôi thịt 8–12 tháng",
  "sanPham":"Thịt nhím (đặc sản), con giống","benhThuongGap":"Tiêu chảy, ký sinh trùng, đau mắt",
  "vungNuoi":"Trung du, miền núi, các trại nuôi","giaTri":"Thịt đặc sản giá cao; mô hình nuôi sinh sản cho con giống có lãi.",
  "suThatThuVi":"Khi gặp nguy, nhím dựng đứng bộ lông gai và rung kêu lạch cạch để dọa kẻ thù — gai có thể cắm rời ra.",
  "mauDacTrung":["#2a2a2a","#d8d2c4"],"nguon":"https://vi.wikipedia.org/wiki/Nh%C3%ADm"},
]
# ===== THỦY SẢN (+10) =====
THUY_SAN = [
 {"id":"ca-chep","ten":"Cá chép","tenKhoaHoc":"Cyprinus carpio","tenKhac":"Common carp","nhom":"ca-nuoi",
  "moTa":"Cá chép là cá nước ngọt nuôi lâu đời, dễ nuôi, ăn tạp; gắn với văn hóa và ẩm thực Việt.",
  "moiTruongNuoc":"Nước ngọt (ao, hồ, ruộng)","nhietDoPH":"20–30°C, pH 6,5–8,5",
  "thucAn":"Ăn tạp: mùn bã, sinh vật đáy, cám, thức ăn viên","hinhThucNuoi":"Ao, ruộng lúa-cá, lồng; mật độ vừa",
  "thuHoach":"6–10 tháng, đạt 0,5–1,5 kg/con","sanLuong":"Khá, tùy hình thức nuôi",
  "sanPham":"Cá thịt tươi","benhThuongGap":"Nấm, trùng mỏ neo, xuất huyết",
  "vungNuoi":"Đồng bằng Sông Hồng, miền núi phía Bắc","giaTri":"Cá ăn phổ thông; cá chép gắn với mâm cúng và lễ ông Công ông Táo.",
  "suThatThuVi":"Cá chép là tổ tiên hoang dã của cá Koi và cá vàng cảnh ngày nay.",
  "mauDacTrung":["#b5894a","#d8c8a0"],"nguon":"https://vi.wikipedia.org/wiki/C%C3%A1_ch%C3%A9p"},
 {"id":"ca-tram-co","ten":"Cá trắm cỏ","tenKhoaHoc":"Ctenopharyngodon idella","tenKhac":"Grass carp","nhom":"ca-nuoi",
  "moTa":"Cá trắm cỏ ăn cỏ và rau, lớn nhanh, là cá nuôi ao truyền thống ở miền Bắc.",
  "moiTruongNuoc":"Nước ngọt (ao, hồ)","nhietDoPH":"22–30°C, pH 6,5–8,5",
  "thucAn":"Cỏ, lá, rau, bèo; thức ăn viên bổ sung","hinhThucNuoi":"Ao nuôi ghép, lồng; mật độ vừa",
  "thuHoach":"10–14 tháng, đạt 1,5–3 kg/con","sanLuong":"Khá cao trong ao nuôi ghép",
  "sanPham":"Cá thịt tươi","benhThuongGap":"Xuất huyết do virus, nấm, ký sinh trùng",
  "vungNuoi":"Đồng bằng Sông Hồng, trung du Bắc Bộ","giaTri":"Cá thịt phổ thông, tận dụng cỏ rau sẵn có; thường nuôi ghép với chép, mè.",
  "suThatThuVi":"Cá trắm cỏ ăn rau cỏ khỏe đến mức được nhiều nơi thả để dọn cỏ dại trong ao hồ.",
  "mauDacTrung":["#7a8b5a","#d8d2b0"],"nguon":"https://vi.wikipedia.org/wiki/C%C3%A1_tr%E1%BA%AFm_c%E1%BB%8F"},
 {"id":"ca-basa","ten":"Cá basa","tenKhoaHoc":"Pangasius bocourti","tenKhac":"Basa fish","nhom":"ca-nuoi",
  "moTa":"Cá basa là cá da trơn sông Mekong, thịt béo trắng; cùng cá tra là mặt hàng phi lê xuất khẩu.",
  "moiTruongNuoc":"Nước ngọt (sông, bè)","nhietDoPH":"26–30°C, pH 6,5–8",
  "thucAn":"Thức ăn viên, cám, phụ phẩm","hinhThucNuoi":"Bè trên sông, ao; thâm canh",
  "thuHoach":"8–10 tháng, đạt ~1–1,5 kg/con","sanLuong":"Cao trong nuôi bè",
  "sanPham":"Phi lê đông lạnh xuất khẩu, cá thịt","benhThuongGap":"Gan thận mủ, xuất huyết, ký sinh trùng",
  "vungNuoi":"An Giang, Đồng Tháp (sông Tiền, sông Hậu)","giaTri":"Mặt hàng phi lê xuất khẩu của ĐBSCL, thịt béo hơn cá tra.",
  "suThatThuVi":"Cá basa có bụng tích mỡ nên thịt béo — tên 'ba sa' theo tiếng địa phương ám chỉ lớp mỡ ba sa đặc trưng.",
  "mauDacTrung":["#9aa0a6","#e3e7ea"],"nguon":"https://vi.wikipedia.org/wiki/C%C3%A1_ba_sa"},
 {"id":"ca-keo","ten":"Cá kèo","tenKhoaHoc":"Pseudapocryptes elongatus","tenKhac":"Goby","nhom":"ca-nuoi",
  "moTa":"Cá kèo là cá nhỏ sống vùng bãi bồi cửa sông nước lợ, đặc sản miền Tây (lẩu cá kèo).",
  "moiTruongNuoc":"Nước lợ (bãi bồi, ao ven biển)","nhietDoPH":"26–32°C, độ mặn 5–20‰",
  "thucAn":"Mùn bã hữu cơ, tảo đáy, thức ăn viên","hinhThucNuoi":"Ao đất vùng nước lợ, mật độ cao",
  "thuHoach":"4–5 tháng, đạt 25–40 con/kg","sanLuong":"Khá cao trong ao nước lợ",
  "sanPham":"Cá kèo tươi (đặc sản)","benhThuongGap":"Ký sinh trùng, lở loét, sốc môi trường",
  "vungNuoi":"Bạc Liêu, Sóc Trăng, Cà Mau","giaTri":"Đặc sản miền Tây; lẩu cá kèo lá giang là món nổi tiếng.",
  "suThatThuVi":"Cá kèo thuộc họ cá bống, có thể trườn và sống một thời gian trên bãi bùn lúc triều rút.",
  "mauDacTrung":["#8a7a5a","#cabf9a"],"nguon":"https://vi.wikipedia.org/wiki/C%C3%A1_k%C3%A8o"},
 {"id":"ca-chinh","ten":"Cá chình","tenKhoaHoc":"Anguilla marmorata","tenKhac":"Marbled eel","nhom":"ca-nuoi",
  "moTa":"Cá chình thân dài như rắn, thịt béo bổ, giá cao; nuôi trong ao, bể nước ngọt.",
  "moiTruongNuoc":"Nước ngọt (ao, bể); sinh sản ngoài biển","nhietDoPH":"25–30°C, pH 7–8",
  "thucAn":"Cá tạp, thức ăn tươi, thức ăn viên đạm cao","hinhThucNuoi":"Ao, bể xi măng, lồng; mật độ vừa",
  "thuHoach":"12–18 tháng, đạt 1–2 kg/con","sanLuong":"Giá trị cao dù sản lượng vừa",
  "sanPham":"Cá chình thương phẩm (đặc sản giá cao)","benhThuongGap":"Nấm, ký sinh trùng, bệnh đường ruột",
  "vungNuoi":"Phú Yên, Bình Định, miền Trung","giaTri":"Đặc sản bổ dưỡng giá cao; con giống còn phụ thuộc đánh bắt tự nhiên.",
  "suThatThuVi":"Cá chình ngược dòng đời cá hồi: sống ở sông suối nhưng bơi ra tận biển sâu để sinh sản rồi chết.",
  "mauDacTrung":["#5a5a4a","#b5ac8a"],"nguon":"https://vi.wikipedia.org/wiki/C%C3%A1_ch%C3%ACnh"},
 {"id":"tom-cang-xanh","ten":"Tôm càng xanh","tenKhoaHoc":"Macrobrachium rosenbergii","tenKhac":"Giant freshwater prawn","nhom":"giap-xac",
  "moTa":"Tôm càng xanh là tôm nước ngọt lớn, càng dài xanh, thịt chắc ngọt; nuôi ao và xen ruộng lúa.",
  "moiTruongNuoc":"Nước ngọt và lợ nhẹ","nhietDoPH":"26–31°C, pH 7–8,5",
  "thucAn":"Thức ăn viên, ốc, cá tạp; ăn tạp thiên động vật","hinhThucNuoi":"Ao, mô hình tôm-lúa, mật độ vừa",
  "thuHoach":"5–6 tháng, đạt 30–60 g/con","sanLuong":"Vừa, giá bán cao",
  "sanPham":"Tôm thương phẩm (nội địa & xuất khẩu)","benhThuongGap":"Đóng rong, đục cơ, bệnh đường ruột",
  "vungNuoi":"Đồng bằng Sông Cửu Long (An Giang, Đồng Tháp, Bạc Liêu)","giaTri":"Tôm nước ngọt giá trị cao; mô hình tôm-lúa luân canh bền vững.",
  "suThatThuVi":"Tôm càng xanh đực có đôi càng dài xanh biếc dài hơn cả thân — vừa để đánh nhau vừa để hấp dẫn con cái.",
  "mauDacTrung":["#3a6b7a","#cabf9a"],"nguon":"https://vi.wikipedia.org/wiki/T%C3%B4m_c%C3%A0ng_xanh"},
 {"id":"ghe","ten":"Ghẹ","tenKhoaHoc":"Portunus pelagicus","tenKhac":"Blue swimming crab","nhom":"giap-xac",
  "moTa":"Ghẹ là loài cua bơi vùng biển ven bờ, mai xanh đốm, thịt ngọt; vừa đánh bắt vừa nuôi.",
  "moiTruongNuoc":"Nước mặn ven biển","nhietDoPH":"26–30°C, độ mặn 25–33‰",
  "thucAn":"Cá tạp, nhuyễn thể, giáp xác nhỏ","hinhThucNuoi":"Nuôi lồng/ao nước mặn; phần lớn còn đánh bắt tự nhiên",
  "thuHoach":"3–4 tháng (nuôi), đạt 100–250 g/con","sanLuong":"Tùy mùa và ngư trường",
  "sanPham":"Ghẹ thịt, ghẹ lột, ghẹ gạch","benhThuongGap":"Mềm vỏ, ký sinh, sốc độ mặn",
  "vungNuoi":"Kiên Giang, Khánh Hòa, vùng biển ven bờ","giaTri":"Hải sản giá trị cao; ghẹ Hàm Ninh (Phú Quốc) là đặc sản nổi tiếng.",
  "suThatThuVi":"Cặp chân sau của ghẹ dẹt như mái chèo, giúp nó bơi nhanh trong nước — khác hẳn cua chỉ bò.",
  "mauDacTrung":["#3a6b8a","#cabf9a"],"nguon":"https://vi.wikipedia.org/wiki/Gh%E1%BA%B9"},
 {"id":"luon","ten":"Lươn","tenKhoaHoc":"Monopterus albus","tenKhac":"Asian swamp eel","nhom":"thuy-san-khac",
  "moTa":"Lươn đồng thân trơn dài, sống chui bùn; nuôi không bùn trong bể bạt cho thịt bổ, ít xương.",
  "moiTruongNuoc":"Nước ngọt (bùn, bể)","nhietDoPH":"25–30°C, pH 6,5–8",
  "thucAn":"Trùn, ốc, cá tạp, thức ăn viên đạm cao","hinhThucNuoi":"Bể bạt nuôi không bùn (có giá thể), mật độ cao",
  "thuHoach":"5–8 tháng, đạt 150–250 g/con","sanLuong":"Cao trong bể nuôi không bùn",
  "sanPham":"Lươn thương phẩm (đặc sản: cháo lươn, miến lươn)","benhThuongGap":"Lở loét, nấm, đường ruột",
  "vungNuoi":"Nghệ An, Đồng bằng Sông Cửu Long","giaTri":"Thịt bổ dưỡng được ưa chuộng; nuôi không bùn dễ quản lý, ít dịch bệnh.",
  "suThatThuVi":"Lươn có thể đổi giới tính: phần lớn lươn cái khi lớn lên sẽ chuyển thành lươn đực.",
  "mauDacTrung":["#8a6a3a","#3a2e22"],"nguon":"https://vi.wikipedia.org/wiki/L%C6%B0%C6%A1n"},
 {"id":"oc-buou-den","ten":"Ốc bươu đen","tenKhoaHoc":"Pila polita","tenKhac":"Black apple snail","nhom":"thuy-san-khac",
  "moTa":"Ốc bươu đen là ốc bản địa nước ngọt, vỏ đen tròn, thịt giòn — đặc sản đồng quê đang được nuôi lại.",
  "moiTruongNuoc":"Nước ngọt (ao, mương, ruộng)","nhietDoPH":"25–30°C, pH 6,5–8",
  "thucAn":"Bèo, lá, rau, mùn hữu cơ; ăn thực vật","hinhThucNuoi":"Ao, bể, ruộng có cây thủy sinh; mật độ vừa",
  "thuHoach":"4–5 tháng, đạt 25–35 con/kg","sanLuong":"Khá, vốn thấp",
  "sanPham":"Ốc thương phẩm (đặc sản), ốc giống","benhThuongGap":"Sưng vòi, chết do nước bẩn, thiếu canxi mỏng vỏ",
  "vungNuoi":"Đồng bằng Sông Cửu Long, đồng bằng Bắc Bộ","giaTri":"Đặc sản đồng quê được ưa chuộng; phân biệt với ốc bươu vàng gây hại.",
  "suThatThuVi":"Ốc bươu đen là loài bản địa có ích, khác hẳn ốc bươu vàng ngoại lai phá lúa.",
  "mauDacTrung":["#2a2a22","#7a6a4a"],"nguon":"https://vi.wikipedia.org/wiki/%E1%BB%90c_b%C6%B0%C6%A1u_%C4%91en"},
 {"id":"ba-ba","ten":"Ba ba","tenKhoaHoc":"Pelodiscus sinensis","tenKhac":"Softshell turtle · cua đinh","nhom":"thuy-san-khac",
  "moTa":"Ba ba là rùa mai mềm nước ngọt, nuôi lấy thịt đặc sản giá cao; mai dẹt, cổ dài, sống đáy.",
  "moiTruongNuoc":"Nước ngọt (ao, bể có chỗ phơi nắng)","nhietDoPH":"25–32°C, pH 7–8",
  "thucAn":"Cá tạp, ốc, giun, thức ăn tươi","hinhThucNuoi":"Ao/bể có bãi cát phơi nắng, nước sạch; mật độ thấp",
  "thuHoach":"15–24 tháng, đạt 1–2 kg/con","sanLuong":"Vừa, giá bán cao",
  "sanPham":"Ba ba thương phẩm (đặc sản), con giống","benhThuongGap":"Nấm, sưng cổ, lở loét mai",
  "vungNuoi":"Đồng bằng Sông Hồng, Đồng bằng Sông Cửu Long","giaTri":"Đặc sản bổ dưỡng giá cao; nghề nuôi ba ba sinh sản cho lãi tốt.",
  "suThatThuVi":"Ba ba thở bằng phổi nhưng có thể ở dưới nước rất lâu nhờ hấp thu thêm oxy qua da và niêm mạc họng.",
  "mauDacTrung":["#5a6b4a","#cabf9a"],"nguon":"https://vi.wikipedia.org/wiki/Ba_ba"},
]

def main():
    data = json.load(open(PATH, encoding='utf-8'))
    existing = {c['id'] for c in data['cay']}
    added = 0
    groups = [('nong-nghiep', TRONG_TROT), ('lam-nghiep', LAM_NGHIEP),
              ('chan-nuoi', CHAN_NUOI), ('thuy-san', THUY_SAN)]
    for lv, recs in groups:
        for rec in recs:
            if rec['id'] in existing:
                print('SKIP (exists):', rec['id']); continue
            rec['linhVuc'] = lv
            rec['anh'] = f"img/{rec['id']}.jpg"
            data['cay'].append(rec); added += 1
    data['_meta']['capNhat'] = '2026-05-27'
    json.dump(data, open(PATH, 'w', encoding='utf-8'), ensure_ascii=False, indent=2)
    print(f'Added {added} mục. Tổng: {len(data["cay"])} mục.')

if __name__ == '__main__':
    main()
